<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 28 Meanings of FROC figures of merit | The RJafroc Book</title>
  <meta name="description" content="Artificial intelligence and observer performance book based on RJafroc." />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 28 Meanings of FROC figures of merit | The RJafroc Book" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Artificial intelligence and observer performance book based on RJafroc." />
  <meta name="github-repo" content="dpc10ster/RJafrocBook" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 28 Meanings of FROC figures of merit | The RJafroc Book" />
  
  <meta name="twitter:description" content="Artificial intelligence and observer performance book based on RJafroc." />
  

<meta name="author" content="Dev P. Chakraborty, PhD" />


<meta name="date" content="2021-12-18" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="froc-vs-wafroc.html"/>
<link rel="next" href="visual-search.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">RJafroc documentation</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#tba-how-much-finished"><i class="fa fa-check"></i>TBA How much finished</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#the-pdf-file-of-the-book"><i class="fa fa-check"></i>The pdf file of the book</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#a-note-on-the-online-distribution-mechanism-of-the-book"><i class="fa fa-check"></i>A note on the online distribution mechanism of the book</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#structure-of-the-book"><i class="fa fa-check"></i>Structure of the book</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#contributing-to-this-book"><i class="fa fa-check"></i>Contributing to this book</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#is-this-book-relevant-to-you-and-what-are-the-alternatives"><i class="fa fa-check"></i>Is this book relevant to you and what are the alternatives?</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#todos-tba"><i class="fa fa-check"></i>ToDos TBA</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#chapters-needing-heavy-edits"><i class="fa fa-check"></i>Chapters needing heavy edits</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#shelved-vs.-removed-vs.-parked-folders-needing-heavy-edits"><i class="fa fa-check"></i>Shelved vs. removed vs. parked folders needing heavy edits</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#coding-aids"><i class="fa fa-check"></i>Coding aids</a></li>
</ul></li>
<li class="part"><span><b>Quick Start</b></span></li>
<li class="chapter" data-level="1" data-path="quick-start-help.html"><a href="quick-start-help.html"><i class="fa fa-check"></i><b>1</b> Help</a><ul>
<li class="chapter" data-level="1.1" data-path="quick-start-help.html"><a href="quick-start-help.html#quick-start-help-how-much-finished"><i class="fa fa-check"></i><b>1.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="1.2" data-path="quick-start-help.html"><a href="quick-start-help.html#quick-start-help-getting-help"><i class="fa fa-check"></i><b>1.2</b> Getting help on the software</a></li>
<li class="chapter" data-level="1.3" data-path="quick-start-help.html"><a href="quick-start-help.html#quick-start-help-references"><i class="fa fa-check"></i><b>1.3</b> References</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="quick-start-data-format.html"><a href="quick-start-data-format.html"><i class="fa fa-check"></i><b>2</b> JAFROC data format</a><ul>
<li class="chapter" data-level="2.1" data-path="quick-start-data-format.html"><a href="quick-start-data-format.html#quick-start-data-format-how-much-finished"><i class="fa fa-check"></i><b>2.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="2.2" data-path="quick-start-data-format.html"><a href="quick-start-data-format.html#quick-start-data-format-intro"><i class="fa fa-check"></i><b>2.2</b> Introduction</a></li>
<li class="chapter" data-level="2.3" data-path="quick-start-data-format.html"><a href="quick-start-data-format.html#quick-start-data-format-note-to-existing-users"><i class="fa fa-check"></i><b>2.3</b> Note to existing users</a></li>
<li class="chapter" data-level="2.4" data-path="quick-start-data-format.html"><a href="quick-start-data-format.html#quick-start-data-format-contents"><i class="fa fa-check"></i><b>2.4</b> Contents of Excel file</a></li>
<li class="chapter" data-level="2.5" data-path="quick-start-data-format.html"><a href="quick-start-data-format.html#quick-start-data-format-truth-worksheet"><i class="fa fa-check"></i><b>2.5</b> The <code>Truth</code> worksheet</a></li>
<li class="chapter" data-level="2.6" data-path="quick-start-data-format.html"><a href="quick-start-data-format.html#quick-start-data-fp-worksheet"><i class="fa fa-check"></i><b>2.6</b> The false positive (FP) ratings</a></li>
<li class="chapter" data-level="2.7" data-path="quick-start-data-format.html"><a href="quick-start-data-format.html#quick-start-data-format-tp-worksheet"><i class="fa fa-check"></i><b>2.7</b> The true positive (TP) ratings</a></li>
<li class="chapter" data-level="2.8" data-path="quick-start-data-format.html"><a href="quick-start-data-format.html#quick-start-data-format-single-reader"><i class="fa fa-check"></i><b>2.8</b> A single reader dataset</a></li>
<li class="chapter" data-level="2.9" data-path="quick-start-data-format.html"><a href="quick-start-data-format.html#quick-start-data-format-references"><i class="fa fa-check"></i><b>2.9</b> References</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="quick-start-read-datafile.html"><a href="quick-start-read-datafile.html"><i class="fa fa-check"></i><b>3</b> Reading the Excel data file</a><ul>
<li class="chapter" data-level="3.1" data-path="quick-start-read-datafile.html"><a href="quick-start-read-datafile.html#quick-start-read-datafile-how-much-finished"><i class="fa fa-check"></i><b>3.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="3.2" data-path="quick-start-read-datafile.html"><a href="quick-start-read-datafile.html#quick-start-read-datafile-intro"><i class="fa fa-check"></i><b>3.2</b> Introduction</a></li>
<li class="chapter" data-level="3.3" data-path="quick-start-read-datafile.html"><a href="quick-start-read-datafile.html#quick-start-read-datafile-structure-roc-dataset"><i class="fa fa-check"></i><b>3.3</b> The structure of an ROC dataset</a></li>
<li class="chapter" data-level="3.4" data-path="quick-start-read-datafile.html"><a href="quick-start-read-datafile.html#quick-start-read-datafile-correspondence-nl-fp"><i class="fa fa-check"></i><b>3.4</b> Correspondence between <code>NL</code> member of dataset and the <code>FP</code> worksheet</a></li>
<li class="chapter" data-level="3.5" data-path="quick-start-read-datafile.html"><a href="quick-start-read-datafile.html#quick-start-read-datafile-correspondence-case-index-vs-case-id"><i class="fa fa-check"></i><b>3.5</b> Case-index vs. caseID</a></li>
<li class="chapter" data-level="3.6" data-path="quick-start-read-datafile.html"><a href="quick-start-read-datafile.html#quick-start-read-datafile-correspondence-ll-tp"><i class="fa fa-check"></i><b>3.6</b> Correspondence between <code>LL</code> member of dataset and the <code>TP</code> worksheet</a></li>
<li class="chapter" data-level="3.7" data-path="quick-start-read-datafile.html"><a href="quick-start-read-datafile.html#quick-start-read-datafile-references"><i class="fa fa-check"></i><b>3.7</b> References</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="quick-start-froc-data-format.html"><a href="quick-start-froc-data-format.html"><i class="fa fa-check"></i><b>4</b> Data format and reading FROC data</a><ul>
<li class="chapter" data-level="4.1" data-path="quick-start-froc-data-format.html"><a href="quick-start-froc-data-format.html#quick-start-froc-data-format-how-much-finished"><i class="fa fa-check"></i><b>4.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="4.2" data-path="quick-start-froc-data-format.html"><a href="quick-start-froc-data-format.html#quick-start-froc-data-intro"><i class="fa fa-check"></i><b>4.2</b> Introduction</a></li>
<li class="chapter" data-level="4.3" data-path="quick-start-froc-data-format.html"><a href="quick-start-froc-data-format.html#quick-start-froc-data-truth"><i class="fa fa-check"></i><b>4.3</b> The <code>Truth</code> worksheet</a></li>
<li class="chapter" data-level="4.4" data-path="quick-start-froc-data-format.html"><a href="quick-start-froc-data-format.html#quick-start-froc-data-structure"><i class="fa fa-check"></i><b>4.4</b> Reading the FROC dataset</a></li>
<li class="chapter" data-level="4.5" data-path="quick-start-froc-data-format.html"><a href="quick-start-froc-data-format.html#quick-start-froc-data-fp"><i class="fa fa-check"></i><b>4.5</b> The false positive (FP) ratings</a></li>
<li class="chapter" data-level="4.6" data-path="quick-start-froc-data-format.html"><a href="quick-start-froc-data-format.html#quick-start-froc-data-tp"><i class="fa fa-check"></i><b>4.6</b> The true positive (TP) ratings</a></li>
<li class="chapter" data-level="4.7" data-path="quick-start-froc-data-format.html"><a href="quick-start-froc-data-format.html#quick-start-froc-data-distribution-diseased-cases"><i class="fa fa-check"></i><b>4.7</b> On the distribution of numbers of lesions in diseased cases</a><ul>
<li class="chapter" data-level="4.7.1" data-path="quick-start-froc-data-format.html"><a href="quick-start-froc-data-format.html#quick-start-froc-data-lesion-distribution"><i class="fa fa-check"></i><b>4.7.1</b> Definition of <code>lesDistr</code> array</a></li>
</ul></li>
<li class="chapter" data-level="4.8" data-path="quick-start-froc-data-format.html"><a href="quick-start-froc-data-format.html#quick-start-froc-data-lesion-weights"><i class="fa fa-check"></i><b>4.8</b> Definition of <code>lesWghtDistr</code> array</a></li>
<li class="chapter" data-level="4.9" data-path="quick-start-froc-data-format.html"><a href="quick-start-froc-data-format.html#quick-start-froc-data-format-references"><i class="fa fa-check"></i><b>4.9</b> References</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="quick-start-dbm-text.html"><a href="quick-start-dbm-text.html"><i class="fa fa-check"></i><b>5</b> DBM analysis text output</a><ul>
<li class="chapter" data-level="5.1" data-path="quick-start-dbm-text.html"><a href="quick-start-dbm-text.html#quick-start-dbm-text-how-much-finished"><i class="fa fa-check"></i><b>5.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="5.2" data-path="quick-start-dbm-text.html"><a href="quick-start-dbm-text.html#quick-start-dbm-text-intro"><i class="fa fa-check"></i><b>5.2</b> Introduction</a></li>
<li class="chapter" data-level="5.3" data-path="quick-start-dbm-text.html"><a href="quick-start-dbm-text.html#quick-start-dbm-text-analyze-dataset"><i class="fa fa-check"></i><b>5.3</b> Analyzing the ROC dataset</a></li>
<li class="chapter" data-level="5.4" data-path="quick-start-dbm-text.html"><a href="quick-start-dbm-text.html#quick-start-dbm-text-explanation"><i class="fa fa-check"></i><b>5.4</b> Explanation of the output</a></li>
<li class="chapter" data-level="5.5" data-path="quick-start-dbm-text.html"><a href="quick-start-dbm-text.html#quick-start-dbm-text-references"><i class="fa fa-check"></i><b>5.5</b> References</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="quick-start-or-text.html"><a href="quick-start-or-text.html"><i class="fa fa-check"></i><b>6</b> OR analysis text output</a><ul>
<li class="chapter" data-level="6.1" data-path="quick-start-or-text.html"><a href="quick-start-or-text.html#quick-start-or-text-how-much-finished"><i class="fa fa-check"></i><b>6.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="6.2" data-path="quick-start-or-text.html"><a href="quick-start-or-text.html#quick-start-or-text-intro"><i class="fa fa-check"></i><b>6.2</b> Introduction</a></li>
<li class="chapter" data-level="6.3" data-path="quick-start-or-text.html"><a href="quick-start-or-text.html#quick-start-or-text-analyze-dataset"><i class="fa fa-check"></i><b>6.3</b> Analyzing the ROC dataset</a></li>
<li class="chapter" data-level="6.4" data-path="quick-start-or-text.html"><a href="quick-start-or-text.html#quick-start-or-text-explanation"><i class="fa fa-check"></i><b>6.4</b> Explanation of the output</a></li>
<li class="chapter" data-level="6.5" data-path="quick-start-or-text.html"><a href="quick-start-or-text.html#quick-start-or-text-references"><i class="fa fa-check"></i><b>6.5</b> References</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="quick-start-or-excel.html"><a href="quick-start-or-excel.html"><i class="fa fa-check"></i><b>7</b> OR analysis Excel output</a><ul>
<li class="chapter" data-level="7.1" data-path="quick-start-or-excel.html"><a href="quick-start-or-excel.html#quick-start-or-excel-how-much-finished"><i class="fa fa-check"></i><b>7.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="7.2" data-path="quick-start-or-excel.html"><a href="quick-start-or-excel.html#quick-start-or-excel-intro"><i class="fa fa-check"></i><b>7.2</b> Introduction</a></li>
<li class="chapter" data-level="7.3" data-path="quick-start-or-excel.html"><a href="quick-start-or-excel.html#quick-start-or-excel-output"><i class="fa fa-check"></i><b>7.3</b> Generating the Excel output file</a></li>
<li class="chapter" data-level="7.4" data-path="quick-start-or-excel.html"><a href="quick-start-or-excel.html#quick-start-or-excel-references"><i class="fa fa-check"></i><b>7.4</b> References</a></li>
</ul></li>
<li class="part"><span><b>ROC paradigm</b></span></li>
<li class="chapter" data-level="8" data-path="preliminaries.html"><a href="preliminaries.html"><i class="fa fa-check"></i><b>8</b> Preliminaries</a><ul>
<li class="chapter" data-level="8.1" data-path="preliminaries.html"><a href="preliminaries.html#preliminaries-how-much-finished"><i class="fa fa-check"></i><b>8.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="8.2" data-path="preliminaries.html"><a href="preliminaries.html#preliminariesIntro"><i class="fa fa-check"></i><b>8.2</b> Introduction</a></li>
<li class="chapter" data-level="8.3" data-path="preliminaries.html"><a href="preliminaries.html#clinical-tasks"><i class="fa fa-check"></i><b>8.3</b> Clinical tasks</a><ul>
<li class="chapter" data-level="8.3.1" data-path="preliminaries.html"><a href="preliminaries.html#workflow-in-an-imaging-study"><i class="fa fa-check"></i><b>8.3.1</b> Workflow in an imaging study</a></li>
<li class="chapter" data-level="8.3.2" data-path="preliminaries.html"><a href="preliminaries.html#the-screening-and-diagnostic-workup-tasks"><i class="fa fa-check"></i><b>8.3.2</b> The screening and diagnostic workup tasks</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="preliminaries.html"><a href="preliminaries.html#imaging-device-development-and-its-clinical-deployment"><i class="fa fa-check"></i><b>8.4</b> Imaging device development and its clinical deployment</a><ul>
<li class="chapter" data-level="8.4.1" data-path="preliminaries.html"><a href="preliminaries.html#physical-measurements"><i class="fa fa-check"></i><b>8.4.1</b> Physical measurements</a></li>
<li class="chapter" data-level="8.4.2" data-path="preliminaries.html"><a href="preliminaries.html#quality-control-and-image-quality-optimization"><i class="fa fa-check"></i><b>8.4.2</b> Quality Control and Image quality optimization</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="preliminaries.html"><a href="preliminaries.html#image-quality-vs.-task-performance"><i class="fa fa-check"></i><b>8.5</b> Image quality vs. task performance</a></li>
<li class="chapter" data-level="8.6" data-path="preliminaries.html"><a href="preliminaries.html#why-physical-measures-of-image-quality-are-not-enough"><i class="fa fa-check"></i><b>8.6</b> Why physical measures of image quality are not enough</a></li>
<li class="chapter" data-level="8.7" data-path="preliminaries.html"><a href="preliminaries.html#model-observers"><i class="fa fa-check"></i><b>8.7</b> Model observers</a></li>
<li class="chapter" data-level="8.8" data-path="preliminaries.html"><a href="preliminaries.html#measuring-observer-performance-four-paradigms"><i class="fa fa-check"></i><b>8.8</b> Measuring observer performance: four paradigms</a><ul>
<li class="chapter" data-level="8.8.1" data-path="preliminaries.html"><a href="preliminaries.html#basic-approach-to-the-analysis"><i class="fa fa-check"></i><b>8.8.1</b> Basic approach to the analysis</a></li>
<li class="chapter" data-level="8.8.2" data-path="preliminaries.html"><a href="preliminaries.html#historical-notes"><i class="fa fa-check"></i><b>8.8.2</b> Historical notes</a></li>
</ul></li>
<li class="chapter" data-level="8.9" data-path="preliminaries.html"><a href="preliminaries.html#hierarchy-of-assessment-methods"><i class="fa fa-check"></i><b>8.9</b> Hierarchy of assessment methods</a></li>
<li class="chapter" data-level="8.10" data-path="preliminaries.html"><a href="preliminaries.html#overview-of-the-book-and-how-to-use-it"><i class="fa fa-check"></i><b>8.10</b> Overview of the book and how to use it</a><ul>
<li class="chapter" data-level="8.10.1" data-path="preliminaries.html"><a href="preliminaries.html#overview-of-the-book"><i class="fa fa-check"></i><b>8.10.1</b> Overview of the book</a></li>
<li class="chapter" data-level="8.10.2" data-path="preliminaries.html"><a href="preliminaries.html#how-to-use-the-book"><i class="fa fa-check"></i><b>8.10.2</b> How to use the book</a></li>
</ul></li>
<li class="chapter" data-level="8.11" data-path="preliminaries.html"><a href="preliminaries.html#preliminaries-Summary"><i class="fa fa-check"></i><b>8.11</b> Summary</a></li>
<li class="chapter" data-level="8.12" data-path="preliminaries.html"><a href="preliminaries.html#preliminaries-Discussion"><i class="fa fa-check"></i><b>8.12</b> Discussion</a></li>
<li class="chapter" data-level="8.13" data-path="preliminaries.html"><a href="preliminaries.html#preliminaries-references"><i class="fa fa-check"></i><b>8.13</b> References</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="binary-task.html"><a href="binary-task.html"><i class="fa fa-check"></i><b>9</b> The Binary Task</a><ul>
<li class="chapter" data-level="9.1" data-path="binary-task.html"><a href="binary-task.html#binary-task-how-much-finished"><i class="fa fa-check"></i><b>9.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="9.2" data-path="binary-task.html"><a href="binary-task.html#binary-taskIntro"><i class="fa fa-check"></i><b>9.2</b> Introduction</a></li>
<li class="chapter" data-level="9.3" data-path="binary-task.html"><a href="binary-task.html#binary-taskTruth"><i class="fa fa-check"></i><b>9.3</b> The fundamental 2x2 table</a></li>
<li class="chapter" data-level="9.4" data-path="binary-task.html"><a href="binary-task.html#sensitivity-and-specificity"><i class="fa fa-check"></i><b>9.4</b> Sensitivity and specificity</a><ul>
<li class="chapter" data-level="9.4.1" data-path="binary-task.html"><a href="binary-task.html#reasons-for-the-names-sensitivity-and-specificity"><i class="fa fa-check"></i><b>9.4.1</b> Reasons for the names sensitivity and specificity</a></li>
<li class="chapter" data-level="9.4.2" data-path="binary-task.html"><a href="binary-task.html#estimating-sensitivity-and-specificity"><i class="fa fa-check"></i><b>9.4.2</b> Estimating sensitivity and specificity</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="binary-task.html"><a href="binary-task.html#disease-prevalence"><i class="fa fa-check"></i><b>9.5</b> Disease prevalence</a></li>
<li class="chapter" data-level="9.6" data-path="binary-task.html"><a href="binary-task.html#accuracy"><i class="fa fa-check"></i><b>9.6</b> Accuracy</a></li>
<li class="chapter" data-level="9.7" data-path="binary-task.html"><a href="binary-task.html#negative-and-positive-predictive-values"><i class="fa fa-check"></i><b>9.7</b> Negative and positive predictive values</a><ul>
<li class="chapter" data-level="9.7.1" data-path="binary-task.html"><a href="binary-task.html#binary-taskNpvPpvCode"><i class="fa fa-check"></i><b>9.7.1</b> Example calculation of PPV, NPV and accuracy</a></li>
<li class="chapter" data-level="9.7.2" data-path="binary-task.html"><a href="binary-task.html#binary-taskNpvPpvComments"><i class="fa fa-check"></i><b>9.7.2</b> Comments</a></li>
<li class="chapter" data-level="9.7.3" data-path="binary-task.html"><a href="binary-task.html#binary-taskNpvPpvIrrel2LabTasks"><i class="fa fa-check"></i><b>9.7.3</b> PPV and NPV are irrelevant to laboratory tasks</a></li>
</ul></li>
<li class="chapter" data-level="9.8" data-path="binary-task.html"><a href="binary-task.html#binary-task-Summary"><i class="fa fa-check"></i><b>9.8</b> Summary</a></li>
<li class="chapter" data-level="9.9" data-path="binary-task.html"><a href="binary-task.html#binary-task-Discussion"><i class="fa fa-check"></i><b>9.9</b> Discussion</a></li>
<li class="chapter" data-level="9.10" data-path="binary-task.html"><a href="binary-task.html#binary-task-references"><i class="fa fa-check"></i><b>9.10</b> References</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="binary-task-model.html"><a href="binary-task-model.html"><i class="fa fa-check"></i><b>10</b> Modeling the Binary Task</a><ul>
<li class="chapter" data-level="10.1" data-path="binary-task-model.html"><a href="binary-task-model.html#binary-task-model-how-much-finished"><i class="fa fa-check"></i><b>10.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="10.2" data-path="binary-task-model.html"><a href="binary-task-model.html#binary-task-model-intro"><i class="fa fa-check"></i><b>10.2</b> Introduction</a></li>
<li class="chapter" data-level="10.3" data-path="binary-task-model.html"><a href="binary-task-model.html#binary-task-model-z-sample-model"><i class="fa fa-check"></i><b>10.3</b> Decision variable and decision threshold</a><ul>
<li class="chapter" data-level="10.3.1" data-path="binary-task-model.html"><a href="binary-task-model.html#existence-of-a-decision-variable"><i class="fa fa-check"></i><b>10.3.1</b> Existence of a decision variable</a></li>
<li class="chapter" data-level="10.3.2" data-path="binary-task-model.html"><a href="binary-task-model.html#existence-of-a-decision-threshold"><i class="fa fa-check"></i><b>10.3.2</b> Existence of a decision threshold</a></li>
<li class="chapter" data-level="10.3.3" data-path="binary-task-model.html"><a href="binary-task-model.html#adequacy-of-the-training-session"><i class="fa fa-check"></i><b>10.3.3</b> Adequacy of the training session</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="binary-task-model.html"><a href="binary-task-model.html#binary-task-model-example-1"><i class="fa fa-check"></i><b>10.4</b> Changing the decision threshold: Example I</a></li>
<li class="chapter" data-level="10.5" data-path="binary-task-model.html"><a href="binary-task-model.html#binary-task-model-example-2"><i class="fa fa-check"></i><b>10.5</b> Changing the decision threshold: Example II</a></li>
<li class="chapter" data-level="10.6" data-path="binary-task-model.html"><a href="binary-task-model.html#binary-task-model-equal-variance-binormal-model"><i class="fa fa-check"></i><b>10.6</b> The equal-variance binormal model</a></li>
<li class="chapter" data-level="10.7" data-path="binary-task-model.html"><a href="binary-task-model.html#binary-task-model-normal-distribution"><i class="fa fa-check"></i><b>10.7</b> The normal distribution</a></li>
<li class="chapter" data-level="10.8" data-path="binary-task-model.html"><a href="binary-task-model.html#binary-task-model-sensitivity-specificity"><i class="fa fa-check"></i><b>10.8</b> Analytic expressions for specificity and sensitivity</a></li>
<li class="chapter" data-level="10.9" data-path="binary-task-model.html"><a href="binary-task-model.html#binary-task-model-sensitivity-specificity-demo"><i class="fa fa-check"></i><b>10.9</b> Demonstration of the concepts of sensitivity and specificity</a><ul>
<li class="chapter" data-level="10.9.1" data-path="binary-task-model.html"><a href="binary-task-model.html#estimating-mu-from-a-finite-sample"><i class="fa fa-check"></i><b>10.9.1</b> Estimating mu from a finite sample</a></li>
<li class="chapter" data-level="10.9.2" data-path="binary-task-model.html"><a href="binary-task-model.html#changing-the-seed-variable-case-sampling-variability"><i class="fa fa-check"></i><b>10.9.2</b> Changing the seed variable: case-sampling variability</a></li>
<li class="chapter" data-level="10.9.3" data-path="binary-task-model.html"><a href="binary-task-model.html#increasing-the-numbers-of-cases"><i class="fa fa-check"></i><b>10.9.3</b> Increasing the numbers of cases</a></li>
</ul></li>
<li class="chapter" data-level="10.10" data-path="binary-task-model.html"><a href="binary-task-model.html#binary-task-model-sensitivity-specificity-inverse-variation"><i class="fa fa-check"></i><b>10.10</b> Inverse variation of sensitivity and specificity and the need for a single FOM</a></li>
<li class="chapter" data-level="10.11" data-path="binary-task-model.html"><a href="binary-task-model.html#binary-task-model-roc-curve"><i class="fa fa-check"></i><b>10.11</b> The ROC curve</a><ul>
<li class="chapter" data-level="10.11.1" data-path="binary-task-model.html"><a href="binary-task-model.html#binary-task-model-chance-diagonal"><i class="fa fa-check"></i><b>10.11.1</b> The chance diagonal</a></li>
<li class="chapter" data-level="10.11.2" data-path="binary-task-model.html"><a href="binary-task-model.html#binary-task-model-guessing-observer"><i class="fa fa-check"></i><b>10.11.2</b> The guessing observer</a></li>
<li class="chapter" data-level="10.11.3" data-path="binary-task-model.html"><a href="binary-task-model.html#binary-task-model-symmetry-wrt-negative-diagonal"><i class="fa fa-check"></i><b>10.11.3</b> Symmetry with respect to negative diagonal</a></li>
<li class="chapter" data-level="10.11.4" data-path="binary-task-model.html"><a href="binary-task-model.html#binary-task-model-auc-roc-important"><i class="fa fa-check"></i><b>10.11.4</b> Area under the ROC curve</a></li>
<li class="chapter" data-level="10.11.5" data-path="binary-task-model.html"><a href="binary-task-model.html#binary-task-model-properties-roc"><i class="fa fa-check"></i><b>10.11.5</b> Properties of the equal-variance binormal model ROC curve</a></li>
<li class="chapter" data-level="10.11.6" data-path="binary-task-model.html"><a href="binary-task-model.html#binary-task-model-comments"><i class="fa fa-check"></i><b>10.11.6</b> Comments</a></li>
<li class="chapter" data-level="10.11.7" data-path="binary-task-model.html"><a href="binary-task-model.html#binary-task-model-mu-parameter-intepretation"><i class="fa fa-check"></i><b>10.11.7</b> Physical interpretation of the mu-parameter</a></li>
</ul></li>
<li class="chapter" data-level="10.12" data-path="binary-task-model.html"><a href="binary-task-model.html#binary-task-model-confidence-intervals"><i class="fa fa-check"></i><b>10.12</b> Assigning confidence intervals to an operating point</a></li>
<li class="chapter" data-level="10.13" data-path="binary-task-model.html"><a href="binary-task-model.html#binary-task-model-beam-study"><i class="fa fa-check"></i><b>10.13</b> Variability in sensitivity and specificity: the Beam et al study</a></li>
<li class="chapter" data-level="10.14" data-path="binary-task-model.html"><a href="binary-task-model.html#binary-task-model-summary"><i class="fa fa-check"></i><b>10.14</b> Summary</a></li>
<li class="chapter" data-level="10.15" data-path="binary-task-model.html"><a href="binary-task-model.html#binary-task-model-references"><i class="fa fa-check"></i><b>10.15</b> References</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="ratings-paradigm.html"><a href="ratings-paradigm.html"><i class="fa fa-check"></i><b>11</b> Ratings Paradigm</a><ul>
<li class="chapter" data-level="11.1" data-path="ratings-paradigm.html"><a href="ratings-paradigm.html#ratings-paradigm-how-much-finished"><i class="fa fa-check"></i><b>11.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="11.2" data-path="ratings-paradigm.html"><a href="ratings-paradigm.html#ratings-paradigm-introduction"><i class="fa fa-check"></i><b>11.2</b> Introduction</a></li>
<li class="chapter" data-level="11.3" data-path="ratings-paradigm.html"><a href="ratings-paradigm.html#binary-task-roc-counts-table"><i class="fa fa-check"></i><b>11.3</b> The ROC counts table</a></li>
<li class="chapter" data-level="11.4" data-path="ratings-paradigm.html"><a href="ratings-paradigm.html#binary-task-operating-points-from-counts-table"><i class="fa fa-check"></i><b>11.4</b> Operating points from counts table</a><ul>
<li class="chapter" data-level="11.4.1" data-path="ratings-paradigm.html"><a href="ratings-paradigm.html#labeling-the-points"><i class="fa fa-check"></i><b>11.4.1</b> Labeling the points</a></li>
<li class="chapter" data-level="11.4.2" data-path="ratings-paradigm.html"><a href="ratings-paradigm.html#binary-task-examples"><i class="fa fa-check"></i><b>11.4.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="11.5" data-path="ratings-paradigm.html"><a href="ratings-paradigm.html#binary-task-automating"><i class="fa fa-check"></i><b>11.5</b> Automating all this</a></li>
<li class="chapter" data-level="11.6" data-path="ratings-paradigm.html"><a href="ratings-paradigm.html#binary-task-relation-to-rating"><i class="fa fa-check"></i><b>11.6</b> Relation between ratings paradigm and the binary paradigm</a></li>
<li class="chapter" data-level="11.7" data-path="ratings-paradigm.html"><a href="ratings-paradigm.html#binary-task-ratings-not-numerical-values"><i class="fa fa-check"></i><b>11.7</b> Ratings are not numerical values</a></li>
<li class="chapter" data-level="11.8" data-path="ratings-paradigm.html"><a href="ratings-paradigm.html#binary-task-clinical-operating-point"><i class="fa fa-check"></i><b>11.8</b> A single “clinical” operating point from ratings data</a></li>
<li class="chapter" data-level="11.9" data-path="ratings-paradigm.html"><a href="ratings-paradigm.html#binary-task-2afc"><i class="fa fa-check"></i><b>11.9</b> The forced choice paradigm</a></li>
<li class="chapter" data-level="11.10" data-path="ratings-paradigm.html"><a href="ratings-paradigm.html#binary-task-observer-studies-as-simulations"><i class="fa fa-check"></i><b>11.10</b> Observer performance studies as laboratory simulations of clinical tasks</a></li>
<li class="chapter" data-level="11.11" data-path="ratings-paradigm.html"><a href="ratings-paradigm.html#binary-task-discrete-vs-continuous-ratings"><i class="fa fa-check"></i><b>11.11</b> Discrete vs. continuous ratings: the Miller study</a></li>
<li class="chapter" data-level="11.12" data-path="ratings-paradigm.html"><a href="ratings-paradigm.html#binary-task-birads-rating-scale"><i class="fa fa-check"></i><b>11.12</b> The BI-RADS ratings scale and ROC studies</a></li>
<li class="chapter" data-level="11.13" data-path="ratings-paradigm.html"><a href="ratings-paradigm.html#binary-task-birads-rating-scale-controversy"><i class="fa fa-check"></i><b>11.13</b> The controversy</a></li>
<li class="chapter" data-level="11.14" data-path="ratings-paradigm.html"><a href="ratings-paradigm.html#ratings-paradigm-discussion"><i class="fa fa-check"></i><b>11.14</b> Discussion</a></li>
<li class="chapter" data-level="11.15" data-path="ratings-paradigm.html"><a href="ratings-paradigm.html#ratings-paradigm-references"><i class="fa fa-check"></i><b>11.15</b> References</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="empirical-auc.html"><a href="empirical-auc.html"><i class="fa fa-check"></i><b>12</b> Empirical AUC</a><ul>
<li class="chapter" data-level="12.1" data-path="empirical-auc.html"><a href="empirical-auc.html#empirical-auc-how-much-finished"><i class="fa fa-check"></i><b>12.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="12.2" data-path="empirical-auc.html"><a href="empirical-auc.html#empirical-auc-introduction"><i class="fa fa-check"></i><b>12.2</b> Introduction</a></li>
<li class="chapter" data-level="12.3" data-path="empirical-auc.html"><a href="empirical-auc.html#empirical-roc-plot"><i class="fa fa-check"></i><b>12.3</b> The empirical ROC plot</a><ul>
<li class="chapter" data-level="12.3.1" data-path="empirical-auc.html"><a href="empirical-auc.html#notation-for-cases"><i class="fa fa-check"></i><b>12.3.1</b> Notation for cases</a></li>
<li class="chapter" data-level="12.3.2" data-path="empirical-auc.html"><a href="empirical-auc.html#an-empirical-operating-point"><i class="fa fa-check"></i><b>12.3.2</b> An empirical operating point</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="empirical-auc.html"><a href="empirical-auc.html#empirical-auc-operating-points"><i class="fa fa-check"></i><b>12.4</b> Empirical operating points from ratings data</a></li>
<li class="chapter" data-level="12.5" data-path="empirical-auc.html"><a href="empirical-auc.html#empirical-auc-area-under"><i class="fa fa-check"></i><b>12.5</b> AUC under the empirical ROC plot</a></li>
<li class="chapter" data-level="12.6" data-path="empirical-auc.html"><a href="empirical-auc.html#empirical-auc-wilcoxon"><i class="fa fa-check"></i><b>12.6</b> The Wilcoxon statistic</a></li>
<li class="chapter" data-level="12.7" data-path="empirical-auc.html"><a href="empirical-auc.html#empirical-auc-wilcoxon-bamber-theorem"><i class="fa fa-check"></i><b>12.7</b> Bamber’s Equivalence theorem</a></li>
<li class="chapter" data-level="12.8" data-path="empirical-auc.html"><a href="empirical-auc.html#empirical-auc-wilcoxon-bamber-theorem-importance"><i class="fa fa-check"></i><b>12.8</b> Importance of Bamber’s theorem</a></li>
<li class="chapter" data-level="12.9" data-path="empirical-auc.html"><a href="empirical-auc.html#empirical-auc-discussion-summary"><i class="fa fa-check"></i><b>12.9</b> Discussion / Summary</a></li>
<li class="chapter" data-level="12.10" data-path="empirical-auc.html"><a href="empirical-auc.html#empirical-auc-appendix-details-bamber-theorem"><i class="fa fa-check"></i><b>12.10</b> Appendix 5.A: Details of Wilcoxon theorem</a><ul>
<li class="chapter" data-level="12.10.1" data-path="empirical-auc.html"><a href="empirical-auc.html#upper-triangle"><i class="fa fa-check"></i><b>12.10.1</b> Upper triangle</a></li>
<li class="chapter" data-level="12.10.2" data-path="empirical-auc.html"><a href="empirical-auc.html#lowest-trapezoid"><i class="fa fa-check"></i><b>12.10.2</b> Lowest trapezoid</a></li>
</ul></li>
<li class="chapter" data-level="12.11" data-path="empirical-auc.html"><a href="empirical-auc.html#empirical-auc-references"><i class="fa fa-check"></i><b>12.11</b> References</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="binormal-model.html"><a href="binormal-model.html"><i class="fa fa-check"></i><b>13</b> Binormal model</a><ul>
<li class="chapter" data-level="13.1" data-path="binormal-model.html"><a href="binormal-model.html#binormal-model-how-much-finished"><i class="fa fa-check"></i><b>13.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="13.2" data-path="binormal-model.html"><a href="binormal-model.html#binormal-model-introduction"><i class="fa fa-check"></i><b>13.2</b> TBA Introduction</a></li>
<li class="chapter" data-level="13.3" data-path="binormal-model.html"><a href="binormal-model.html#binormal-model-definition"><i class="fa fa-check"></i><b>13.3</b> Binormal model</a><ul>
<li class="chapter" data-level="13.3.1" data-path="binormal-model.html"><a href="binormal-model.html#the-basic-model"><i class="fa fa-check"></i><b>13.3.1</b> The basic model</a></li>
<li class="chapter" data-level="13.3.2" data-path="binormal-model.html"><a href="binormal-model.html#additional-parameters-for-binned-data"><i class="fa fa-check"></i><b>13.3.2</b> Additional parameters for binned data</a></li>
<li class="chapter" data-level="13.3.3" data-path="binormal-model.html"><a href="binormal-model.html#sensitivity-and-specificity-1"><i class="fa fa-check"></i><b>13.3.3</b> Sensitivity and specificity</a></li>
<li class="chapter" data-level="13.3.4" data-path="binormal-model.html"><a href="binormal-model.html#binormal-model-in-conventional-notation"><i class="fa fa-check"></i><b>13.3.4</b> Binormal model in conventional notation</a></li>
</ul></li>
<li class="chapter" data-level="13.4" data-path="binormal-model.html"><a href="binormal-model.html#binormal-model-roc-curve"><i class="fa fa-check"></i><b>13.4</b> Binormal ROC curve</a></li>
<li class="chapter" data-level="13.5" data-path="binormal-model.html"><a href="binormal-model.html#binormal-model-scalar-measure"><i class="fa fa-check"></i><b>13.5</b> Scalar threshold-independent measure</a><ul>
<li class="chapter" data-level="13.5.1" data-path="binormal-model.html"><a href="binormal-model.html#binormal-model-partial-auc"><i class="fa fa-check"></i><b>13.5.1</b> Partial AUC</a></li>
<li class="chapter" data-level="13.5.2" data-path="binormal-model.html"><a href="binormal-model.html#binormal-model-full-auc"><i class="fa fa-check"></i><b>13.5.2</b> Full AUC</a></li>
<li class="chapter" data-level="13.5.3" data-path="binormal-model.html"><a href="binormal-model.html#binormal-model-d-prime"><i class="fa fa-check"></i><b>13.5.3</b> The d’ measure</a></li>
</ul></li>
<li class="chapter" data-level="13.6" data-path="binormal-model.html"><a href="binormal-model.html#binormal-model-partial-true"><i class="fa fa-check"></i><b>13.6</b> Partial AUC vs. true performance</a></li>
<li class="chapter" data-level="13.7" data-path="binormal-model.html"><a href="binormal-model.html#binormal-model-illustrative-plots"><i class="fa fa-check"></i><b>13.7</b> Illustrative plots</a></li>
<li class="chapter" data-level="13.8" data-path="binormal-model.html"><a href="binormal-model.html#binormal-model-geometrical-argument"><i class="fa fa-check"></i><b>13.8</b> Geometrical argument</a></li>
<li class="chapter" data-level="13.9" data-path="binormal-model.html"><a href="binormal-model.html#binormal-model-optimal-op-pt"><i class="fa fa-check"></i><b>13.9</b> Optimal operating point on ROC</a></li>
<li class="chapter" data-level="13.10" data-path="binormal-model.html"><a href="binormal-model.html#binormal-model-discussion"><i class="fa fa-check"></i><b>13.10</b> Discussion</a></li>
<li class="chapter" data-level="13.11" data-path="binormal-model.html"><a href="binormal-model.html#binormal-model-pdf-curves-appendix-1"><i class="fa fa-check"></i><b>13.11</b> Appendix I: Density functions</a></li>
<li class="chapter" data-level="13.12" data-path="binormal-model.html"><a href="binormal-model.html#binormal-model-appendix-2"><i class="fa fa-check"></i><b>13.12</b> Appendix II: Area under binormal ROC</a><ul>
<li class="chapter" data-level="13.12.1" data-path="binormal-model.html"><a href="binormal-model.html#binormal-model-appendix-1-partial-auc"><i class="fa fa-check"></i><b>13.12.1</b> General case (partial-area)</a></li>
<li class="chapter" data-level="13.12.2" data-path="binormal-model.html"><a href="binormal-model.html#binormal-model-appendix-1-total-auc"><i class="fa fa-check"></i><b>13.12.2</b> Special case (total area)</a></li>
</ul></li>
<li class="chapter" data-level="13.13" data-path="binormal-model.html"><a href="binormal-model.html#binormal-model-invariance-property-appendix-3"><i class="fa fa-check"></i><b>13.13</b> Appendix III: Invariance property of pdfs</a></li>
<li class="chapter" data-level="13.14" data-path="binormal-model.html"><a href="binormal-model.html#binormal-model-curve-fitting-appendix-4"><i class="fa fa-check"></i><b>13.14</b> Appendix IV: Fitting an ROC curve</a><ul>
<li class="chapter" data-level="13.14.1" data-path="binormal-model.html"><a href="binormal-model.html#java-fitted-roc-curve"><i class="fa fa-check"></i><b>13.14.1</b> JAVA fitted ROC curve</a></li>
<li class="chapter" data-level="13.14.2" data-path="binormal-model.html"><a href="binormal-model.html#simplistic-straight-line-fit-to-the-roc-curve"><i class="fa fa-check"></i><b>13.14.2</b> Simplistic straight line fit to the ROC curve</a></li>
<li class="chapter" data-level="13.14.3" data-path="binormal-model.html"><a href="binormal-model.html#maximum-likelihood-estimation-mle"><i class="fa fa-check"></i><b>13.14.3</b> Maximum likelihood estimation (MLE)</a></li>
<li class="chapter" data-level="13.14.4" data-path="binormal-model.html"><a href="binormal-model.html#code-implementing-mle"><i class="fa fa-check"></i><b>13.14.4</b> Code implementing MLE</a></li>
</ul></li>
<li class="chapter" data-level="13.15" data-path="binormal-model.html"><a href="binormal-model.html#binormal-model-curve-fitting-validation-appendix-5"><i class="fa fa-check"></i><b>13.15</b> Appendix V: Validating fitting model</a><ul>
<li class="chapter" data-level="13.15.1" data-path="binormal-model.html"><a href="binormal-model.html#estimating-the-covariance-matrix"><i class="fa fa-check"></i><b>13.15.1</b> Estimating the covariance matrix</a></li>
<li class="chapter" data-level="13.15.2" data-path="binormal-model.html"><a href="binormal-model.html#estimating-the-variance-of-az"><i class="fa fa-check"></i><b>13.15.2</b> Estimating the variance of Az</a></li>
</ul></li>
<li class="chapter" data-level="13.16" data-path="binormal-model.html"><a href="binormal-model.html#binormal-model-references"><i class="fa fa-check"></i><b>13.16</b> References</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="sources-of-variability.html"><a href="sources-of-variability.html"><i class="fa fa-check"></i><b>14</b> Sources of AUC variability</a><ul>
<li class="chapter" data-level="14.1" data-path="sources-of-variability.html"><a href="sources-of-variability.html#sources-of-variability-how-much-finished"><i class="fa fa-check"></i><b>14.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="14.2" data-path="sources-of-variability.html"><a href="sources-of-variability.html#sources-of-variabilityIntro"><i class="fa fa-check"></i><b>14.2</b> Introduction</a></li>
<li class="chapter" data-level="14.3" data-path="sources-of-variability.html"><a href="sources-of-variability.html#sources-of-variability3sources"><i class="fa fa-check"></i><b>14.3</b> Three sources of variability</a></li>
<li class="chapter" data-level="14.4" data-path="sources-of-variability.html"><a href="sources-of-variability.html#dependence-of-auc-on-the-case-sample"><i class="fa fa-check"></i><b>14.4</b> Dependence of AUC on the case sample</a><ul>
<li class="chapter" data-level="14.4.1" data-path="sources-of-variability.html"><a href="sources-of-variability.html#case-sampling-variability-of-auc"><i class="fa fa-check"></i><b>14.4.1</b> Case sampling variability of AUC</a></li>
</ul></li>
<li class="chapter" data-level="14.5" data-path="sources-of-variability.html"><a href="sources-of-variability.html#sources-of-variabilityDeLong"><i class="fa fa-check"></i><b>14.5</b> DeLong method</a></li>
<li class="chapter" data-level="14.6" data-path="sources-of-variability.html"><a href="sources-of-variability.html#sources-of-variabilityBootstrap"><i class="fa fa-check"></i><b>14.6</b> Bootstrap method</a><ul>
<li class="chapter" data-level="14.6.1" data-path="sources-of-variability.html"><a href="sources-of-variability.html#demonstration-of-the-bootstrap-method"><i class="fa fa-check"></i><b>14.6.1</b> Demonstration of the bootstrap method</a></li>
</ul></li>
<li class="chapter" data-level="14.7" data-path="sources-of-variability.html"><a href="sources-of-variability.html#sources-of-variabilityJackknife"><i class="fa fa-check"></i><b>14.7</b> Jackknife method</a></li>
<li class="chapter" data-level="14.8" data-path="sources-of-variability.html"><a href="sources-of-variability.html#sources-of-variabilityCalSimulator"><i class="fa fa-check"></i><b>14.8</b> Calibrated simulator</a><ul>
<li class="chapter" data-level="14.8.1" data-path="sources-of-variability.html"><a href="sources-of-variability.html#the-need-for-a-calibrated-simulator"><i class="fa fa-check"></i><b>14.8.1</b> The need for a calibrated simulator</a></li>
<li class="chapter" data-level="14.8.2" data-path="sources-of-variability.html"><a href="sources-of-variability.html#implementation-of-a-simple-calibrated-simulator"><i class="fa fa-check"></i><b>14.8.2</b> Implementation of a simple calibrated simulator</a></li>
</ul></li>
<li class="chapter" data-level="14.9" data-path="sources-of-variability.html"><a href="sources-of-variability.html#sources-of-variability-Discussion"><i class="fa fa-check"></i><b>14.9</b> Discussion</a></li>
<li class="chapter" data-level="14.10" data-path="sources-of-variability.html"><a href="sources-of-variability.html#sources-of-variability-references"><i class="fa fa-check"></i><b>14.10</b> References</a></li>
</ul></li>
<li class="part"><span><b>Significance Testing</b></span></li>
<li class="chapter" data-level="15" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html"><i class="fa fa-check"></i><b>15</b> Hypothesis Testing</a><ul>
<li class="chapter" data-level="15.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#hypothesis-testing-how-much-finished"><i class="fa fa-check"></i><b>15.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="15.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#hypothesis-testing-introduction"><i class="fa fa-check"></i><b>15.2</b> Introduction</a></li>
<li class="chapter" data-level="15.3" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#single-modality-single-reader-roc-study"><i class="fa fa-check"></i><b>15.3</b> Single-modality single-reader ROC study</a></li>
<li class="chapter" data-level="15.4" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#type-i-errors"><i class="fa fa-check"></i><b>15.4</b> Type-I errors</a></li>
<li class="chapter" data-level="15.5" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#one-vs.-two-sided-tests"><i class="fa fa-check"></i><b>15.5</b> One vs. two sided tests</a></li>
<li class="chapter" data-level="15.6" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#statistical-power"><i class="fa fa-check"></i><b>15.6</b> Statistical power</a><ul>
<li class="chapter" data-level="15.6.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#factors-affecting-statistical-power"><i class="fa fa-check"></i><b>15.6.1</b> Factors affecting statistical power</a></li>
</ul></li>
<li class="chapter" data-level="15.7" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#hypothesis-testingComments"><i class="fa fa-check"></i><b>15.7</b> Comments</a></li>
<li class="chapter" data-level="15.8" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#why-alpha-is-chosen-as-5"><i class="fa fa-check"></i><b>15.8</b> Why alpha is chosen as 5%</a></li>
<li class="chapter" data-level="15.9" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#hypothesis-testingDiscussion"><i class="fa fa-check"></i><b>15.9</b> Discussion</a></li>
<li class="chapter" data-level="15.10" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#hypothesis-testing-references"><i class="fa fa-check"></i><b>15.10</b> References</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="dbm-analysis-background.html"><a href="dbm-analysis-background.html"><i class="fa fa-check"></i><b>16</b> DBM method background</a><ul>
<li class="chapter" data-level="16.1" data-path="dbm-analysis-background.html"><a href="dbm-analysis-background.html#dbm-analysis-background-how-much-finished"><i class="fa fa-check"></i><b>16.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="16.2" data-path="dbm-analysis-background.html"><a href="dbm-analysis-background.html#dbm-analysis-background-introduction"><i class="fa fa-check"></i><b>16.2</b> Introduction</a><ul>
<li class="chapter" data-level="16.2.1" data-path="dbm-analysis-background.html"><a href="dbm-analysis-background.html#historical-background"><i class="fa fa-check"></i><b>16.2.1</b> Historical background</a></li>
<li class="chapter" data-level="16.2.2" data-path="dbm-analysis-background.html"><a href="dbm-analysis-background.html#the-wagner-analogy"><i class="fa fa-check"></i><b>16.2.2</b> The Wagner analogy</a></li>
<li class="chapter" data-level="16.2.3" data-path="dbm-analysis-background.html"><a href="dbm-analysis-background.html#the-shortage-of-numbers-to-analyze-and-a-pivotal-breakthrough"><i class="fa fa-check"></i><b>16.2.3</b> The shortage of numbers to analyze and a pivotal breakthrough</a></li>
<li class="chapter" data-level="16.2.4" data-path="dbm-analysis-background.html"><a href="dbm-analysis-background.html#organization-of-chapter"><i class="fa fa-check"></i><b>16.2.4</b> Organization of chapter</a></li>
</ul></li>
<li class="chapter" data-level="16.3" data-path="dbm-analysis-background.html"><a href="dbm-analysis-background.html#dbm-analysis-background-random-fixed-factors"><i class="fa fa-check"></i><b>16.3</b> Random and fixed factors</a></li>
<li class="chapter" data-level="16.4" data-path="dbm-analysis-background.html"><a href="dbm-analysis-background.html#dbm-analysis-background-reader-case-populations"><i class="fa fa-check"></i><b>16.4</b> Reader and case populations</a></li>
<li class="chapter" data-level="16.5" data-path="dbm-analysis-background.html"><a href="dbm-analysis-background.html#dbm-analysis-background-threeAnalyses"><i class="fa fa-check"></i><b>16.5</b> Three types of analyses</a></li>
<li class="chapter" data-level="16.6" data-path="dbm-analysis-background.html"><a href="dbm-analysis-background.html#dbm-analysis-background-approach"><i class="fa fa-check"></i><b>16.6</b> General approach</a></li>
<li class="chapter" data-level="16.7" data-path="dbm-analysis-background.html"><a href="dbm-analysis-background.html#dbm-analysis-background-summary"><i class="fa fa-check"></i><b>16.7</b> Summary TBA</a></li>
<li class="chapter" data-level="16.8" data-path="dbm-analysis-background.html"><a href="dbm-analysis-background.html#dbm-analysis-background-references"><i class="fa fa-check"></i><b>16.8</b> References</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="dbm-analysis-significance-testing.html"><a href="dbm-analysis-significance-testing.html"><i class="fa fa-check"></i><b>17</b> Significance Testing using the DBM Method</a><ul>
<li class="chapter" data-level="17.1" data-path="dbm-analysis-significance-testing.html"><a href="dbm-analysis-significance-testing.html#dbm-analysis-significance-testing-how-much-finished"><i class="fa fa-check"></i><b>17.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="17.2" data-path="dbm-analysis-significance-testing.html"><a href="dbm-analysis-significance-testing.html#the-dbm-sampling-model"><i class="fa fa-check"></i><b>17.2</b> The DBM sampling model</a><ul>
<li class="chapter" data-level="17.2.1" data-path="dbm-analysis-significance-testing.html"><a href="dbm-analysis-significance-testing.html#explanation-of-terms-in-the-model"><i class="fa fa-check"></i><b>17.2.1</b> Explanation of terms in the model</a></li>
<li class="chapter" data-level="17.2.2" data-path="dbm-analysis-significance-testing.html"><a href="dbm-analysis-significance-testing.html#meanings-of-variance-components-in-the-dbm-model-tba-this-section-can-be-improved"><i class="fa fa-check"></i><b>17.2.2</b> Meanings of variance components in the DBM model (<strong>TBA this section can be improved</strong>)</a></li>
<li class="chapter" data-level="17.2.3" data-path="dbm-analysis-significance-testing.html"><a href="dbm-analysis-significance-testing.html#definitions-of-mean-squares"><i class="fa fa-check"></i><b>17.2.3</b> Definitions of mean-squares</a></li>
</ul></li>
<li class="chapter" data-level="17.3" data-path="dbm-analysis-significance-testing.html"><a href="dbm-analysis-significance-testing.html#expected-values-of-mean-squares"><i class="fa fa-check"></i><b>17.3</b> Expected values of mean squares</a></li>
<li class="chapter" data-level="17.4" data-path="dbm-analysis-significance-testing.html"><a href="dbm-analysis-significance-testing.html#dbm-analysis-significance-testing-RRRC-analysis"><i class="fa fa-check"></i><b>17.4</b> Random-reader random-case (RRRC) analysis</a><ul>
<li class="chapter" data-level="17.4.1" data-path="dbm-analysis-significance-testing.html"><a href="dbm-analysis-significance-testing.html#calculation-of-mean-squares-an-example"><i class="fa fa-check"></i><b>17.4.1</b> Calculation of mean squares: an example</a></li>
<li class="chapter" data-level="17.4.2" data-path="dbm-analysis-significance-testing.html"><a href="dbm-analysis-significance-testing.html#dbm-analysis-significance-testing-sig-testing"><i class="fa fa-check"></i><b>17.4.2</b> Significance testing</a></li>
<li class="chapter" data-level="17.4.3" data-path="dbm-analysis-significance-testing.html"><a href="dbm-analysis-significance-testing.html#the-satterthwaite-approximation"><i class="fa fa-check"></i><b>17.4.3</b> The Satterthwaite approximation</a></li>
<li class="chapter" data-level="17.4.4" data-path="dbm-analysis-significance-testing.html"><a href="dbm-analysis-significance-testing.html#decision-rules-p-value-and-confidence-intervals"><i class="fa fa-check"></i><b>17.4.4</b> Decision rules, p-value and confidence intervals</a></li>
</ul></li>
<li class="chapter" data-level="17.5" data-path="dbm-analysis-significance-testing.html"><a href="dbm-analysis-significance-testing.html#sample-size-estimation-for-random-reader-random-case-generalization"><i class="fa fa-check"></i><b>17.5</b> Sample size estimation for random-reader random-case generalization</a><ul>
<li class="chapter" data-level="17.5.1" data-path="dbm-analysis-significance-testing.html"><a href="dbm-analysis-significance-testing.html#the-non-centrality-parameter"><i class="fa fa-check"></i><b>17.5.1</b> The non-centrality parameter</a></li>
<li class="chapter" data-level="17.5.2" data-path="dbm-analysis-significance-testing.html"><a href="dbm-analysis-significance-testing.html#the-denominator-degrees-of-freedom"><i class="fa fa-check"></i><b>17.5.2</b> The denominator degrees of freedom</a></li>
<li class="chapter" data-level="17.5.3" data-path="dbm-analysis-significance-testing.html"><a href="dbm-analysis-significance-testing.html#example-of-sample-size-estimation-rrrc-generalization"><i class="fa fa-check"></i><b>17.5.3</b> Example of sample size estimation, RRRC generalization</a></li>
</ul></li>
<li class="chapter" data-level="17.6" data-path="dbm-analysis-significance-testing.html"><a href="dbm-analysis-significance-testing.html#significance-testing-and-sample-size-estimation-for-fixed-reader-random-case-generalization"><i class="fa fa-check"></i><b>17.6</b> Significance testing and sample size estimation for fixed-reader random-case generalization</a></li>
<li class="chapter" data-level="17.7" data-path="dbm-analysis-significance-testing.html"><a href="dbm-analysis-significance-testing.html#significance-testing-and-sample-size-estimation-for-random-reader-fixed-case-generalization"><i class="fa fa-check"></i><b>17.7</b> Significance testing and sample size estimation for random-reader fixed-case generalization</a></li>
<li class="chapter" data-level="17.8" data-path="dbm-analysis-significance-testing.html"><a href="dbm-analysis-significance-testing.html#dbm-analysis-significance-testing-summary"><i class="fa fa-check"></i><b>17.8</b> Summary TBA</a></li>
<li class="chapter" data-level="17.9" data-path="dbm-analysis-significance-testing.html"><a href="dbm-analysis-significance-testing.html#things-for-me-to-think-about"><i class="fa fa-check"></i><b>17.9</b> Things for me to think about</a><ul>
<li class="chapter" data-level="17.9.1" data-path="dbm-analysis-significance-testing.html"><a href="dbm-analysis-significance-testing.html#expected-values-of-mean-squares-1"><i class="fa fa-check"></i><b>17.9.1</b> Expected values of mean squares</a></li>
</ul></li>
<li class="chapter" data-level="17.10" data-path="dbm-analysis-significance-testing.html"><a href="dbm-analysis-significance-testing.html#dbm-analysis-significance-testing-references"><i class="fa fa-check"></i><b>17.10</b> References</a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="dbm-analysis-special-cases.html"><a href="dbm-analysis-special-cases.html"><i class="fa fa-check"></i><b>18</b> DBM method special cases</a><ul>
<li class="chapter" data-level="18.1" data-path="dbm-analysis-special-cases.html"><a href="dbm-analysis-special-cases.html#dbm-analysis-special-cases-fits-how-much-finished"><i class="fa fa-check"></i><b>18.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="18.2" data-path="dbm-analysis-special-cases.html"><a href="dbm-analysis-special-cases.html#FRRCDBMAnalysis"><i class="fa fa-check"></i><b>18.2</b> Fixed-reader random-case (FRRC) analysis</a><ul>
<li class="chapter" data-level="18.2.1" data-path="dbm-analysis-special-cases.html"><a href="dbm-analysis-special-cases.html#FRRCSingleReaderDBMAnalysis"><i class="fa fa-check"></i><b>18.2.1</b> Single-reader multiple-treatment analysis</a></li>
</ul></li>
<li class="chapter" data-level="18.3" data-path="dbm-analysis-special-cases.html"><a href="dbm-analysis-special-cases.html#dbm-analysis-special-cases-RRFCAnalysis"><i class="fa fa-check"></i><b>18.3</b> Random-reader fixed-case (RRFC) analysis</a></li>
<li class="chapter" data-level="18.4" data-path="dbm-analysis-special-cases.html"><a href="dbm-analysis-special-cases.html#dbm-analysis-special-cases-references"><i class="fa fa-check"></i><b>18.4</b> References</a></li>
</ul></li>
<li class="chapter" data-level="19" data-path="or-method-intro.html"><a href="or-method-intro.html"><i class="fa fa-check"></i><b>19</b> Introduction to the Obuchowski-Rockette method</a><ul>
<li class="chapter" data-level="19.1" data-path="or-method-intro.html"><a href="or-method-intro.html#or-method-intro-how-much-finished"><i class="fa fa-check"></i><b>19.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="19.2" data-path="or-method-intro.html"><a href="or-method-intro.html#or-method-intro-helper-functions"><i class="fa fa-check"></i><b>19.2</b> Locations of helper functions</a></li>
<li class="chapter" data-level="19.3" data-path="or-method-intro.html"><a href="or-method-intro.html#or-method-intro-intro"><i class="fa fa-check"></i><b>19.3</b> Introduction</a></li>
<li class="chapter" data-level="19.4" data-path="or-method-intro.html"><a href="or-method-intro.html#or-method-intro-single-reader"><i class="fa fa-check"></i><b>19.4</b> Single-reader multiple-treatment</a><ul>
<li class="chapter" data-level="19.4.1" data-path="or-method-intro.html"><a href="or-method-intro.html#or-method-intro-single-reader-overview"><i class="fa fa-check"></i><b>19.4.1</b> Overview</a></li>
<li class="chapter" data-level="19.4.2" data-path="or-method-intro.html"><a href="or-method-intro.html#st-or-multiple-treatment"><i class="fa fa-check"></i><b>19.4.2</b> Significance testing</a></li>
<li class="chapter" data-level="19.4.3" data-path="or-method-intro.html"><a href="or-method-intro.html#or-method-intro-pvalue-ci"><i class="fa fa-check"></i><b>19.4.3</b> p-value and confidence interval</a></li>
<li class="chapter" data-level="19.4.4" data-path="or-method-intro.html"><a href="or-method-intro.html#or-method-intro-single-reader-nh-validation"><i class="fa fa-check"></i><b>19.4.4</b> Null hypothesis validation</a></li>
<li class="chapter" data-level="19.4.5" data-path="or-method-intro.html"><a href="or-method-intro.html#or-method-intro-single-reader-application-roc"><i class="fa fa-check"></i><b>19.4.5</b> Application 1</a></li>
<li class="chapter" data-level="19.4.6" data-path="or-method-intro.html"><a href="or-method-intro.html#or-method-intro-single-reader-application-froc"><i class="fa fa-check"></i><b>19.4.6</b> Application 2</a></li>
</ul></li>
<li class="chapter" data-level="19.5" data-path="or-method-intro.html"><a href="or-method-intro.html#or-method-intro-single-treatment"><i class="fa fa-check"></i><b>19.5</b> Single-treatment multiple-reader</a><ul>
<li class="chapter" data-level="19.5.1" data-path="or-method-intro.html"><a href="or-method-intro.html#or-method-intro-single-treatment-overview"><i class="fa fa-check"></i><b>19.5.1</b> Overview</a></li>
<li class="chapter" data-level="19.5.2" data-path="or-method-intro.html"><a href="or-method-intro.html#st-or-multiple-reader"><i class="fa fa-check"></i><b>19.5.2</b> Significance testing</a></li>
<li class="chapter" data-level="19.5.3" data-path="or-method-intro.html"><a href="or-method-intro.html#st-or-multiple-reader-example-three"><i class="fa fa-check"></i><b>19.5.3</b> Special case</a></li>
</ul></li>
<li class="chapter" data-level="19.6" data-path="or-method-intro.html"><a href="or-method-intro.html#or-method-intro-multiple-reader-multiple-treatment"><i class="fa fa-check"></i><b>19.6</b> Multiple-reader multiple-treatment</a><ul>
<li class="chapter" data-level="19.6.1" data-path="or-method-intro.html"><a href="or-method-intro.html#StrCovMatrix"><i class="fa fa-check"></i><b>19.6.1</b> Structure of the covariance matrix</a></li>
<li class="chapter" data-level="19.6.2" data-path="or-method-intro.html"><a href="or-method-intro.html#PhysicalMeaningsOfCovMatrix"><i class="fa fa-check"></i><b>19.6.2</b> Physical meanings of the covariance terms</a></li>
</ul></li>
<li class="chapter" data-level="19.7" data-path="or-method-intro.html"><a href="or-method-intro.html#or-method-intro-summary"><i class="fa fa-check"></i><b>19.7</b> Summary</a></li>
<li class="chapter" data-level="19.8" data-path="or-method-intro.html"><a href="or-method-intro.html#or-method-intro-discussion"><i class="fa fa-check"></i><b>19.8</b> Discussion</a></li>
<li class="chapter" data-level="19.9" data-path="or-method-intro.html"><a href="or-method-intro.html#or-method-intro-elementary-stats"><i class="fa fa-check"></i><b>19.9</b> Appendix: Covariance and correlation</a><ul>
<li class="chapter" data-level="19.9.1" data-path="or-method-intro.html"><a href="or-method-intro.html#or-method-intro-elementary-stats-f-stat-chisq-stat"><i class="fa fa-check"></i><b>19.9.1</b> Relation: chisquare and F with infinite ddf</a></li>
<li class="chapter" data-level="19.9.2" data-path="or-method-intro.html"><a href="or-method-intro.html#or-method-intro-elementary-stats-def-cov-matrix"><i class="fa fa-check"></i><b>19.9.2</b> Definitions of covariance and correlation</a></li>
<li class="chapter" data-level="19.9.3" data-path="or-method-intro.html"><a href="or-method-intro.html#or-method-intro-elementary-stats-equal-variance"><i class="fa fa-check"></i><b>19.9.3</b> Special case when variables have equal variances</a></li>
<li class="chapter" data-level="19.9.4" data-path="or-method-intro.html"><a href="or-method-intro.html#or-method-intro-elementary-stats-est-cov-matrix"><i class="fa fa-check"></i><b>19.9.4</b> Estimating the variance-covariance matrix</a></li>
<li class="chapter" data-level="19.9.5" data-path="or-method-intro.html"><a href="or-method-intro.html#or-method-intro-elementary-stats-jack-var-inflation-factor"><i class="fa fa-check"></i><b>19.9.5</b> The variance inflation factor</a></li>
<li class="chapter" data-level="19.9.6" data-path="or-method-intro.html"><a href="or-method-intro.html#or-method-intro-elementary-stats-meaning-cov-matrix"><i class="fa fa-check"></i><b>19.9.6</b> Meaning of the covariance matrix</a></li>
<li class="chapter" data-level="19.9.7" data-path="or-method-intro.html"><a href="or-method-intro.html#or-method-intro-elementary-stats-code-cov-matrix"><i class="fa fa-check"></i><b>19.9.7</b> Code illustrating the covariance matrix</a></li>
<li class="chapter" data-level="19.9.8" data-path="or-method-intro.html"><a href="or-method-intro.html#or-method-intro-compare-dbm-or"><i class="fa fa-check"></i><b>19.9.8</b> Comparing DBM to Obuchowski and Rockette for single-reader multiple-treatments</a></li>
</ul></li>
<li class="chapter" data-level="19.10" data-path="or-method-intro.html"><a href="or-method-intro.html#or-method-intro-references"><i class="fa fa-check"></i><b>19.10</b> References</a></li>
</ul></li>
<li class="chapter" data-level="20" data-path="or-analysis-st.html"><a href="or-analysis-st.html"><i class="fa fa-check"></i><b>20</b> Obuchowski Rockette (OR) Analysis</a><ul>
<li class="chapter" data-level="20.1" data-path="or-analysis-st.html"><a href="or-analysis-st.html#or-analysis-st-how-much-finished"><i class="fa fa-check"></i><b>20.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="20.2" data-path="or-analysis-st.html"><a href="or-analysis-st.html#or-analysis-st-introduction"><i class="fa fa-check"></i><b>20.2</b> Introduction</a></li>
<li class="chapter" data-level="20.3" data-path="or-analysis-st.html"><a href="or-analysis-st.html#or-analysis-st-rrrc"><i class="fa fa-check"></i><b>20.3</b> Random-reader random-case</a><ul>
<li class="chapter" data-level="20.3.1" data-path="or-analysis-st.html"><a href="or-analysis-st.html#TwoAnecdotes"><i class="fa fa-check"></i><b>20.3.1</b> Two anecdotes</a></li>
<li class="chapter" data-level="20.3.2" data-path="or-analysis-st.html"><a href="or-analysis-st.html#Hills-ddf"><i class="fa fa-check"></i><b>20.3.2</b> Hillis ddf</a></li>
<li class="chapter" data-level="20.3.3" data-path="or-analysis-st.html"><a href="or-analysis-st.html#decision-rule-p-value-and-confidence-interval"><i class="fa fa-check"></i><b>20.3.3</b> Decision rule, p-value and confidence interval</a></li>
</ul></li>
<li class="chapter" data-level="20.4" data-path="or-analysis-st.html"><a href="or-analysis-st.html#or-analysis-st-frrc"><i class="fa fa-check"></i><b>20.4</b> Fixed-reader random-case</a></li>
<li class="chapter" data-level="20.5" data-path="or-analysis-st.html"><a href="or-analysis-st.html#or-analysis-st-rrfc"><i class="fa fa-check"></i><b>20.5</b> Random-reader fixed-case</a></li>
<li class="chapter" data-level="20.6" data-path="or-analysis-st.html"><a href="or-analysis-st.html#or-analysis-st-single-treatment"><i class="fa fa-check"></i><b>20.6</b> Single treatment analysis</a></li>
</ul></li>
<li class="chapter" data-level="21" data-path="or-applications.html"><a href="or-applications.html"><i class="fa fa-check"></i><b>21</b> Obuchowski Rockette Applications</a><ul>
<li class="chapter" data-level="21.1" data-path="or-applications.html"><a href="or-applications.html#or-applications-how-much-finished"><i class="fa fa-check"></i><b>21.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="21.2" data-path="or-applications.html"><a href="or-applications.html#or-applications-introduction"><i class="fa fa-check"></i><b>21.2</b> Introduction</a></li>
<li class="chapter" data-level="21.3" data-path="or-applications.html"><a href="or-applications.html#or-applications-dataset02-hand"><i class="fa fa-check"></i><b>21.3</b> Hand calculation</a><ul>
<li class="chapter" data-level="21.3.1" data-path="or-applications.html"><a href="or-applications.html#or-applications-RRRC-dataset02-hand"><i class="fa fa-check"></i><b>21.3.1</b> Random-Reader Random-Case (RRRC) analysis</a></li>
<li class="chapter" data-level="21.3.2" data-path="or-applications.html"><a href="or-applications.html#or-applications-FRRC-dataset02-hand"><i class="fa fa-check"></i><b>21.3.2</b> Fixed-Reader Random-Case (FRRC) analysis</a></li>
<li class="chapter" data-level="21.3.3" data-path="or-applications.html"><a href="or-applications.html#or-applications-RRFC-dataset02-hand"><i class="fa fa-check"></i><b>21.3.3</b> Random-Reader Fixed-Case (RRFC) analysis</a></li>
</ul></li>
<li class="chapter" data-level="21.4" data-path="or-applications.html"><a href="or-applications.html#or-applications-dataset02-RJafroc"><i class="fa fa-check"></i><b>21.4</b> RJafroc: dataset02</a><ul>
<li class="chapter" data-level="21.4.1" data-path="or-applications.html"><a href="or-applications.html#or-applications-RRRC-dataset02-RJafroc"><i class="fa fa-check"></i><b>21.4.1</b> Random-Reader Random-Case (RRRC) analysis</a></li>
<li class="chapter" data-level="21.4.2" data-path="or-applications.html"><a href="or-applications.html#or-applications-FRRC-dataset02-RJafroc"><i class="fa fa-check"></i><b>21.4.2</b> Fixed-Reader Random-Case (FRRC) analysis</a></li>
<li class="chapter" data-level="21.4.3" data-path="or-applications.html"><a href="or-applications.html#or-applications-RRFC-dataset02-RJafroc"><i class="fa fa-check"></i><b>21.4.3</b> Random-Reader Fixed-Case (RRFC) analysis</a></li>
</ul></li>
<li class="chapter" data-level="21.5" data-path="or-applications.html"><a href="or-applications.html#or-applications-dataset04-RJafroc"><i class="fa fa-check"></i><b>21.5</b> RJafroc: dataset04</a><ul>
<li class="chapter" data-level="21.5.1" data-path="or-applications.html"><a href="or-applications.html#or-applications-RRRC-dataset04"><i class="fa fa-check"></i><b>21.5.1</b> Random-Reader Random-Case (RRRC) analysis</a></li>
<li class="chapter" data-level="21.5.2" data-path="or-applications.html"><a href="or-applications.html#or-applications-FRRC-dataset04"><i class="fa fa-check"></i><b>21.5.2</b> Fixed-Reader Random-Case (FRRC) analysis</a></li>
<li class="chapter" data-level="21.5.3" data-path="or-applications.html"><a href="or-applications.html#or-applications-RRFC-dataset04"><i class="fa fa-check"></i><b>21.5.3</b> Random-Reader Fixed-Case (RRFC) analysis</a></li>
</ul></li>
<li class="chapter" data-level="21.6" data-path="or-applications.html"><a href="or-applications.html#or-applications-dataset04-FROC-RJafroc"><i class="fa fa-check"></i><b>21.6</b> RJafroc: dataset04, FROC</a><ul>
<li class="chapter" data-level="21.6.1" data-path="or-applications.html"><a href="or-applications.html#or-applications-RRRC-dataset04-FROC"><i class="fa fa-check"></i><b>21.6.1</b> Random-Reader Random-Case (RRRC) analysis</a></li>
<li class="chapter" data-level="21.6.2" data-path="or-applications.html"><a href="or-applications.html#or-applications-FRRC-dataset04-FROC"><i class="fa fa-check"></i><b>21.6.2</b> Fixed-Reader Random-Case (FRRC) analysis</a></li>
<li class="chapter" data-level="21.6.3" data-path="or-applications.html"><a href="or-applications.html#or-applications-RRFC-dataset04-FROC"><i class="fa fa-check"></i><b>21.6.3</b> Random-Reader Fixed-Case (RRFC) analysis</a></li>
</ul></li>
<li class="chapter" data-level="21.7" data-path="or-applications.html"><a href="or-applications.html#or-applications-dataset04-FROC-DBM-RJafroc"><i class="fa fa-check"></i><b>21.7</b> RJafroc: dataset04, FROC/DBM</a><ul>
<li class="chapter" data-level="21.7.1" data-path="or-applications.html"><a href="or-applications.html#or-applications-RRRC-dataset04-FROC-DBM"><i class="fa fa-check"></i><b>21.7.1</b> Random-Reader Random-Case (RRRC) analysis</a></li>
<li class="chapter" data-level="21.7.2" data-path="or-applications.html"><a href="or-applications.html#or-applications-FRRC-dataset04-FROC-DBM"><i class="fa fa-check"></i><b>21.7.2</b> Fixed-Reader Random-Case (FRRC) analysis</a></li>
<li class="chapter" data-level="21.7.3" data-path="or-applications.html"><a href="or-applications.html#or-applications-RRFC-dataset04-FROC-DBM"><i class="fa fa-check"></i><b>21.7.3</b> Random-Reader Fixed-Case (RRFC) analysis</a></li>
</ul></li>
<li class="chapter" data-level="21.8" data-path="or-applications.html"><a href="or-applications.html#or-applications-Summary"><i class="fa fa-check"></i><b>21.8</b> Summary</a></li>
<li class="chapter" data-level="21.9" data-path="or-applications.html"><a href="or-applications.html#or-applications-Discussion"><i class="fa fa-check"></i><b>21.9</b> Discussion</a></li>
<li class="chapter" data-level="21.10" data-path="or-applications.html"><a href="or-applications.html#ToMullOver1-tentative"><i class="fa fa-check"></i><b>21.10</b> Tentative</a></li>
<li class="chapter" data-level="21.11" data-path="or-applications.html"><a href="or-applications.html#or-applications-references"><i class="fa fa-check"></i><b>21.11</b> References</a></li>
</ul></li>
<li class="chapter" data-level="22" data-path="roc-sample-size-dbm.html"><a href="roc-sample-size-dbm.html"><i class="fa fa-check"></i><b>22</b> Sample size estimation for ROC studies DBM method</a><ul>
<li class="chapter" data-level="22.1" data-path="roc-sample-size-dbm.html"><a href="roc-sample-size-dbm.html#roc-sample-size-dbm-how-much-finished"><i class="fa fa-check"></i><b>22.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="22.2" data-path="roc-sample-size-dbm.html"><a href="roc-sample-size-dbm.html#roc-sample-size-dbm-introduction"><i class="fa fa-check"></i><b>22.2</b> Introduction</a></li>
<li class="chapter" data-level="22.3" data-path="roc-sample-size-dbm.html"><a href="roc-sample-size-dbm.html#StatPower1"><i class="fa fa-check"></i><b>22.3</b> Statistical Power</a><ul>
<li class="chapter" data-level="22.3.1" data-path="roc-sample-size-dbm.html"><a href="roc-sample-size-dbm.html#observed-vs.-anticipated-effect-size"><i class="fa fa-check"></i><b>22.3.1</b> Observed vs. anticipated effect-size</a></li>
<li class="chapter" data-level="22.3.2" data-path="roc-sample-size-dbm.html"><a href="roc-sample-size-dbm.html#roc-sample-size-dbm-dependence-of-stats-power"><i class="fa fa-check"></i><b>22.3.2</b> Dependence of statistical power on estimates of model parameters</a></li>
<li class="chapter" data-level="22.3.3" data-path="roc-sample-size-dbm.html"><a href="roc-sample-size-dbm.html#roc-sample-size-dbm-RRRC-sample-size-estimation"><i class="fa fa-check"></i><b>22.3.3</b> Formulae for random-reader random-case (RRRC) sample size estimation</a></li>
<li class="chapter" data-level="22.3.4" data-path="roc-sample-size-dbm.html"><a href="roc-sample-size-dbm.html#roc-sample-size-dbm-sig-testing"><i class="fa fa-check"></i><b>22.3.4</b> Significance testing</a></li>
<li class="chapter" data-level="22.3.5" data-path="roc-sample-size-dbm.html"><a href="roc-sample-size-dbm.html#roc-sample-size-dbm-pvalue-ci"><i class="fa fa-check"></i><b>22.3.5</b> p-value and confidence interval</a></li>
<li class="chapter" data-level="22.3.6" data-path="roc-sample-size-dbm.html"><a href="roc-sample-size-dbm.html#roc-sample-size-dbm-CompareDBM2OR"><i class="fa fa-check"></i><b>22.3.6</b> Comparing DBM to Obuchowski and Rockette for single-reader multiple-treatments</a></li>
</ul></li>
<li class="chapter" data-level="22.4" data-path="roc-sample-size-dbm.html"><a href="roc-sample-size-dbm.html#roc-sample-size-dbm-FRRC-sample-size-estimation"><i class="fa fa-check"></i><b>22.4</b> Formulae for fixed-reader random-case (FRRC) sample size estimation</a><ul>
<li class="chapter" data-level="22.4.1" data-path="roc-sample-size-dbm.html"><a href="roc-sample-size-dbm.html#roc-sample-size-dbm-RRFC-sample-size-estimation"><i class="fa fa-check"></i><b>22.4.1</b> Formulae for random-reader fixed-case (RRFC) sample size estimation</a></li>
<li class="chapter" data-level="22.4.2" data-path="roc-sample-size-dbm.html"><a href="roc-sample-size-dbm.html#roc-sample-size-dbm-FRRCAnalysis"><i class="fa fa-check"></i><b>22.4.2</b> Fixed-reader random-case (FRRC) analysis TBA</a></li>
<li class="chapter" data-level="22.4.3" data-path="roc-sample-size-dbm.html"><a href="roc-sample-size-dbm.html#roc-sample-size-dbm-RRFCAnalysis"><i class="fa fa-check"></i><b>22.4.3</b> Random-reader fixed-case (RRFC) analysis</a></li>
<li class="chapter" data-level="22.4.4" data-path="roc-sample-size-dbm.html"><a href="roc-sample-size-dbm.html#roc-sample-size-dbm-STMRAnalysis"><i class="fa fa-check"></i><b>22.4.4</b> Single-treatment multiple-reader analysis</a></li>
</ul></li>
<li class="chapter" data-level="22.5" data-path="roc-sample-size-dbm.html"><a href="roc-sample-size-dbm.html#discussionsummary2"><i class="fa fa-check"></i><b>22.5</b> Discussion/Summary/2</a></li>
<li class="chapter" data-level="22.6" data-path="roc-sample-size-dbm.html"><a href="roc-sample-size-dbm.html#roc-sample-size-dbm-references"><i class="fa fa-check"></i><b>22.6</b> References</a></li>
</ul></li>
<li class="chapter" data-level="23" data-path="roc-sample-size-or.html"><a href="roc-sample-size-or.html"><i class="fa fa-check"></i><b>23</b> Sample size estimation for ROC studies OR method</a><ul>
<li class="chapter" data-level="23.1" data-path="roc-sample-size-or.html"><a href="roc-sample-size-or.html#roc-sample-size-or-how-much-finished"><i class="fa fa-check"></i><b>23.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="23.2" data-path="roc-sample-size-or.html"><a href="roc-sample-size-or.html#roc-sample-size-or-introduction"><i class="fa fa-check"></i><b>23.2</b> Introduction</a></li>
<li class="chapter" data-level="23.3" data-path="roc-sample-size-or.html"><a href="roc-sample-size-or.html#StatPower2"><i class="fa fa-check"></i><b>23.3</b> Statistical Power</a><ul>
<li class="chapter" data-level="23.3.1" data-path="roc-sample-size-or.html"><a href="roc-sample-size-or.html#sample-size-estimation-for-random-reader-random-cases"><i class="fa fa-check"></i><b>23.3.1</b> Sample size estimation for random-reader random-cases</a></li>
<li class="chapter" data-level="23.3.2" data-path="roc-sample-size-or.html"><a href="roc-sample-size-or.html#roc-sample-size-or-dependence-of-stats-power"><i class="fa fa-check"></i><b>23.3.2</b> Dependence of statistical power on estimates of model parameters</a></li>
<li class="chapter" data-level="23.3.3" data-path="roc-sample-size-or.html"><a href="roc-sample-size-or.html#roc-sample-size-or-RRRC-sample-size-estimation"><i class="fa fa-check"></i><b>23.3.3</b> Formulae for random-reader random-case (RRRC) sample size estimation</a></li>
<li class="chapter" data-level="23.3.4" data-path="roc-sample-size-or.html"><a href="roc-sample-size-or.html#roc-sample-size-or-sig-testing"><i class="fa fa-check"></i><b>23.3.4</b> Significance testing</a></li>
<li class="chapter" data-level="23.3.5" data-path="roc-sample-size-or.html"><a href="roc-sample-size-or.html#roc-sample-size-or-pvalue-ci"><i class="fa fa-check"></i><b>23.3.5</b> p-value and confidence interval</a></li>
<li class="chapter" data-level="23.3.6" data-path="roc-sample-size-or.html"><a href="roc-sample-size-or.html#roc-sample-size-or-CompareDBM2OR"><i class="fa fa-check"></i><b>23.3.6</b> Comparing DBM to Obuchowski and Rockette for single-reader multiple-treatments</a></li>
</ul></li>
<li class="chapter" data-level="23.4" data-path="roc-sample-size-or.html"><a href="roc-sample-size-or.html#roc-sample-size-or-FRRC-sample-size-estimation"><i class="fa fa-check"></i><b>23.4</b> Formulae for fixed-reader random-case (FRRC) sample size estimation</a><ul>
<li class="chapter" data-level="23.4.1" data-path="roc-sample-size-or.html"><a href="roc-sample-size-or.html#roc-sample-size-or-RRFC-sample-size-estimation"><i class="fa fa-check"></i><b>23.4.1</b> Formulae for random-reader fixed-case (RRFC) sample size estimation</a></li>
<li class="chapter" data-level="23.4.2" data-path="roc-sample-size-or.html"><a href="roc-sample-size-or.html#example-1"><i class="fa fa-check"></i><b>23.4.2</b> Example 1</a></li>
<li class="chapter" data-level="23.4.3" data-path="roc-sample-size-or.html"><a href="roc-sample-size-or.html#roc-sample-size-or-FRRCAnalysis"><i class="fa fa-check"></i><b>23.4.3</b> Fixed-reader random-case (FRRC) analysis</a></li>
<li class="chapter" data-level="23.4.4" data-path="roc-sample-size-or.html"><a href="roc-sample-size-or.html#roc-sample-size-or-RRFCAnalysis"><i class="fa fa-check"></i><b>23.4.4</b> Random-reader fixed-case (RRFC) analysis</a></li>
<li class="chapter" data-level="23.4.5" data-path="roc-sample-size-or.html"><a href="roc-sample-size-or.html#roc-sample-size-or-STMRAnalysis"><i class="fa fa-check"></i><b>23.4.5</b> Single-treatment multiple-reader analysis</a></li>
</ul></li>
<li class="chapter" data-level="23.5" data-path="roc-sample-size-or.html"><a href="roc-sample-size-or.html#discussionsummary3"><i class="fa fa-check"></i><b>23.5</b> Discussion/Summary/3</a></li>
<li class="chapter" data-level="23.6" data-path="roc-sample-size-or.html"><a href="roc-sample-size-or.html#roc-sample-size-or-references"><i class="fa fa-check"></i><b>23.6</b> References</a></li>
</ul></li>
<li class="part"><span><b>FROC paradigm</b></span></li>
<li class="chapter" data-level="24" data-path="froc-paradigm.html"><a href="froc-paradigm.html"><i class="fa fa-check"></i><b>24</b> The FROC paradigm</a><ul>
<li class="chapter" data-level="24.1" data-path="froc-paradigm.html"><a href="froc-paradigm.html#froc-paradigm-how-much-finished"><i class="fa fa-check"></i><b>24.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="24.2" data-path="froc-paradigm.html"><a href="froc-paradigm.html#froc-paradigm-intro"><i class="fa fa-check"></i><b>24.2</b> Introduction</a></li>
<li class="chapter" data-level="24.3" data-path="froc-paradigm.html"><a href="froc-paradigm.html#location-specific-paradigms"><i class="fa fa-check"></i><b>24.3</b> Location specific paradigms</a></li>
<li class="chapter" data-level="24.4" data-path="froc-paradigm.html"><a href="froc-paradigm.html#froc-paradigm-vis-search"><i class="fa fa-check"></i><b>24.4</b> Visual search</a><ul>
<li class="chapter" data-level="24.4.1" data-path="froc-paradigm.html"><a href="froc-paradigm.html#froc-paradigm-scoring-the-data"><i class="fa fa-check"></i><b>24.4.1</b> Proximity criterion and scoring the data</a></li>
<li class="chapter" data-level="24.4.2" data-path="froc-paradigm.html"><a href="froc-paradigm.html#multiple-marks-in-the-same-vicinity"><i class="fa fa-check"></i><b>24.4.2</b> Multiple marks in the same vicinity</a></li>
<li class="chapter" data-level="24.4.3" data-path="froc-paradigm.html"><a href="froc-paradigm.html#historical-context"><i class="fa fa-check"></i><b>24.4.3</b> Historical context</a></li>
</ul></li>
<li class="chapter" data-level="24.5" data-path="froc-paradigm.html"><a href="froc-paradigm.html#a-pioneering-froc-study-in-medical-imaging"><i class="fa fa-check"></i><b>24.5</b> A pioneering FROC study in medical imaging</a><ul>
<li class="chapter" data-level="24.5.1" data-path="froc-paradigm.html"><a href="froc-paradigm.html#image-preparation"><i class="fa fa-check"></i><b>24.5.1</b> Image preparation</a></li>
<li class="chapter" data-level="24.5.2" data-path="froc-paradigm.html"><a href="froc-paradigm.html#image-interpretation-and-the-1-rating"><i class="fa fa-check"></i><b>24.5.2</b> Image Interpretation and the 1-rating</a></li>
<li class="chapter" data-level="24.5.3" data-path="froc-paradigm.html"><a href="froc-paradigm.html#scoring-the-data"><i class="fa fa-check"></i><b>24.5.3</b> Scoring the data</a></li>
</ul></li>
<li class="chapter" data-level="24.6" data-path="froc-paradigm.html"><a href="froc-paradigm.html#froc-paradigm-froc-plot"><i class="fa fa-check"></i><b>24.6</b> The free-response receiver operating characteristic (FROC) plot</a></li>
<li class="chapter" data-level="24.7" data-path="froc-paradigm.html"><a href="froc-paradigm.html#froc-paradigm-preview-rsm"><i class="fa fa-check"></i><b>24.7</b> Preview of the RSM data simulator</a></li>
<li class="chapter" data-level="24.8" data-path="froc-paradigm.html"><a href="froc-paradigm.html#froc-paradigm-pop-binned-plots"><i class="fa fa-check"></i><b>24.8</b> Population and binned FROC plots</a></li>
<li class="chapter" data-level="24.9" data-path="froc-paradigm.html"><a href="froc-paradigm.html#froc-paradigm-perceptual-snr"><i class="fa fa-check"></i><b>24.9</b> Perceptual SNR</a></li>
<li class="chapter" data-level="24.10" data-path="froc-paradigm.html"><a href="froc-paradigm.html#froc-paradigm-solar-analogy"><i class="fa fa-check"></i><b>24.10</b> The “solar” analogy: search vs. classification performance</a></li>
<li class="chapter" data-level="24.11" data-path="froc-paradigm.html"><a href="froc-paradigm.html#froc-paradigm-discussion"><i class="fa fa-check"></i><b>24.11</b> Discussion and suggestions</a></li>
<li class="chapter" data-level="24.12" data-path="froc-paradigm.html"><a href="froc-paradigm.html#froc-paradigm-references"><i class="fa fa-check"></i><b>24.12</b> References</a></li>
</ul></li>
<li class="chapter" data-level="25" data-path="froc-empirical.html"><a href="froc-empirical.html"><i class="fa fa-check"></i><b>25</b> Empirical plots</a><ul>
<li class="chapter" data-level="25.1" data-path="froc-empirical.html"><a href="froc-empirical.html#froc-empirical-how-much-finished"><i class="fa fa-check"></i><b>25.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="25.2" data-path="froc-empirical.html"><a href="froc-empirical.html#froc-empirical-intro"><i class="fa fa-check"></i><b>25.2</b> Introduction</a></li>
<li class="chapter" data-level="25.3" data-path="froc-empirical.html"><a href="froc-empirical.html#froc-empirical-mark-rating-pairs"><i class="fa fa-check"></i><b>25.3</b> Mark rating pairs</a><ul>
<li class="chapter" data-level="25.3.1" data-path="froc-empirical.html"><a href="froc-empirical.html#latent-vs.-actual-marks"><i class="fa fa-check"></i><b>25.3.1</b> Latent vs. actual marks</a></li>
<li class="chapter" data-level="25.3.2" data-path="froc-empirical.html"><a href="froc-empirical.html#binning-rule"><i class="fa fa-check"></i><b>25.3.2</b> Binning rule</a></li>
</ul></li>
<li class="chapter" data-level="25.4" data-path="froc-empirical.html"><a href="froc-empirical.html#froc-empirical-notation"><i class="fa fa-check"></i><b>25.4</b> FROC notation</a><ul>
<li class="chapter" data-level="25.4.1" data-path="froc-empirical.html"><a href="froc-empirical.html#comments-on-table-reftabfroc-empirical-notation"><i class="fa fa-check"></i><b>25.4.1</b> Comments on Table @ref(tab:froc-empirical-notation)</a></li>
<li class="chapter" data-level="25.4.2" data-path="froc-empirical.html"><a href="froc-empirical.html#discussion-cases-with-zero-latent-nl-marks"><i class="fa fa-check"></i><b>25.4.2</b> Discussion: cases with zero latent NL marks</a></li>
</ul></li>
<li class="chapter" data-level="25.5" data-path="froc-empirical.html"><a href="froc-empirical.html#froc-empirical-froc-plot"><i class="fa fa-check"></i><b>25.5</b> The empirical FROC</a><ul>
<li class="chapter" data-level="25.5.1" data-path="froc-empirical.html"><a href="froc-empirical.html#froc-empirical-definition-auc-FROC"><i class="fa fa-check"></i><b>25.5.1</b> Definition</a></li>
<li class="chapter" data-level="25.5.2" data-path="froc-empirical.html"><a href="froc-empirical.html#froc-empirical-origin-trivial-point"><i class="fa fa-check"></i><b>25.5.2</b> The origin, a trivial point</a></li>
<li class="chapter" data-level="25.5.3" data-path="froc-empirical.html"><a href="froc-empirical.html#froc-empirical-end-point"><i class="fa fa-check"></i><b>25.5.3</b> The observed end-point and its semi-constrained property</a></li>
<li class="chapter" data-level="25.5.4" data-path="froc-empirical.html"><a href="froc-empirical.html#froc-empirical-froc-plot-futility-extrapolation"><i class="fa fa-check"></i><b>25.5.4</b> Futility of extrapolation outside the observed end-point</a></li>
</ul></li>
<li class="chapter" data-level="25.6" data-path="froc-empirical.html"><a href="froc-empirical.html#froc-empirical-ROC"><i class="fa fa-check"></i><b>25.6</b> The inferred ROC plot</a><ul>
<li class="chapter" data-level="25.6.1" data-path="froc-empirical.html"><a href="froc-empirical.html#inferred-roc-rating"><i class="fa fa-check"></i><b>25.6.1</b> Inferred-ROC rating</a></li>
<li class="chapter" data-level="25.6.2" data-path="froc-empirical.html"><a href="froc-empirical.html#inferred-fpf"><i class="fa fa-check"></i><b>25.6.2</b> Inferred FPF</a></li>
<li class="chapter" data-level="25.6.3" data-path="froc-empirical.html"><a href="froc-empirical.html#inferred-tpf"><i class="fa fa-check"></i><b>25.6.3</b> Inferred TPF</a></li>
<li class="chapter" data-level="25.6.4" data-path="froc-empirical.html"><a href="froc-empirical.html#froc-empirical-definition-auc-ROC"><i class="fa fa-check"></i><b>25.6.4</b> Definition</a></li>
</ul></li>
<li class="chapter" data-level="25.7" data-path="froc-empirical.html"><a href="froc-empirical.html#froc-empirical-AFROC"><i class="fa fa-check"></i><b>25.7</b> The alternative FROC (AFROC) plot</a><ul>
<li class="chapter" data-level="25.7.1" data-path="froc-empirical.html"><a href="froc-empirical.html#froc-empirical-definition-auc-AFROC"><i class="fa fa-check"></i><b>25.7.1</b> Definition</a></li>
<li class="chapter" data-level="25.7.2" data-path="froc-empirical.html"><a href="froc-empirical.html#froc-empirical-AFROC-constrained"><i class="fa fa-check"></i><b>25.7.2</b> The constrained observed end-point of the AFROC</a></li>
</ul></li>
<li class="chapter" data-level="25.8" data-path="froc-empirical.html"><a href="froc-empirical.html#froc-empirical-wAFROC"><i class="fa fa-check"></i><b>25.8</b> The weighted-AFROC (wAFROC) plot</a><ul>
<li class="chapter" data-level="25.8.1" data-path="froc-empirical.html"><a href="froc-empirical.html#froc-empirical-definition-auc-wAFROC"><i class="fa fa-check"></i><b>25.8.1</b> Definition</a></li>
</ul></li>
<li class="chapter" data-level="25.9" data-path="froc-empirical.html"><a href="froc-empirical.html#froc-empirical-AFROC1"><i class="fa fa-check"></i><b>25.9</b> The AFROC1 plot</a><ul>
<li class="chapter" data-level="25.9.1" data-path="froc-empirical.html"><a href="froc-empirical.html#froc-empirical-definition-auc-AFROC1"><i class="fa fa-check"></i><b>25.9.1</b> Definition</a></li>
</ul></li>
<li class="chapter" data-level="25.10" data-path="froc-empirical.html"><a href="froc-empirical.html#froc-empirical-wAFROC1"><i class="fa fa-check"></i><b>25.10</b> The weighted-AFROC1 (wAFROC1) plot</a><ul>
<li class="chapter" data-level="25.10.1" data-path="froc-empirical.html"><a href="froc-empirical.html#froc-empirical-definition-auc-wAFROC1"><i class="fa fa-check"></i><b>25.10.1</b> Definition</a></li>
</ul></li>
<li class="chapter" data-level="25.11" data-path="froc-empirical.html"><a href="froc-empirical.html#froc-empirical-EFROC"><i class="fa fa-check"></i><b>25.11</b> The EFROC plot</a><ul>
<li class="chapter" data-level="25.11.1" data-path="froc-empirical.html"><a href="froc-empirical.html#froc-empirical-definition-auc-EFROC"><i class="fa fa-check"></i><b>25.11.1</b> Definition</a></li>
</ul></li>
<li class="chapter" data-level="25.12" data-path="froc-empirical.html"><a href="froc-empirical.html#froc-empirical-Discussion"><i class="fa fa-check"></i><b>25.12</b> Discussion</a></li>
<li class="chapter" data-level="25.13" data-path="froc-empirical.html"><a href="froc-empirical.html#froc-empirical-references"><i class="fa fa-check"></i><b>25.13</b> References</a></li>
</ul></li>
<li class="chapter" data-level="26" data-path="froc-empirical-examples.html"><a href="froc-empirical-examples.html"><i class="fa fa-check"></i><b>26</b> Empirical plot examples</a><ul>
<li class="chapter" data-level="26.1" data-path="froc-empirical-examples.html"><a href="froc-empirical-examples.html#froc-empirical-examples-how-much-finished"><i class="fa fa-check"></i><b>26.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="26.2" data-path="froc-empirical-examples.html"><a href="froc-empirical-examples.html#froc-empirical-examples-intro"><i class="fa fa-check"></i><b>26.2</b> Introduction</a></li>
<li class="chapter" data-level="26.3" data-path="froc-empirical-examples.html"><a href="froc-empirical-examples.html#raw-frocafrocroc-plots"><i class="fa fa-check"></i><b>26.3</b> Raw FROC/AFROC/ROC plots</a><ul>
<li class="chapter" data-level="26.3.1" data-path="froc-empirical-examples.html"><a href="froc-empirical-examples.html#froc-empirical-examples-raw-plots-code1"><i class="fa fa-check"></i><b>26.3.1</b> Code for raw plots</a></li>
<li class="chapter" data-level="26.3.2" data-path="froc-empirical-examples.html"><a href="froc-empirical-examples.html#explanation-of-the-code"><i class="fa fa-check"></i><b>26.3.2</b> Explanation of the code</a></li>
<li class="chapter" data-level="26.3.3" data-path="froc-empirical-examples.html"><a href="froc-empirical-examples.html#key-differences-from-the-roc-paradigm"><i class="fa fa-check"></i><b>26.3.3</b> Key differences from the ROC paradigm:</a></li>
</ul></li>
<li class="chapter" data-level="26.4" data-path="froc-empirical-examples.html"><a href="froc-empirical-examples.html#the-chance-level-froc-and-afroc"><i class="fa fa-check"></i><b>26.4</b> The chance level FROC and AFROC</a></li>
<li class="chapter" data-level="26.5" data-path="froc-empirical-examples.html"><a href="froc-empirical-examples.html#location-level-true-negatives"><i class="fa fa-check"></i><b>26.5</b> Location-level “true-negatives”</a></li>
<li class="chapter" data-level="26.6" data-path="froc-empirical-examples.html"><a href="froc-empirical-examples.html#binned-frocafrocroc-plots"><i class="fa fa-check"></i><b>26.6</b> Binned FROC/AFROC/ROC plots</a><ul>
<li class="chapter" data-level="26.6.1" data-path="froc-empirical-examples.html"><a href="froc-empirical-examples.html#binned-plots-code1"><i class="fa fa-check"></i><b>26.6.1</b> Code for binned plots</a></li>
<li class="chapter" data-level="26.6.2" data-path="froc-empirical-examples.html"><a href="froc-empirical-examples.html#effect-of-seed-on-binned-plots"><i class="fa fa-check"></i><b>26.6.2</b> Effect of <code>seed</code> on binned plots</a></li>
</ul></li>
<li class="chapter" data-level="26.7" data-path="froc-empirical-examples.html"><a href="froc-empirical-examples.html#froc-empirical-examples-str-binned-data"><i class="fa fa-check"></i><b>26.7</b> Structure of the binned data</a></li>
<li class="chapter" data-level="26.8" data-path="froc-empirical-examples.html"><a href="froc-empirical-examples.html#froc-empirical-examples-summary"><i class="fa fa-check"></i><b>26.8</b> Summary</a></li>
<li class="chapter" data-level="26.9" data-path="froc-empirical-examples.html"><a href="froc-empirical-examples.html#froc-empirical-examples-Discussion"><i class="fa fa-check"></i><b>26.9</b> Discussion</a></li>
<li class="chapter" data-level="26.10" data-path="froc-empirical-examples.html"><a href="froc-empirical-examples.html#froc-empirical-examples-references"><i class="fa fa-check"></i><b>26.10</b> References</a></li>
</ul></li>
<li class="chapter" data-level="27" data-path="froc-vs-wafroc.html"><a href="froc-vs-wafroc.html"><i class="fa fa-check"></i><b>27</b> FROC vs. wAFROC</a><ul>
<li class="chapter" data-level="27.1" data-path="froc-vs-wafroc.html"><a href="froc-vs-wafroc.html#froc-vs-wafroc-how-much-finished"><i class="fa fa-check"></i><b>27.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="27.2" data-path="froc-vs-wafroc.html"><a href="froc-vs-wafroc.html#froc-vs-wafroc-intro"><i class="fa fa-check"></i><b>27.2</b> Introduction</a></li>
<li class="chapter" data-level="27.3" data-path="froc-vs-wafroc.html"><a href="froc-vs-wafroc.html#froc-vs.-wafroc"><i class="fa fa-check"></i><b>27.3</b> FROC vs. wAFROC</a><ul>
<li class="chapter" data-level="27.3.1" data-path="froc-vs-wafroc.html"><a href="froc-vs-wafroc.html#moderate-difference-in-performance"><i class="fa fa-check"></i><b>27.3.1</b> Moderate difference in performance</a></li>
<li class="chapter" data-level="27.3.2" data-path="froc-vs-wafroc.html"><a href="froc-vs-wafroc.html#large-difference-in-performance"><i class="fa fa-check"></i><b>27.3.2</b> Large difference in performance</a></li>
<li class="chapter" data-level="27.3.3" data-path="froc-vs-wafroc.html"><a href="froc-vs-wafroc.html#small-difference-in-performance-and-identical-thresholds"><i class="fa fa-check"></i><b>27.3.3</b> Small difference in performance and identical thresholds</a></li>
</ul></li>
<li class="chapter" data-level="27.4" data-path="froc-vs-wafroc.html"><a href="froc-vs-wafroc.html#summary-of-simulations"><i class="fa fa-check"></i><b>27.4</b> Summary of simulations</a><ul>
<li class="chapter" data-level="27.4.1" data-path="froc-vs-wafroc.html"><a href="froc-vs-wafroc.html#summary-of-r1-simulations"><i class="fa fa-check"></i><b>27.4.1</b> Summary of R1 simulations</a></li>
<li class="chapter" data-level="27.4.2" data-path="froc-vs-wafroc.html"><a href="froc-vs-wafroc.html#summary-of-r2-simulations"><i class="fa fa-check"></i><b>27.4.2</b> Summary of R2 simulations</a></li>
<li class="chapter" data-level="27.4.3" data-path="froc-vs-wafroc.html"><a href="froc-vs-wafroc.html#froc-vs-wafroc-comments"><i class="fa fa-check"></i><b>27.4.3</b> Comments</a></li>
</ul></li>
<li class="chapter" data-level="27.5" data-path="froc-vs-wafroc.html"><a href="froc-vs-wafroc.html#froc-vs-wafroc-effect-sizes"><i class="fa fa-check"></i><b>27.5</b> Effect size comparison</a></li>
<li class="chapter" data-level="27.6" data-path="froc-vs-wafroc.html"><a href="froc-vs-wafroc.html#froc-vs-wafroc-peformance-depends-on-zeta1"><i class="fa fa-check"></i><b>27.6</b> Performance depends on <span class="math inline">\(\zeta_1\)</span></a></li>
<li class="chapter" data-level="27.7" data-path="froc-vs-wafroc.html"><a href="froc-vs-wafroc.html#froc-vs-wafroc-Discussion"><i class="fa fa-check"></i><b>27.7</b> Discussion</a></li>
<li class="chapter" data-level="27.8" data-path="froc-vs-wafroc.html"><a href="froc-vs-wafroc.html#froc-vs-wafroc-references"><i class="fa fa-check"></i><b>27.8</b> References</a></li>
</ul></li>
<li class="chapter" data-level="28" data-path="froc-meanings.html"><a href="froc-meanings.html"><i class="fa fa-check"></i><b>28</b> Meanings of FROC figures of merit</a><ul>
<li class="chapter" data-level="28.1" data-path="froc-meanings.html"><a href="froc-meanings.html#froc-meanings-how-much-finished"><i class="fa fa-check"></i><b>28.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="28.2" data-path="froc-meanings.html"><a href="froc-meanings.html#froc-meanings-intro"><i class="fa fa-check"></i><b>28.2</b> Introduction</a></li>
<li class="chapter" data-level="28.3" data-path="froc-meanings.html"><a href="froc-meanings.html#froc-meanings-afroc"><i class="fa fa-check"></i><b>28.3</b> Empirical AFROC FOM-statistic</a><ul>
<li class="chapter" data-level="28.3.1" data-path="froc-meanings.html"><a href="froc-meanings.html#upper-limit-for-afroc-fom-statistic"><i class="fa fa-check"></i><b>28.3.1</b> Upper limit for AFROC FOM-statistic</a></li>
<li class="chapter" data-level="28.3.2" data-path="froc-meanings.html"><a href="froc-meanings.html#range-of-afroc-fom-statistic"><i class="fa fa-check"></i><b>28.3.2</b> Range of AFROC FOM-statistic</a></li>
</ul></li>
<li class="chapter" data-level="28.4" data-path="froc-meanings.html"><a href="froc-meanings.html#froc-meanings-wafroc"><i class="fa fa-check"></i><b>28.4</b> Empirical weighted-AFROC FOM-statistic</a></li>
<li class="chapter" data-level="28.5" data-path="froc-meanings.html"><a href="froc-meanings.html#froc-meanings-two-theorems"><i class="fa fa-check"></i><b>28.5</b> Two Theorems</a><ul>
<li class="chapter" data-level="28.5.1" data-path="froc-meanings.html"><a href="froc-meanings.html#froc-meanings-two-theorems-1"><i class="fa fa-check"></i><b>28.5.1</b> Theorem 1</a></li>
<li class="chapter" data-level="28.5.2" data-path="froc-meanings.html"><a href="froc-meanings.html#froc-meanings-two-theorems-2"><i class="fa fa-check"></i><b>28.5.2</b> Theorem 2</a></li>
</ul></li>
<li class="chapter" data-level="28.6" data-path="froc-meanings.html"><a href="froc-meanings.html#froc-meanings-numerical-illustrations"><i class="fa fa-check"></i><b>28.6</b> Numerical illustrations</a></li>
<li class="chapter" data-level="28.7" data-path="froc-meanings.html"><a href="froc-meanings.html#summary-tables-of-ratings"><i class="fa fa-check"></i><b>28.7</b> Summary tables of ratings</a></li>
<li class="chapter" data-level="28.8" data-path="froc-meanings.html"><a href="froc-meanings.html#froc-meanings-AFROC-plot-first-principles"><i class="fa fa-check"></i><b>28.8</b> AFROC plot from first principles</a></li>
<li class="chapter" data-level="28.9" data-path="froc-meanings.html"><a href="froc-meanings.html#froc-meanings-wAFROC-plot-first-principles"><i class="fa fa-check"></i><b>28.9</b> wAFROC plot from first principles</a></li>
<li class="chapter" data-level="28.10" data-path="froc-meanings.html"><a href="froc-meanings.html#froc-meanings-physical-interpretions"><i class="fa fa-check"></i><b>28.10</b> Physical interpretations</a><ul>
<li class="chapter" data-level="28.10.1" data-path="froc-meanings.html"><a href="froc-meanings.html#physical-interpretation-of-area-under-afroc"><i class="fa fa-check"></i><b>28.10.1</b> Physical interpretation of area under AFROC</a></li>
<li class="chapter" data-level="28.10.2" data-path="froc-meanings.html"><a href="froc-meanings.html#physical-interpretation-of-area-under-wafroc"><i class="fa fa-check"></i><b>28.10.2</b> Physical interpretation of area under wAFROC</a></li>
</ul></li>
<li class="chapter" data-level="28.11" data-path="froc-meanings.html"><a href="froc-meanings.html#froc-meanings-Discussion"><i class="fa fa-check"></i><b>28.11</b> Discussion</a></li>
<li class="chapter" data-level="28.12" data-path="froc-meanings.html"><a href="froc-meanings.html#froc-meanings-references"><i class="fa fa-check"></i><b>28.12</b> References</a></li>
</ul></li>
<li class="chapter" data-level="29" data-path="visual-search.html"><a href="visual-search.html"><i class="fa fa-check"></i><b>29</b> Visual Search</a><ul>
<li class="chapter" data-level="29.1" data-path="visual-search.html"><a href="visual-search.html#visual-search-how-much-finished"><i class="fa fa-check"></i><b>29.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="29.2" data-path="visual-search.html"><a href="visual-search.html#visual-search-intro"><i class="fa fa-check"></i><b>29.2</b> Introduction</a></li>
<li class="chapter" data-level="29.3" data-path="visual-search.html"><a href="visual-search.html#visual-search-grouping-labeling-rois"><i class="fa fa-check"></i><b>29.3</b> Grouping and labeling ROIs</a></li>
<li class="chapter" data-level="29.4" data-path="visual-search.html"><a href="visual-search.html#visual-search-recognition-detection"><i class="fa fa-check"></i><b>29.4</b> Recognition vs. detection</a></li>
<li class="chapter" data-level="29.5" data-path="visual-search.html"><a href="visual-search.html#visual-search-search-classification"><i class="fa fa-check"></i><b>29.5</b> Search vs. classification</a></li>
<li class="chapter" data-level="29.6" data-path="visual-search.html"><a href="visual-search.html#visual-search-two-search-paradigms"><i class="fa fa-check"></i><b>29.6</b> Two visual search paradigms</a><ul>
<li class="chapter" data-level="29.6.1" data-path="visual-search.html"><a href="visual-search.html#visual-search-conventional-paradigm"><i class="fa fa-check"></i><b>29.6.1</b> The conventional paradigm</a></li>
<li class="chapter" data-level="29.6.2" data-path="visual-search.html"><a href="visual-search.html#visual-search-medical-imaging-search-paradigm"><i class="fa fa-check"></i><b>29.6.2</b> The medical imaging visual search paradigm</a></li>
</ul></li>
<li class="chapter" data-level="29.7" data-path="visual-search.html"><a href="visual-search.html#visual-search-determining-where-radiologist-looks"><i class="fa fa-check"></i><b>29.7</b> Determining where the radiologist looks</a></li>
<li class="chapter" data-level="29.8" data-path="visual-search.html"><a href="visual-search.html#visual-search-kundel-nodine-model"><i class="fa fa-check"></i><b>29.8</b> The Kundel - Nodine search model</a><ul>
<li class="chapter" data-level="29.8.1" data-path="visual-search.html"><a href="visual-search.html#visual-search-glancing-global-impression"><i class="fa fa-check"></i><b>29.8.1</b> Glancing / Global impression</a></li>
<li class="chapter" data-level="29.8.2" data-path="visual-search.html"><a href="visual-search.html#visual-search-scanning-local-feature-analysis"><i class="fa fa-check"></i><b>29.8.2</b> Scanning / local feature analysis</a></li>
</ul></li>
<li class="chapter" data-level="29.9" data-path="visual-search.html"><a href="visual-search.html#visual-search-Kundel-Nodine-model-CAD"><i class="fa fa-check"></i><b>29.9</b> Kundel-Nodine model and CAD algorithms</a></li>
<li class="chapter" data-level="29.10" data-path="visual-search.html"><a href="visual-search.html#visual-search-eye-tracking-froc"><i class="fa fa-check"></i><b>29.10</b> Simultaneously acquired eye-tracking and FROC data</a><ul>
<li class="chapter" data-level="29.10.1" data-path="visual-search.html"><a href="visual-search.html#visual-search-eye-tracking-froc-data"><i class="fa fa-check"></i><b>29.10.1</b> FROC and Eye-Tracking Data Collection</a></li>
<li class="chapter" data-level="29.10.2" data-path="visual-search.html"><a href="visual-search.html#visual-search-measures-visual-attention"><i class="fa fa-check"></i><b>29.10.2</b> Measures of Visual Attention</a></li>
<li class="chapter" data-level="29.10.3" data-path="visual-search.html"><a href="visual-search.html#visual-search-generalized-ratings"><i class="fa fa-check"></i><b>29.10.3</b> Generalized ratings</a></li>
</ul></li>
<li class="chapter" data-level="29.11" data-path="visual-search.html"><a href="visual-search.html#visual-search-discussion-summary"><i class="fa fa-check"></i><b>29.11</b> Discussion / Summary</a></li>
<li class="chapter" data-level="29.12" data-path="visual-search.html"><a href="visual-search.html#visual-search-references"><i class="fa fa-check"></i><b>29.12</b> References</a></li>
</ul></li>
<li class="chapter" data-level="30" data-path="rsm.html"><a href="rsm.html"><i class="fa fa-check"></i><b>30</b> The radiological search model</a><ul>
<li class="chapter" data-level="30.1" data-path="rsm.html"><a href="rsm.html#rsm-how-much-finished"><i class="fa fa-check"></i><b>30.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="30.2" data-path="rsm.html"><a href="rsm.html#rsm-intro"><i class="fa fa-check"></i><b>30.2</b> Introduction</a></li>
<li class="chapter" data-level="30.3" data-path="rsm.html"><a href="rsm.html#rsm-details"><i class="fa fa-check"></i><b>30.3</b> The radiological search model</a></li>
<li class="chapter" data-level="30.4" data-path="rsm.html"><a href="rsm.html#rsm-assumptions"><i class="fa fa-check"></i><b>30.4</b> RSM assumptions</a></li>
<li class="chapter" data-level="30.5" data-path="rsm.html"><a href="rsm.html#rsm-summary"><i class="fa fa-check"></i><b>30.5</b> Summary of RSM</a></li>
<li class="chapter" data-level="30.6" data-path="rsm.html"><a href="rsm.html#rsm-parameter-interpretations"><i class="fa fa-check"></i><b>30.6</b> Physical interpretation of RSM parameters</a><ul>
<li class="chapter" data-level="30.6.1" data-path="rsm.html"><a href="rsm.html#rsm-mu-parameter"><i class="fa fa-check"></i><b>30.6.1</b> The <span class="math inline">\(\mu\)</span> parameter</a></li>
<li class="chapter" data-level="30.6.2" data-path="rsm.html"><a href="rsm.html#rsm-summary-lambda-prime-parameter"><i class="fa fa-check"></i><b>30.6.2</b> The <span class="math inline">\(\lambda&#39;\)</span> parameter</a></li>
<li class="chapter" data-level="30.6.3" data-path="rsm.html"><a href="rsm.html#rsm-summary-nu-parameter"><i class="fa fa-check"></i><b>30.6.3</b> The <span class="math inline">\(\nu&#39;\)</span> parameter</a></li>
</ul></li>
<li class="chapter" data-level="30.7" data-path="rsm.html"><a href="rsm.html#rsm-re-parameterization"><i class="fa fa-check"></i><b>30.7</b> Model re-parameterization</a></li>
<li class="chapter" data-level="30.8" data-path="rsm.html"><a href="rsm.html#rsm-discussion-summary"><i class="fa fa-check"></i><b>30.8</b> Discussion / Summary</a></li>
<li class="chapter" data-level="30.9" data-path="rsm.html"><a href="rsm.html#rsm-references"><i class="fa fa-check"></i><b>30.9</b> References</a></li>
</ul></li>
<li class="chapter" data-level="31" data-path="rsm-predictions.html"><a href="rsm-predictions.html"><i class="fa fa-check"></i><b>31</b> Radiological search model predictions</a><ul>
<li class="chapter" data-level="31.1" data-path="rsm-predictions.html"><a href="rsm-predictions.html#rsm-predictions-how-much-finished"><i class="fa fa-check"></i><b>31.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="31.2" data-path="rsm-predictions.html"><a href="rsm-predictions.html#rsm-predictions-intro"><i class="fa fa-check"></i><b>31.2</b> Introduction</a></li>
<li class="chapter" data-level="31.3" data-path="rsm-predictions.html"><a href="rsm-predictions.html#rsm-predictions-details-inferred-roc"><i class="fa fa-check"></i><b>31.3</b> Inferred integer ROC ratings</a><ul>
<li class="chapter" data-level="31.3.1" data-path="rsm-predictions.html"><a href="rsm-predictions.html#rsm-predictions-details-inferred-roc-comments"><i class="fa fa-check"></i><b>31.3.1</b> Comments</a></li>
</ul></li>
<li class="chapter" data-level="31.4" data-path="rsm-predictions.html"><a href="rsm-predictions.html#rsm-predictions-constrained-end-point"><i class="fa fa-check"></i><b>31.4</b> Constrained end-point property</a><ul>
<li class="chapter" data-level="31.4.1" data-path="rsm-predictions.html"><a href="rsm-predictions.html#rsm-predictions-constrained-end-point-abscissa"><i class="fa fa-check"></i><b>31.4.1</b> The abscissa of the ROC end-point</a></li>
<li class="chapter" data-level="31.4.2" data-path="rsm-predictions.html"><a href="rsm-predictions.html#rsm-predictions-constrained-end-point-ordinate"><i class="fa fa-check"></i><b>31.4.2</b> The ordinate of the ROC end-point</a></li>
<li class="chapter" data-level="31.4.3" data-path="rsm-predictions.html"><a href="rsm-predictions.html#rsm-predictions-variable-number-lesions"><i class="fa fa-check"></i><b>31.4.3</b> Variable number of lesions per case</a></li>
</ul></li>
<li class="chapter" data-level="31.5" data-path="rsm-predictions.html"><a href="rsm-predictions.html#rsm-predictions-roc-curve"><i class="fa fa-check"></i><b>31.5</b> The RSM-predicted ROC curve</a><ul>
<li class="chapter" data-level="31.5.1" data-path="rsm-predictions.html"><a href="rsm-predictions.html#rsm-predictions-roc-curve-fpf"><i class="fa fa-check"></i><b>31.5.1</b> Derivation of FPF</a></li>
<li class="chapter" data-level="31.5.2" data-path="rsm-predictions.html"><a href="rsm-predictions.html#rsm-predictions-roc-curve-tpf"><i class="fa fa-check"></i><b>31.5.2</b> Derivation of TPF</a></li>
<li class="chapter" data-level="31.5.3" data-path="rsm-predictions.html"><a href="rsm-predictions.html#rsm-predictions-roc-curve-varying-lesions"><i class="fa fa-check"></i><b>31.5.3</b> Extension to varying numbers of lesions</a></li>
<li class="chapter" data-level="31.5.4" data-path="rsm-predictions.html"><a href="rsm-predictions.html#rsm-predictions-roc-curve-proper"><i class="fa fa-check"></i><b>31.5.4</b> “Proper” property of the RSM-predicted ROC curve</a></li>
<li class="chapter" data-level="31.5.5" data-path="rsm-predictions.html"><a href="rsm-predictions.html#rsm-predictions-roc-curve-pdfs"><i class="fa fa-check"></i><b>31.5.5</b> The pdfs for the ROC decision variable</a></li>
<li class="chapter" data-level="31.5.6" data-path="rsm-predictions.html"><a href="rsm-predictions.html#rsm-predictions-roc-curve-aucs"><i class="fa fa-check"></i><b>31.5.6</b> RSM-predicted ROC-AUC and AFROC-AUC</a></li>
<li class="chapter" data-level="31.5.7" data-path="rsm-predictions.html"><a href="rsm-predictions.html#rsm-predictions-roc-curve-pdfs2"><i class="fa fa-check"></i><b>31.5.7</b> RSM-predicted ROC and pdf curves</a></li>
</ul></li>
<li class="chapter" data-level="31.6" data-path="rsm-predictions.html"><a href="rsm-predictions.html#rsm-predictions-froc-curve"><i class="fa fa-check"></i><b>31.6</b> The RSM-predicted FROC curve</a></li>
<li class="chapter" data-level="31.7" data-path="rsm-predictions.html"><a href="rsm-predictions.html#rsm-predictions-afroc-curve"><i class="fa fa-check"></i><b>31.7</b> The RSM-predicted AFROC curve</a><ul>
<li class="chapter" data-level="31.7.1" data-path="rsm-predictions.html"><a href="rsm-predictions.html#rsm-predictions-afroc-chance"><i class="fa fa-check"></i><b>31.7.1</b> Chance level performance on AFROC</a></li>
<li class="chapter" data-level="31.7.2" data-path="rsm-predictions.html"><a href="rsm-predictions.html#rsm-predictions-no-marks"><i class="fa fa-check"></i><b>31.7.2</b> The reader who does not yield any marks</a></li>
</ul></li>
<li class="chapter" data-level="31.8" data-path="rsm-predictions.html"><a href="rsm-predictions.html#rsm-predictions-discussion-summary"><i class="fa fa-check"></i><b>31.8</b> Discussion / Summary</a><ul>
<li class="chapter" data-level="31.8.1" data-path="rsm-predictions.html"><a href="rsm-predictions.html#the-wagner-review"><i class="fa fa-check"></i><b>31.8.1</b> The Wagner review</a></li>
</ul></li>
<li class="chapter" data-level="31.9" data-path="rsm-predictions.html"><a href="rsm-predictions.html#rsm-predictions-references"><i class="fa fa-check"></i><b>31.9</b> References</a></li>
</ul></li>
<li class="chapter" data-level="32" data-path="rsm-search-classification.html"><a href="rsm-search-classification.html"><i class="fa fa-check"></i><b>32</b> Search and classification performances</a><ul>
<li class="chapter" data-level="32.1" data-path="rsm-search-classification.html"><a href="rsm-search-classification.html#rsm-search-classification-how-much-finished"><i class="fa fa-check"></i><b>32.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="32.2" data-path="rsm-search-classification.html"><a href="rsm-search-classification.html#rsm-search-classification-intro"><i class="fa fa-check"></i><b>32.2</b> Introduction</a></li>
<li class="chapter" data-level="32.3" data-path="rsm-search-classification.html"><a href="rsm-search-classification.html#quantifying-search-performance-rsm-search-search-performance"><i class="fa fa-check"></i><b>32.3</b> Quantifying search performance #rsm-search-search-performance}</a></li>
<li class="chapter" data-level="32.4" data-path="rsm-search-classification.html"><a href="rsm-search-classification.html#rsm-search-classification-performance"><i class="fa fa-check"></i><b>32.4</b> Quantifying classification performance</a><ul>
<li class="chapter" data-level="32.4.1" data-path="rsm-search-classification.html"><a href="rsm-search-classification.html#rsm-search-classification-search-classification-2afc-lke"><i class="fa fa-check"></i><b>32.4.1</b> Lesion-classification performance and the 2AFC LKE task</a></li>
<li class="chapter" data-level="32.4.2" data-path="rsm-search-classification.html"><a href="rsm-search-classification.html#rsm-search-classification-search-classification-significance"><i class="fa fa-check"></i><b>32.4.2</b> Significance of measuring search and lesion-classification performance</a></li>
</ul></li>
<li class="chapter" data-level="32.5" data-path="rsm-search-classification.html"><a href="rsm-search-classification.html#rsm-search-classification-discussion-summary"><i class="fa fa-check"></i><b>32.5</b> Discussion / Summary</a><ul>
<li class="chapter" data-level="32.5.1" data-path="rsm-search-classification.html"><a href="rsm-search-classification.html#the-wagner-review-1"><i class="fa fa-check"></i><b>32.5.1</b> The Wagner review</a></li>
</ul></li>
<li class="chapter" data-level="32.6" data-path="rsm-search-classification.html"><a href="rsm-search-classification.html#rsm-search-classification-references"><i class="fa fa-check"></i><b>32.6</b> References</a></li>
</ul></li>
<li class="chapter" data-level="33" data-path="rsm-goodbye-froc.html"><a href="rsm-goodbye-froc.html"><i class="fa fa-check"></i><b>33</b> The FROC should not be used to measure performance</a><ul>
<li class="chapter" data-level="33.1" data-path="rsm-goodbye-froc.html"><a href="rsm-goodbye-froc.html#rsm-goodbye-how-much-finished"><i class="fa fa-check"></i><b>33.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="33.2" data-path="rsm-goodbye-froc.html"><a href="rsm-goodbye-froc.html#rsm-goodbye-froc-intro"><i class="fa fa-check"></i><b>33.2</b> Introduction</a></li>
<li class="chapter" data-level="33.3" data-path="rsm-goodbye-froc.html"><a href="rsm-goodbye-froc.html#rsm-goodbye-froc-froc-poor"><i class="fa fa-check"></i><b>33.3</b> The FROC curve is a poor descriptor of search performance</a><ul>
<li class="chapter" data-level="33.3.1" data-path="rsm-goodbye-froc.html"><a href="rsm-goodbye-froc.html#clinically-relevant-portion-of-an-operating-characteristic-rsm-goodbye-froc-clinically-relevant"><i class="fa fa-check"></i><b>33.3.1</b> Clinically relevant portion of an operating characteristic #rsm-goodbye-froc-clinically-relevant}</a></li>
</ul></li>
<li class="chapter" data-level="33.4" data-path="rsm-goodbye-froc.html"><a href="rsm-goodbye-froc.html#rsm-goodbye-froc-discussion-summary"><i class="fa fa-check"></i><b>33.4</b> Discussion / Summary</a><ul>
<li class="chapter" data-level="33.4.1" data-path="rsm-goodbye-froc.html"><a href="rsm-goodbye-froc.html#the-wagner-review-2"><i class="fa fa-check"></i><b>33.4.1</b> The Wagner review</a></li>
</ul></li>
<li class="chapter" data-level="33.5" data-path="rsm-goodbye-froc.html"><a href="rsm-goodbye-froc.html#rsm-goodbye-froc-references"><i class="fa fa-check"></i><b>33.5</b> References</a></li>
</ul></li>
<li class="chapter" data-level="34" data-path="analyzing-froc-data.html"><a href="analyzing-froc-data.html"><i class="fa fa-check"></i><b>34</b> Analyzing FROC data</a><ul>
<li class="chapter" data-level="34.1" data-path="analyzing-froc-data.html"><a href="analyzing-froc-data.html#analyzing-froc-data-how-much-finished"><i class="fa fa-check"></i><b>34.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="34.2" data-path="analyzing-froc-data.html"><a href="analyzing-froc-data.html#analyzing-froc-data-intro"><i class="fa fa-check"></i><b>34.2</b> Introduction</a></li>
<li class="chapter" data-level="34.3" data-path="analyzing-froc-data.html"><a href="analyzing-froc-data.html#analyzing-froc-data-example1"><i class="fa fa-check"></i><b>34.3</b> Example 1</a></li>
<li class="chapter" data-level="34.4" data-path="analyzing-froc-data.html"><a href="analyzing-froc-data.html#analyzing-froc-data-plotting"><i class="fa fa-check"></i><b>34.4</b> Plotting wAFROC and ROC curves</a></li>
<li class="chapter" data-level="34.5" data-path="analyzing-froc-data.html"><a href="analyzing-froc-data.html#analyzing-froc-data-reporting"><i class="fa fa-check"></i><b>34.5</b> Reporting an FROC study</a></li>
<li class="chapter" data-level="34.6" data-path="analyzing-froc-data.html"><a href="analyzing-froc-data.html#crossed-treatment-analysis"><i class="fa fa-check"></i><b>34.6</b> Crossed-treatment analysis</a></li>
<li class="chapter" data-level="34.7" data-path="analyzing-froc-data.html"><a href="analyzing-froc-data.html#analyzing-froc-data-rjafroc-history"><i class="fa fa-check"></i><b>34.7</b> Discussion / Summary</a></li>
<li class="chapter" data-level="34.8" data-path="analyzing-froc-data.html"><a href="analyzing-froc-data.html#analyzing-froc-data-references"><i class="fa fa-check"></i><b>34.8</b> References</a></li>
</ul></li>
<li class="chapter" data-level="35" data-path="froc-sample-size.html"><a href="froc-sample-size.html"><i class="fa fa-check"></i><b>35</b> FROC sample size</a><ul>
<li class="chapter" data-level="35.1" data-path="froc-sample-size.html"><a href="froc-sample-size.html#froc-sample-size-how-much-finished"><i class="fa fa-check"></i><b>35.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="35.2" data-path="froc-sample-size.html"><a href="froc-sample-size.html#froc-sample-size-intro"><i class="fa fa-check"></i><b>35.2</b> Introduction</a></li>
<li class="chapter" data-level="35.3" data-path="froc-sample-size.html"><a href="froc-sample-size.html#froc-sample-size-example1"><i class="fa fa-check"></i><b>35.3</b> Example 1</a></li>
<li class="chapter" data-level="35.4" data-path="froc-sample-size.html"><a href="froc-sample-size.html#froc-sample-size-plotting"><i class="fa fa-check"></i><b>35.4</b> Plotting wAFROC and ROC curves</a></li>
<li class="chapter" data-level="35.5" data-path="froc-sample-size.html"><a href="froc-sample-size.html#froc-sample-size-fitrsmroc-usage-example"><i class="fa fa-check"></i><b>35.5</b> <code>FitRsmROC</code> usage example</a></li>
<li class="chapter" data-level="35.6" data-path="froc-sample-size.html"><a href="froc-sample-size.html#froc-sample-size-discussion-summary"><i class="fa fa-check"></i><b>35.6</b> Discussion / Summary</a></li>
<li class="chapter" data-level="35.7" data-path="froc-sample-size.html"><a href="froc-sample-size.html#froc-sample-size-references"><i class="fa fa-check"></i><b>35.7</b> References</a></li>
</ul></li>
<li class="chapter" data-level="36" data-path="rsm-fitting.html"><a href="rsm-fitting.html"><i class="fa fa-check"></i><b>36</b> RSM fitting</a><ul>
<li class="chapter" data-level="36.1" data-path="rsm-fitting.html"><a href="rsm-fitting.html#rsm-fitting-how-much-finished"><i class="fa fa-check"></i><b>36.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="36.2" data-path="rsm-fitting.html"><a href="rsm-fitting.html#rsm-fitting-intro"><i class="fa fa-check"></i><b>36.2</b> Introduction</a></li>
<li class="chapter" data-level="36.3" data-path="rsm-fitting.html"><a href="rsm-fitting.html#rsm-fitting-froc-likelihood"><i class="fa fa-check"></i><b>36.3</b> FROC likelihood function</a><ul>
<li class="chapter" data-level="36.3.1" data-path="rsm-fitting.html"><a href="rsm-fitting.html#rsm-fitting-froc-nls"><i class="fa fa-check"></i><b>36.3.1</b> Contribution of NLs</a></li>
<li class="chapter" data-level="36.3.2" data-path="rsm-fitting.html"><a href="rsm-fitting.html#rsm-fitting-froc-lls"><i class="fa fa-check"></i><b>36.3.2</b> Contribution of LLs</a></li>
<li class="chapter" data-level="36.3.3" data-path="rsm-fitting.html"><a href="rsm-fitting.html#rsm-fitting-froc-degeneracy"><i class="fa fa-check"></i><b>36.3.3</b> Degeneracy problems</a></li>
</ul></li>
<li class="chapter" data-level="36.4" data-path="rsm-fitting.html"><a href="rsm-fitting.html#rsm-fitting-froc-idca"><i class="fa fa-check"></i><b>36.4</b> IDCA Likelihood function</a></li>
<li class="chapter" data-level="36.5" data-path="rsm-fitting.html"><a href="rsm-fitting.html#rsm-fitting-roc-likelihood"><i class="fa fa-check"></i><b>36.5</b> ROC Likelihood function</a></li>
<li class="chapter" data-level="36.6" data-path="rsm-fitting.html"><a href="rsm-fitting.html#rsm-fitting-fitrsmroc-implementation"><i class="fa fa-check"></i><b>36.6</b> <code>FitRsmROC</code> implementation</a></li>
<li class="chapter" data-level="36.7" data-path="rsm-fitting.html"><a href="rsm-fitting.html#rsm-fitting-fitrsmroc-usage-example"><i class="fa fa-check"></i><b>36.7</b> <code>FitRsmROC</code> usage example</a></li>
<li class="chapter" data-level="36.8" data-path="rsm-fitting.html"><a href="rsm-fitting.html#rsm-fitting-discussion-summary"><i class="fa fa-check"></i><b>36.8</b> Discussion / Summary</a></li>
<li class="chapter" data-level="36.9" data-path="rsm-fitting.html"><a href="rsm-fitting.html#rsm-fitting-references"><i class="fa fa-check"></i><b>36.9</b> References</a></li>
</ul></li>
<li class="chapter" data-level="37" data-path="rsm-3-fits.html"><a href="rsm-3-fits.html"><i class="fa fa-check"></i><b>37</b> Three proper ROC fits</a><ul>
<li class="chapter" data-level="37.1" data-path="rsm-3-fits.html"><a href="rsm-3-fits.html#rsm-3-fits-how-much-finished"><i class="fa fa-check"></i><b>37.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="37.2" data-path="rsm-3-fits.html"><a href="rsm-3-fits.html#rsm-3-fits-intro"><i class="fa fa-check"></i><b>37.2</b> Introduction</a></li>
<li class="chapter" data-level="37.3" data-path="rsm-3-fits.html"><a href="rsm-3-fits.html#rsm-3-fits-applications"><i class="fa fa-check"></i><b>37.3</b> Applications</a><ul>
<li class="chapter" data-level="37.3.1" data-path="rsm-3-fits.html"><a href="rsm-3-fits.html#rsm-3-fits-two-datasets"><i class="fa fa-check"></i><b>37.3.1</b> Application to two datasets</a></li>
</ul></li>
<li class="chapter" data-level="37.4" data-path="rsm-3-fits.html"><a href="rsm-3-fits.html#rsm-3-fits-composite-plots"><i class="fa fa-check"></i><b>37.4</b> Displaying composite plots</a></li>
<li class="chapter" data-level="37.5" data-path="rsm-3-fits.html"><a href="rsm-3-fits.html#rsm-3-fits-rsm-parameters"><i class="fa fa-check"></i><b>37.5</b> Displaying RSM parameters</a></li>
<li class="chapter" data-level="37.6" data-path="rsm-3-fits.html"><a href="rsm-3-fits.html#rsm-3-fits-cbm-parameters"><i class="fa fa-check"></i><b>37.6</b> Displaying CBM parameters</a></li>
<li class="chapter" data-level="37.7" data-path="rsm-3-fits.html"><a href="rsm-3-fits.html#rsm-3-fits-proproc-parameters"><i class="fa fa-check"></i><b>37.7</b> Displaying PROPROC parameters</a></li>
<li class="chapter" data-level="37.8" data-path="rsm-3-fits.html"><a href="rsm-3-fits.html#rsm-3-fits-overview"><i class="fa fa-check"></i><b>37.8</b> Overview of findings</a><ul>
<li class="chapter" data-level="37.8.1" data-path="rsm-3-fits.html"><a href="rsm-3-fits.html#rsm-3-fits-slopes"><i class="fa fa-check"></i><b>37.8.1</b> Slopes</a></li>
<li class="chapter" data-level="37.8.2" data-path="rsm-3-fits.html"><a href="rsm-3-fits.html#rsm-3-fits-confidence-intervals"><i class="fa fa-check"></i><b>37.8.2</b> Confidence intervals</a></li>
<li class="chapter" data-level="37.8.3" data-path="rsm-3-fits.html"><a href="rsm-3-fits.html#rsm-3-fits-slopes-confidence-intervals-summary"><i class="fa fa-check"></i><b>37.8.3</b> Summary of slopes and confidence intervals</a></li>
</ul></li>
<li class="chapter" data-level="37.9" data-path="rsm-3-fits.html"><a href="rsm-3-fits.html#rsm-3-fits-discussion-summary"><i class="fa fa-check"></i><b>37.9</b> Discussion / Summary</a></li>
<li class="chapter" data-level="37.10" data-path="rsm-3-fits.html"><a href="rsm-3-fits.html#rsm-3-fits-appendices"><i class="fa fa-check"></i><b>37.10</b> Appendices</a></li>
<li class="chapter" data-level="37.11" data-path="rsm-3-fits.html"><a href="rsm-3-fits.html#rsm-3-fits-14-datasets"><i class="fa fa-check"></i><b>37.11</b> Datasets</a></li>
<li class="chapter" data-level="37.12" data-path="rsm-3-fits.html"><a href="rsm-3-fits.html#rsm-3-fits-one-dataset-proproc"><i class="fa fa-check"></i><b>37.12</b> Location of PROPROC files</a></li>
<li class="chapter" data-level="37.13" data-path="rsm-3-fits.html"><a href="rsm-3-fits.html#rsm-3-fits-pre-analyzed-results"><i class="fa fa-check"></i><b>37.13</b> Location of pre-analyzed results</a></li>
<li class="chapter" data-level="37.14" data-path="rsm-3-fits.html"><a href="rsm-3-fits.html#rsm-3-fits-representative-plots-van-dyke"><i class="fa fa-check"></i><b>37.14</b> Plots for Van Dyke dataset</a></li>
<li class="chapter" data-level="37.15" data-path="rsm-3-fits.html"><a href="rsm-3-fits.html#rsm-3-fits-references"><i class="fa fa-check"></i><b>37.15</b> References</a></li>
</ul></li>
<li class="part"><span><b>CAD</b></span></li>
<li class="chapter" data-level="38" data-path="standalone-cad-radiologists.html"><a href="standalone-cad-radiologists.html"><i class="fa fa-check"></i><b>38</b> Standalone CAD vs. Radiologists</a><ul>
<li class="chapter" data-level="38.1" data-path="standalone-cad-radiologists.html"><a href="standalone-cad-radiologists.html#standalone-cad-radiologists-how-much-finished"><i class="fa fa-check"></i><b>38.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="38.2" data-path="standalone-cad-radiologists.html"><a href="standalone-cad-radiologists.html#standalone-cad-radiologists-abstract"><i class="fa fa-check"></i><b>38.2</b> Abstract</a></li>
<li class="chapter" data-level="38.3" data-path="standalone-cad-radiologists.html"><a href="standalone-cad-radiologists.html#standalone-cad-radiologists-ker-words"><i class="fa fa-check"></i><b>38.3</b> Keywords</a></li>
<li class="chapter" data-level="38.4" data-path="standalone-cad-radiologists.html"><a href="standalone-cad-radiologists.html#standalone-cad-radiologists-introduction"><i class="fa fa-check"></i><b>38.4</b> Introduction</a></li>
<li class="chapter" data-level="38.5" data-path="standalone-cad-radiologists.html"><a href="standalone-cad-radiologists.html#standalone-cad-radiologists-methods"><i class="fa fa-check"></i><b>38.5</b> Methods</a><ul>
<li class="chapter" data-level="38.5.1" data-path="standalone-cad-radiologists.html"><a href="standalone-cad-radiologists.html#standalone-cad-radiologists-two-previous-studies"><i class="fa fa-check"></i><b>38.5.1</b> Studies assessing performance of CAD vs. radiologists</a></li>
<li class="chapter" data-level="38.5.2" data-path="standalone-cad-radiologists.html"><a href="standalone-cad-radiologists.html#the-1t-rrfc-analysis-model"><i class="fa fa-check"></i><b>38.5.2</b> The 1T-RRFC analysis model</a></li>
<li class="chapter" data-level="38.5.3" data-path="standalone-cad-radiologists.html"><a href="standalone-cad-radiologists.html#standalone-cad-radiologists-2TRRRC-anlaysis"><i class="fa fa-check"></i><b>38.5.3</b> The 2T-RRRC analysis model</a></li>
<li class="chapter" data-level="38.5.4" data-path="standalone-cad-radiologists.html"><a href="standalone-cad-radiologists.html#standalone-cad-radiologists-1TRRRC-anlaysis"><i class="fa fa-check"></i><b>38.5.4</b> The 1T-RRRC analysis model</a></li>
</ul></li>
<li class="chapter" data-level="38.6" data-path="standalone-cad-radiologists.html"><a href="standalone-cad-radiologists.html#standalone-cad-radiologists-computational-details"><i class="fa fa-check"></i><b>38.6</b> Software implementation</a></li>
<li class="chapter" data-level="38.7" data-path="standalone-cad-radiologists.html"><a href="standalone-cad-radiologists.html#standalone-cad-radiologists-results"><i class="fa fa-check"></i><b>38.7</b> Results</a></li>
<li class="chapter" data-level="38.8" data-path="standalone-cad-radiologists.html"><a href="standalone-cad-radiologists.html#standalone-cad-radiologists-discussion"><i class="fa fa-check"></i><b>38.8</b> Discussion</a></li>
<li class="chapter" data-level="38.9" data-path="standalone-cad-radiologists.html"><a href="standalone-cad-radiologists.html#standalone-cad-radiologists-appendix"><i class="fa fa-check"></i><b>38.9</b> Appendix</a><ul>
<li class="chapter" data-level="38.9.1" data-path="standalone-cad-radiologists.html"><a href="standalone-cad-radiologists.html#example-1-1"><i class="fa fa-check"></i><b>38.9.1</b> Example 1</a></li>
<li class="chapter" data-level="38.9.2" data-path="standalone-cad-radiologists.html"><a href="standalone-cad-radiologists.html#example-2"><i class="fa fa-check"></i><b>38.9.2</b> Example 2</a></li>
<li class="chapter" data-level="38.9.3" data-path="standalone-cad-radiologists.html"><a href="standalone-cad-radiologists.html#example-3"><i class="fa fa-check"></i><b>38.9.3</b> Example 3</a></li>
</ul></li>
<li class="chapter" data-level="38.10" data-path="standalone-cad-radiologists.html"><a href="standalone-cad-radiologists.html#standalone-cad-radiologists-references"><i class="fa fa-check"></i><b>38.10</b> References</a></li>
</ul></li>
<li class="chapter" data-level="39" data-path="optim-op-point.html"><a href="optim-op-point.html"><i class="fa fa-check"></i><b>39</b> Optimal operating point on FROC</a><ul>
<li class="chapter" data-level="39.1" data-path="optim-op-point.html"><a href="optim-op-point.html#optim-op-point-how-much-finished"><i class="fa fa-check"></i><b>39.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="39.2" data-path="optim-op-point.html"><a href="optim-op-point.html#optim-op-point-intro"><i class="fa fa-check"></i><b>39.2</b> Introduction</a></li>
<li class="chapter" data-level="39.3" data-path="optim-op-point.html"><a href="optim-op-point.html#optim-op-point-methods"><i class="fa fa-check"></i><b>39.3</b> Methods</a><ul>
<li class="chapter" data-level="39.3.1" data-path="optim-op-point.html"><a href="optim-op-point.html#functions-to-be-maximized"><i class="fa fa-check"></i><b>39.3.1</b> Functions to be maximized</a></li>
<li class="chapter" data-level="39.3.2" data-path="optim-op-point.html"><a href="optim-op-point.html#optim-op-point-vary-lambda"><i class="fa fa-check"></i><b>39.3.2</b> Vary lambda</a></li>
<li class="chapter" data-level="39.3.3" data-path="optim-op-point.html"><a href="optim-op-point.html#optim-op-point-vary-nu"><i class="fa fa-check"></i><b>39.3.3</b> Vary nu</a></li>
<li class="chapter" data-level="39.3.4" data-path="optim-op-point.html"><a href="optim-op-point.html#optim-op-point-vary-mu"><i class="fa fa-check"></i><b>39.3.4</b> Vary mu</a></li>
</ul></li>
<li class="chapter" data-level="39.4" data-path="optim-op-point.html"><a href="optim-op-point.html#optim-op-point-how-to-use-method"><i class="fa fa-check"></i><b>39.4</b> Using the method</a></li>
<li class="chapter" data-level="39.5" data-path="optim-op-point.html"><a href="optim-op-point.html#optim-op-point-application"><i class="fa fa-check"></i><b>39.5</b> An application</a></li>
<li class="chapter" data-level="39.6" data-path="optim-op-point.html"><a href="optim-op-point.html#optim-op-point-discussion"><i class="fa fa-check"></i><b>39.6</b> Discussion</a></li>
<li class="chapter" data-level="39.7" data-path="optim-op-point.html"><a href="optim-op-point.html#optim-op-point-references"><i class="fa fa-check"></i><b>39.7</b> References</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>REFERENCES</a></li>
<li class="chapter" data-level="40" data-path="classification-tasks.html"><a href="classification-tasks.html"><i class="fa fa-check"></i><b>40</b> Localization - classification tasks</a><ul>
<li class="chapter" data-level="40.1" data-path="classification-tasks.html"><a href="classification-tasks.html#classification-tasks-how-much-finished"><i class="fa fa-check"></i><b>40.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="40.2" data-path="classification-tasks.html"><a href="classification-tasks.html#classification-tasks-intro"><i class="fa fa-check"></i><b>40.2</b> Introduction</a></li>
<li class="chapter" data-level="40.3" data-path="classification-tasks.html"><a href="classification-tasks.html#classification-tasks-abbreviations"><i class="fa fa-check"></i><b>40.3</b> Abbreviations</a></li>
<li class="chapter" data-level="40.4" data-path="classification-tasks.html"><a href="classification-tasks.html#classification-tasks-basic-idea"><i class="fa fa-check"></i><b>40.4</b> History and basic idea</a></li>
<li class="chapter" data-level="40.5" data-path="classification-tasks.html"><a href="classification-tasks.html#classification-tasks-example1"><i class="fa fa-check"></i><b>40.5</b> First example, File1.xlsx</a><ul>
<li class="chapter" data-level="40.5.1" data-path="classification-tasks.html"><a href="classification-tasks.html#classification-tasks-example1-truth"><i class="fa fa-check"></i><b>40.5.1</b> <code>Truth</code> sheet</a></li>
<li class="chapter" data-level="40.5.2" data-path="classification-tasks.html"><a href="classification-tasks.html#classification-tasks-example1-tp"><i class="fa fa-check"></i><b>40.5.2</b> <code>TP</code> sheet</a></li>
<li class="chapter" data-level="40.5.3" data-path="classification-tasks.html"><a href="classification-tasks.html#classification-tasks-example1-fp"><i class="fa fa-check"></i><b>40.5.3</b> <code>FP</code> sheet</a></li>
<li class="chapter" data-level="40.5.4" data-path="classification-tasks.html"><a href="classification-tasks.html#the-two-ratings-arrays"><i class="fa fa-check"></i><b>40.5.4</b> The two ratings arrays</a></li>
</ul></li>
<li class="chapter" data-level="40.6" data-path="classification-tasks.html"><a href="classification-tasks.html#classification-tasks-example2"><i class="fa fa-check"></i><b>40.6</b> Second example, File2.xlsx</a></li>
<li class="chapter" data-level="40.7" data-path="classification-tasks.html"><a href="classification-tasks.html#classification-tasks-example3"><i class="fa fa-check"></i><b>40.7</b> Third example, File3.xlsx</a></li>
<li class="chapter" data-level="40.8" data-path="classification-tasks.html"><a href="classification-tasks.html#classification-tasks-example4"><i class="fa fa-check"></i><b>40.8</b> Fourth example, File4.xlsx</a></li>
<li class="chapter" data-level="40.9" data-path="classification-tasks.html"><a href="classification-tasks.html#classification-tasks-example5"><i class="fa fa-check"></i><b>40.9</b> Fifth example, File5.xlsx</a></li>
<li class="chapter" data-level="40.10" data-path="classification-tasks.html"><a href="classification-tasks.html#classification-tasks-precautions"><i class="fa fa-check"></i><b>40.10</b> Precautions</a></li>
<li class="chapter" data-level="40.11" data-path="classification-tasks.html"><a href="classification-tasks.html#classification-tasks-discussion"><i class="fa fa-check"></i><b>40.11</b> Discussion</a></li>
<li class="chapter" data-level="40.12" data-path="classification-tasks.html"><a href="classification-tasks.html#classification-tasks--references"><i class="fa fa-check"></i><b>40.12</b> References</a></li>
</ul></li>
<li class="chapter" data-level="41" data-path="SplitPlotChapter.html"><a href="SplitPlotChapter.html"><i class="fa fa-check"></i><b>41</b> Split Plot Study Design</a><ul>
<li class="chapter" data-level="41.1" data-path="SplitPlotChapter.html"><a href="SplitPlotChapter.html#SplitPlotChapter-how-much-finished"><i class="fa fa-check"></i><b>41.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="41.2" data-path="SplitPlotChapter.html"><a href="SplitPlotChapter.html#mean-square-rt"><i class="fa fa-check"></i><b>41.2</b> Mean Square R(T)</a></li>
<li class="chapter" data-level="41.3" data-path="SplitPlotChapter.html"><a href="SplitPlotChapter.html#SplitPlotChapter-references"><i class="fa fa-check"></i><b>41.3</b> References</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">The RJafroc Book</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="froc-meanings" class="section level1">
<h1><span class="header-section-number">Chapter 28</span> Meanings of FROC figures of merit</h1>
<div id="froc-meanings-how-much-finished" class="section level2">
<h2><span class="header-section-number">28.1</span> TBA How much finished</h2>
<p>50%</p>
</div>
<div id="froc-meanings-intro" class="section level2">
<h2><span class="header-section-number">28.2</span> Introduction</h2>
<p>Chapter <a href="froc-empirical.html#froc-empirical">25</a> focused on empirical plots possible with FROC data, for example, the FROC, AFROC, wAFROC and inferred ROC plots. Expressions were given for computing <em>operating points</em> for each plot from z-samples. Because of the ambiguity in ordering the two values associated with each operating points (e.g., sensitivity-specificity pairs in ROC plots), operating points should not be used as figures of merit. Rather one should use <em>area measures</em> derived from operating characteristics. This chapter is devoted to a number of such measures for FROC data.</p>
<p>A generic empirical area under a plot is denoted <span class="math inline">\(A_{\text{oc}}\)</span>, where the “oc” subscript denotes the applicable operating characteristic. For example, the area under the empirical wAFROC is denoted <span class="math inline">\(A_{\text{wAFROC}}\)</span>. Calculating areas from operating points using planimetry or geometry is tedious at best. <em>Needed are formulas for calculating them directly from ratings.</em> In this sense this chapter is analogous to Chapter <a href="empirical-auc.html#empirical-auc">12</a> where it was shown that the area under the empirical ROC plot <span class="math inline">\(A_{\text{ROC}}\)</span> equaled the Wilcoxon statistic calculated directly from the ratings, i.e., the Bamber theorem <span class="citation">(Bamber <a href="#ref-RN2174" role="doc-biblioref">1975</a>)</span>.</p>
<p>I make a distinction between <em>empirical AUC under a plot</em>, i.e., an area measure, and a <em>FOM-statistic</em>, generically denoted <span class="math inline">\(\theta\)</span>, that can be computed directly from the ratings. While any function of the ratings is a possible FOM-statistic, whether it is useful depends upon whether it can be related to the area under an operating characteristic. This chapter derives formulas for FOM-statistics <span class="math inline">\(\theta_{\text{oc}}\)</span>, which yield the same values as the areas <span class="math inline">\(A_{\text{oc}}\)</span> under the corresponding empirical operating characteristics. The meanings of these FOM-statistics are discussed <span class="citation">(Chakraborty and Zhai <a href="#ref-RN2484" role="doc-biblioref">2016</a>)</span>.</p>
<p>Here is the organization of the chapter.</p>
<ul>
<li><p>Expressions for the empirical AFROC FOM-statistic <span class="math inline">\(\theta_{\text{AFROC}}\)</span> and the empirical weighted-AFROC FOM-statistic <span class="math inline">\(\theta_{\text{wAFROC}}\)</span> are presented and their limiting values for chance-level and perfect performances are explored.</p></li>
<li><p>Two important theorems are stated, whose proofs are in [TBA Online Appendix 14.A].</p></li>
<li><p>The first theorem proves the equality between the empirical wAFROC FOM-statistic <span class="math inline">\(\theta_{\text{wAFROC}}\)</span> and the area <span class="math inline">\(A_{\text{wAFROC}}\)</span> under the empirical wAFROC plot. [A similar equality applies to the empirical AFROC FOM-statistic <span class="math inline">\(\theta_{\text{AFROC}}\)</span> and the area <span class="math inline">\(A_{\text{AFROC}}\)</span> under the empirical AFROC plot.]</p></li>
<li><p>The second theorem derives an expression for the area under the straight-line extension of the wAFROC from the observed end-point to (1,1), and explains why it is essential to include this area.</p></li>
<li><p>A small simulated-dataset is used to illustrate how NL and LL ratings and lesion weights determine the wAFROC empirical plot.</p></li>
<li><p>It demonstrates that the wAFROC gives equal importance to all diseased cases, a desirable statistical characteristic.</p></li>
<li><p>Corresponding results, but ignoring the weights, show that the AFROC gives excessive importance to cases with more lesions.</p></li>
<li><p>A physical interpretation of the AUC or FOM-statistics is given. It shows explicitly how the ratings comparisons implied in FOM-statistic properly credit and penalize the observer for correct and incorrect decisions, respectively. The probabilistic meanings of the AFROC and wAFROC AUCs are given.</p></li>
<li><p>Detailed derivations of FOM-statistics, applicable to the areas under the empirical FROC plot, the AFROC1 and wAFROC1 plots are not given. Instead, the results for all plots are summarized in [TBA Online Appendix 14.C], which shows that the definitions “work”, i.e., the FOM-statistics yield the correct areas as determined by numerical integration of the relevant curves.</p></li>
</ul>
</div>
<div id="froc-meanings-afroc" class="section level2">
<h2><span class="header-section-number">28.3</span> Empirical AFROC FOM-statistic</h2>
<p><span class="math inline">\(A_{\text{AFROC}}\)</span> was defined in <a href="froc-empirical.html#froc-empirical-wAFROC">25.8</a> as the area under the empirical AFROC. The corresponding FOM-statistic <span class="math inline">\(\theta_{\text{AFROC}}\)</span> is defined as follows: one calculates the rating of the highest rated NL mark <span class="math inline">\(\text{FP}_{k_1 1}\)</span> on each non-diseased case <span class="math inline">\(k_1 1\)</span> (or <span class="math inline">\(-\infty\)</span> if the case has no NL marks) and compares it to each LL rating using the kernel function <span class="math inline">\(\psi(x,y)\)</span> defined in Eqn. <a href="empirical-auc.html#eq:empirical-auc-PsiFunction">(12.7)</a>.<a href="#fn24" class="footnote-ref" id="fnref24"><sup>24</sup></a> A summation is performed over all cases and all lesions.</p>
<p>The highest rating <span class="math inline">\(\text{FP}_{k_1 1}\)</span> on non-diseased case <span class="math inline">\(k_1 1\)</span> is defined as:</p>
<span class="math display" id="eq:froc-meanings-R-k1">\[\begin{equation}
\left.
\begin{aligned}
\text{FP}_{k_1 1}  =&amp;  \max_{l_1} \left ( z_{k_1 1 l_1 1} \mid  l_1 \neq \varnothing \right )\\
\text{FP}_{k_1 1}  =&amp;  -\infty\mid l_1 = \varnothing
\end{aligned}
\right \}
\tag{28.1}
\end{equation}\]</span>
<p>If the case has at least one latent NL mark, then <span class="math inline">\(l_1 \neq \varnothing\)</span>, where <span class="math inline">\(\varnothing\)</span> is the null set, and the first definition applies. If the case has no marks, then <span class="math inline">\(l_1 = \varnothing\)</span>, and the second definition applies.</p>
<p>The following equation sums over all cases and lesions:</p>
<span class="math display" id="eq:froc-meanings-theta-afroc">\[\begin{equation}
\begin{aligned} 
\theta_{\text{AFROC}} =&amp; \frac{1}{K_1 L_T}\sum_{k_1=1}^{K_1}\sum_{k_2=1}^{K_2}\sum_{l_2=1}^{L_{k_2}}\psi\left ( \text{FP}_{k_1 1}, z_{k_2 2 l_2 2} \right )\\
\end {aligned}
\tag{28.2}
\end{equation}\]</span>
<p>Since every lesion is assigned a rating, albeit negative infinity for an unmarked lesion, the null set conditioning is not needed.</p>
<div id="upper-limit-for-afroc-fom-statistic" class="section level3">
<h3><span class="header-section-number">28.3.1</span> Upper limit for AFROC FOM-statistic</h3>
<p>The FOM-statistic <span class="math inline">\(\theta_{\text{AFROC}}\)</span> achieves its highest value, unity, if and only if every lesion is rated higher than any mark on non-diseased cases, for then the <span class="math inline">\(\psi\)</span> function always yields unity, and the summations yield :</p>
<span class="math display" id="eq:froc-meanings-theta-afroc-unity">\[\begin{equation}
\left. 
\begin{aligned}
\theta_{\text{AFROC}}=&amp; \frac{1}{K_1 \sum_{k_2=1}^{K_2}L_{k_2}}\sum_{k_1=1}^{K_1}\sum_{k_2=1}^{K_2}\sum_{l_2=1}^{L_{k_2}}  1 \\
= &amp; \frac{1}{K_1 \sum_{k_2=1}^{K_2}L_{k_2}}\sum_{k_1=1}^{K_1}\sum_{k_2=1}^{K_2}L_{k_2} \\
= &amp; \frac{1}{K_1}\sum_{k_1=1}^{K_1}1\\
= &amp; 1
\end{aligned}
\right \}
\tag{28.3}
\end{equation}\]</span>
</div>
<div id="range-of-afroc-fom-statistic" class="section level3">
<h3><span class="header-section-number">28.3.2</span> Range of AFROC FOM-statistic</h3>
<p>If, on the other hand, every lesion is rated lower than every mark on every non-diseased case, the <span class="math inline">\(\psi\)</span> function always yields zero, and the FOM-statistic is zero. Therefore,</p>
<span class="math display" id="eq:froc-meanings-theta-afroc-limits">\[\begin{equation}
0 \leq \theta_{\text{AFROC}} \leq 1
\tag{28.4}
\end{equation}\]</span>
<p>Eqn. <a href="froc-meanings.html#eq:froc-meanings-theta-afroc-limits">(28.4)</a> shows that <span class="math inline">\(\theta_{\text{AFROC}}\)</span> behaves like a probability but its range is <em>twice</em> that of <span class="math inline">\(\theta_{\text{ROC}}\)</span>; recall that <span class="math inline">\(0.5 \leq \theta_{\text{ROC}} \leq 1\)</span> (assuming the observer has equal or better than random performance and the observer does not have the direction of the rating scale accidentally reversed). This has the consequence that treatment related differences between <span class="math inline">\(\theta_{\text{AFROC}}\)</span> (i.e., effect sizes) are larger relative to the corresponding ROC effect sizes (just as temperature differences in the Fahrenheit scale are larger than the same differences expressed in the Celsius scale). This has important implications for FROC sample size estimation, Chapter TBA.</p>
<p>Eqn. <a href="froc-meanings.html#eq:froc-meanings-theta-afroc-limits">(28.4)</a> is one reason why the “chance diagonal” of the AFROC, corresponding to AUC = 0.5, does not, in fact, reflect chance-level performance. An area under the AFROC equal to 0.5 is actually reasonable performance, being smack in the middle of the allowed range. An example of this was given in TBA §13.4.2.2 for the case of an expert radiologist who does not mark any cases.</p>
</div>
</div>
<div id="froc-meanings-wafroc" class="section level2">
<h2><span class="header-section-number">28.4</span> Empirical weighted-AFROC FOM-statistic</h2>
<p>The empirical weighted-AFROC plot and lesion weights were defined in Section <a href="froc-empirical.html#froc-empirical-wAFROC">25.8</a>. The empirical weighted-AFROC FOM-statistic <span class="citation">(Chakraborty and Berbaum <a href="#ref-RN1385" role="doc-biblioref">2004</a>)</span> is defined by including the lesion weights <span class="math inline">\(W_{k_2 l_2}\)</span> inside the summations (but outside the kernel function):</p>
<span class="math display" id="eq:froc-meanings-theta-wafroc">\[\begin{equation}
\begin{aligned} 
\theta_{\text{wAFROC}} =&amp; \frac{1}{K_1 K_2}\sum_{k_1=1}^{K_1}\sum_{k_2=1}^{K_2}\sum_{l_2=1}^{L_{k_2}}W_{k_2 l_2}\psi\left ( \text{FP}_{k_1 1}, z_{k_2 2 l_2 2} \right )\\
\end {aligned}
\tag{28.5}
\end{equation}\]</span>
<p>The weights obey the constraint:</p>
<span class="math display" id="eq:froc-meanings-theta-constraint-weights">\[\begin{equation} 
\sum_{l_2=1}^{L_{k_2}}W_{k_2 l_2} = 1
\tag{28.6}
\end{equation}\]</span>
<p>This ensures, as will be shown shortly, that each diseased case contributes equally to the FOM, regardless of how many lesions are in it. In the special case of one lesion per diseased case, <span class="math inline">\(\theta_{\text{AFROC}}\)</span> and <span class="math inline">\(\theta_{\text{wAFROC}}\)</span> are identical. For equally weighted lesions,</p>
<span class="math display" id="eq:froc-meanings-theta-equal-weights">\[\begin{equation} 
W_{k_2 l_2} = \frac{1}{L_{k_2}}
\tag{28.7}
\end{equation}\]</span>
<p>For example, for equally weighted lesions and a case with three lesions, each weight equals one-third (1/3).<a href="#fn25" class="footnote-ref" id="fnref25"><sup>25</sup></a></p>
</div>
<div id="froc-meanings-two-theorems" class="section level2">
<h2><span class="header-section-number">28.5</span> Two Theorems</h2>
<p>The area <span class="math inline">\(A_{\text{wAFROC}}\)</span> under the wAFROC plot is obtained by summing the areas of individual trapezoids defined by drawing vertical lines from each pair of adjacent operating points to the x-axis. A sample plot is shown Fig. <a href="froc-meanings.html#fig:froc-meanings-theorems">28.1</a>.</p>
<div class="figure"><span style="display:block;" id="fig:froc-meanings-theorems"></span>
<img src="14-froc-meanings-foms-ocs_files/figure-html/froc-meanings-theorems-1.png" alt="An example wAFROC plot; from left to right, the two shaded areas correspond to $A_i$ and  $A_0$, respectively, defined below." width="672" />
<p class="caption">
FIGURE 28.1: An example wAFROC plot; from left to right, the two shaded areas correspond to <span class="math inline">\(A_i\)</span> and <span class="math inline">\(A_0\)</span>, respectively, defined below.
</p>
</div>
<p>The operating point labeled <span class="math inline">\(i\)</span> has coordinates <span class="math inline">\(\left ( \text{FPF}_i, \text{wLLF}_i \right )\)</span> given by Eqn. <a href="froc-empirical.html#eq:froc-empirical-FPF">(25.13)</a> and Eqn. <a href="froc-empirical.html#eq:froc-empirical-wLLFr">(25.21)</a>, respectively, reproduced here for convenience:</p>
<span class="math display" id="eq:froc-meanings-FPF">\[\begin{equation}
FPF_i \equiv FPF \left ( \zeta_i \right ) = \frac{1}{K_1} \sum_{k_1=1}^{K_1} \mathbb{I} \left ( FP_{k_1 1} \geq \zeta_i\right )
\tag{28.8}
\end{equation}\]</span>
<span class="math display" id="eq:froc-meanings-wLLFi">\[\begin{equation}
\text{wLLF}_i \equiv \text{wLLF}_{\zeta_i} = \frac{1}{K_2}\sum_{k_2=1}^{K_2}\sum_{l_2=1}^{L_{k_2}}W_{k_2 l_2} \mathbb{I}\left ( z_{k_2 l_2 2} \geq \zeta_i \right )
\tag{28.9}
\end{equation}\]</span>
<p>TBA Online Appendix 14.A proves the following theorems:</p>
<div id="froc-meanings-two-theorems-1" class="section level3">
<h3><span class="header-section-number">28.5.1</span> Theorem 1</h3>
<p>The area <span class="math inline">\(A_{\text{wAFROC}}\)</span> under the empirical wAFROC plot equals the weighted-AFROC FOM-statistic <span class="math inline">\(\theta_{\text{wAFROC}}\)</span> defined by Eqn. <a href="froc-meanings.html#eq:froc-meanings-theta-wafroc">(28.5)</a>:</p>
<span class="math display" id="eq:froc-meanings-theorem1">\[\begin{equation}
\theta_{\text{wAFROC}} = A_{\text{wAFROC}}
\tag{28.10}
\end{equation}\]</span>
<p>This is the FROC counterpart of Bamber’s Wilcoxon vs. empirical ROC area equivalence theorem <span class="citation">(Bamber <a href="#ref-RN2174" role="doc-biblioref">1975</a>)</span>, derived in Section <a href="empirical-auc.html#empirical-auc-wilcoxon-bamber-theorem">12.7</a>.</p>
</div>
<div id="froc-meanings-two-theorems-2" class="section level3">
<h3><span class="header-section-number">28.5.2</span> Theorem 2</h3>
<p>The area <span class="math inline">\(A_0\)</span> under the straight-line extension of the wAFROC from the observed end-point <span class="math inline">\(\left ( \text{FPF}_1, \text{wLLF}_1 \right )\)</span> to (1,1) is given by:</p>
<span class="math display" id="eq:froc-meanings-A0">\[\begin{equation}
A_0 = \frac{\left ( 1 - \text{FPF}_1 \right )\left ( 1 + \text{wLLF}_1 \right )}{2}
\tag{28.11}
\end{equation}\]</span>
<p>According to Eqn. <a href="froc-meanings.html#eq:froc-meanings-A0">(28.11)</a>, <span class="math inline">\(A_0\)</span> increases as <span class="math inline">\(\text{FPF}_1\)</span> decreases, i.e., as more non-diseased cases are <em>not marked</em> and as <span class="math inline">\(\text{wLLF}_1\)</span> increases, i.e., as more lesions, especially those with greater weights, <em>are marked</em>. Both observations are in keeping with the behavior of a valid FOM.</p>
<ul>
<li>Failure to include the area under the straight-line extension results in not counting the full positive contribution to the FOM of unmarked non-diseased cases and marked lesions.</li>
<li>Each unmarked non-diseased case represents a perfect decision.</li>
<li>For a perfect observer whose operating characteristic is the vertical line from (0,0) to (0,1) followed by the horizontal line from (0,1) to (1,1), <em>the area under the straight-line extension comprises the entire AUC</em>. Excluding it would yield zero AUC for a perfect observer, which is obviously incorrect.</li>
<li>Stated equivalently, for the perfect observer <span class="math inline">\(\text{FPF}_1 = 0\)</span> and <span class="math inline">\(\text{wLLF}_1 = 1\)</span> and then, according to Eqn. <a href="froc-meanings.html#eq:froc-meanings-A0">(28.11)</a>, the area under the straight line extension is <span class="math inline">\(A_0 = 1\)</span>.</li>
</ul>
</div>
</div>
<div id="froc-meanings-numerical-illustrations" class="section level2">
<h2><span class="header-section-number">28.6</span> Numerical illustrations</h2>
<p>The wAFROC and AFROC concepts are perhaps best illustrated with a numerical simulation-based illustration with very few cases.</p>
<p>Parameters of the simulation are <span class="math inline">\(\mu = 2\)</span>, <span class="math inline">\(\lambda = 1\)</span>, <span class="math inline">\(\nu = 1\)</span>, <span class="math inline">\(\zeta_1 = -1\)</span> and <span class="math inline">\(L_{max} = 2\)</span>. One simulates a dataset consisting of <span class="math inline">\(K_1 = 4\)</span> non-diseased cases and <span class="math inline">\(K_2 = 4\)</span> diseased cases. The first two diseased cases have one lesion each, and the remaining two have two lesions each.</p>
<pre><code>#&gt; AFROC AUC =  0.7708333
#&gt; wAFROC AUC =  0.7875</code></pre>
<p>Shown in Fig. <a href="froc-meanings.html#fig:plots-p1-p2">28.2</a> are the AFROC and wAFROC plots with operating points.</p>
<div class="figure"><span style="display:block;" id="fig:plots-p1-p2"></span>
<img src="14-froc-meanings-foms-ocs_files/figure-html/plots-p1-p2-1.png" alt="Left: AFROC plot; Right: corresponding wAFROC plot." width="672" />
<p class="caption">
FIGURE 28.2: Left: AFROC plot; Right: corresponding wAFROC plot.
</p>
</div>
<p>The number of lesions for diseased cases is shown next. Notice that the first two cases have one lesion each and the next two have two lesions each.</p>
<div class="sourceCode" id="cb197"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb197-1"><a href="froc-meanings.html#cb197-1"></a>Lk2</span>
<span id="cb197-2"><a href="froc-meanings.html#cb197-2"></a><span class="co">#&gt; [1] 1 1 2 2</span></span></code></pre></div>
<p>The ratings are shown next.</p>
<div class="sourceCode" id="cb198"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb198-1"><a href="froc-meanings.html#cb198-1"></a>x1 &lt;-<span class="st"> </span><span class="kw">as.data.frame</span>(frocData<span class="op">$</span>ratings<span class="op">$</span>NL[<span class="dv">1</span>,<span class="dv">1</span>,,])</span>
<span id="cb198-2"><a href="froc-meanings.html#cb198-2"></a><span class="kw">colnames</span>(x1) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;location1&quot;</span>, <span class="st">&quot;location2&quot;</span>)</span>
<span id="cb198-3"><a href="froc-meanings.html#cb198-3"></a>x2 &lt;-<span class="st"> </span><span class="kw">as.data.frame</span>(frocData<span class="op">$</span>ratings<span class="op">$</span>LL[<span class="dv">1</span>,<span class="dv">1</span>,,])</span>
<span id="cb198-4"><a href="froc-meanings.html#cb198-4"></a><span class="kw">colnames</span>(x2) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;location1&quot;</span>, <span class="st">&quot;location2&quot;</span>)</span>
<span id="cb198-5"><a href="froc-meanings.html#cb198-5"></a>x1</span>
<span id="cb198-6"><a href="froc-meanings.html#cb198-6"></a><span class="co">#&gt;    location1 location2</span></span>
<span id="cb198-7"><a href="froc-meanings.html#cb198-7"></a><span class="co">#&gt; 1       -Inf      -Inf</span></span>
<span id="cb198-8"><a href="froc-meanings.html#cb198-8"></a><span class="co">#&gt; 2  0.4874291      -Inf</span></span>
<span id="cb198-9"><a href="froc-meanings.html#cb198-9"></a><span class="co">#&gt; 3  0.7383247 0.5757814</span></span>
<span id="cb198-10"><a href="froc-meanings.html#cb198-10"></a><span class="co">#&gt; 4 -0.3053884      -Inf</span></span>
<span id="cb198-11"><a href="froc-meanings.html#cb198-11"></a><span class="co">#&gt; 5  1.5117812      -Inf</span></span>
<span id="cb198-12"><a href="froc-meanings.html#cb198-12"></a><span class="co">#&gt; 6       -Inf      -Inf</span></span>
<span id="cb198-13"><a href="froc-meanings.html#cb198-13"></a><span class="co">#&gt; 7       -Inf      -Inf</span></span>
<span id="cb198-14"><a href="froc-meanings.html#cb198-14"></a><span class="co">#&gt; 8       -Inf      -Inf</span></span>
<span id="cb198-15"><a href="froc-meanings.html#cb198-15"></a>x2</span>
<span id="cb198-16"><a href="froc-meanings.html#cb198-16"></a><span class="co">#&gt;    location1 location2</span></span>
<span id="cb198-17"><a href="froc-meanings.html#cb198-17"></a><span class="co">#&gt; 1  0.8523430      -Inf</span></span>
<span id="cb198-18"><a href="froc-meanings.html#cb198-18"></a><span class="co">#&gt; 2 -0.2146999      -Inf</span></span>
<span id="cb198-19"><a href="froc-meanings.html#cb198-19"></a><span class="co">#&gt; 3  1.5884892      -Inf</span></span>
<span id="cb198-20"><a href="froc-meanings.html#cb198-20"></a><span class="co">#&gt; 4  2.9438362   1.98381</span></span></code></pre></div>
<ul>
<li>The length of the third dimension of the NL array is eight (4 non-diseased + 4 diseased cases).</li>
<li>The fifth sequential case corresponds to NLs on the first diseased case, etc.</li>
<li>The first non-diseased case has no latent marks.</li>
<li>The second non-diseased case has one latent mark rated 0.4874291.</li>
<li>The third non-diseased case has two latent marks rated 0.7383247 and 0.5757814.</li>
<li>The fourth non-diseased case has one latent mark rated -0.3053884.</li>
<li>The first diseased case has one latent NL mark rated 1.5117812.</li>
<li>The remaining diseased case have no latent NL marks.</li>
</ul>
</div>
<div id="summary-tables-of-ratings" class="section level2">
<h2><span class="header-section-number">28.7</span> Summary tables of ratings</h2>
<p>Table <a href="froc-meanings.html#tab:froc-meanings-table-non-diseased">28.1</a> shows the layout of mark-rating pairs on <em>non-diseased</em> cases, illustrating FP ratings, corresponding to the green circles in Fig. <a href="froc-meanings.html#fig:froc-meanings-linear-plot-afroc-wafroc">28.3</a>. [UM denotes an unmarked location and blank cells denote unrealized z-samples.]</p>
<ul>
<li>Because non-diseased cases have no lesions, all z-samples listed in this table are for NLs.</li>
<li>The first column lists the case numbers.</li>
<li>The column labeled <span class="math inline">\(k_t t l_s s\)</span> lists the case-location indexing subscripts.</li>
<li>The column labeled <span class="math inline">\(z_{k_t t l_s s}\)</span> lists the corresponding z-samples, when realized, and otherwise the cells are blank.</li>
<li>The column labeled <span class="math inline">\(FP_{k_t t}\)</span> lists the FP rating for each non-diseased case, which is the highest of all realized z-samples on the case or <span class="math inline">\(-\infty\)</span> if none are realized.</li>
<li>Column 5: the labels <strong>A</strong> - <strong>H</strong> correspond to the operating points shown in Fig. <a href="froc-meanings.html#fig:froc-meanings-linear-plot-afroc-wafroc">28.3</a> and Fig. <a href="froc-meanings.html#fig:froc-meanings-afroc-wafroc">28.4</a>.</li>
</ul>
<table>
<caption>
<span id="tab:froc-meanings-table-non-diseased">TABLE 28.1: </span>Layout of mark-rating pairs on non-diseased cases; UM denotes an unmarked non-diseased case.
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:left;">
<span class="math inline">\(k_t t l_s s\)</span>
</th>
<th style="text-align:left;">
<span class="math inline">\(z_{k_t t l_s s}\)</span>
</th>
<th style="text-align:left;">
<span class="math inline">\(FP_{k_t t}\)</span>
</th>
<th style="text-align:left;">
<span class="math inline">\(\text{Label}\)</span>
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
1111
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
1121
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
<span class="math inline">\(-\infty\)</span>
</td>
<td style="text-align:left;">
UM
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
2111
</td>
<td style="text-align:left;">
0.487
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
2
</td>
<td style="text-align:left;">
2121
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
0.487
</td>
<td style="text-align:left;">
F
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
3111
</td>
<td style="text-align:left;">
0.738
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
3
</td>
<td style="text-align:left;">
3121
</td>
<td style="text-align:left;">
0.576
</td>
<td style="text-align:left;">
0.738
</td>
<td style="text-align:left;">
E
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
4111
</td>
<td style="text-align:left;">
-0.305
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
4
</td>
<td style="text-align:left;">
4121
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
-0.305
</td>
<td style="text-align:left;">
H
</td>
</tr>
</tbody>
</table>
<p>Table <a href="froc-meanings.html#tab:froc-meanings-table-diseased">28.2</a> shows the layout of mark-rating pairs on <em>diseased</em> cases, illustrating LL ratings, corresponding to the red circles in Fig. <a href="froc-meanings.html#fig:froc-meanings-linear-plot-afroc-wafroc">28.3</a>. [UM denotes an unmarked location and blank cells denote unrealized z-samples.]</p>
<ul>
<li>Because diseased cases can have NLs and LLs, both are shown in this table.</li>
<li>The first column lists the case numbers.</li>
<li>The second column lists the number of lesions present.</li>
<li>Columns 3 and 4 illustrate NL indexing and z-samples.</li>
<li>Columns 5 and 6 illustrate LL indexing and z-samples.</li>
<li>Column 7 lists the lesion weights.</li>
<li>Column 8: the labels <strong>A</strong> - <strong>H</strong> correspond to the operating points shown in Fig. <a href="froc-meanings.html#fig:froc-meanings-linear-plot-afroc-wafroc">28.3</a> and Fig. <a href="froc-meanings.html#fig:froc-meanings-afroc-wafroc">28.4</a>.</li>
</ul>
<table>
<caption>
<span id="tab:froc-meanings-table-diseased">TABLE 28.2: </span>Layout of mark-rating pairs on diseased cases; UM denotes an unmarked lesion.
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:left;">
<span class="math inline">\(L_{k_2}\)</span>
</th>
<th style="text-align:left;">
<span class="math inline">\(k_t t l_s s\)</span>
</th>
<th style="text-align:left;">
<span class="math inline">\(z_{k_t t l_s s}\)</span>
</th>
<th style="text-align:left;">
<span class="math inline">\(k_t t l_s s\)</span>
</th>
<th style="text-align:left;">
<span class="math inline">\(z_{k_t t l_s s}\)</span>
</th>
<th style="text-align:left;">
<span class="math inline">\(\text{weights}\)</span>
</th>
<th style="text-align:left;">
<span class="math inline">\(\text{Label}\)</span>
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
1211
</td>
<td style="text-align:left;">
1.512
</td>
<td style="text-align:left;">
1212
</td>
<td style="text-align:left;">
0.852
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
D
</td>
</tr>
<tr>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
1221
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
1222
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
2211
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
2212
</td>
<td style="text-align:left;">
-0.215
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
G
</td>
</tr>
<tr>
<td style="text-align:left;">
2
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
2221
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
2222
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
3211
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
3212
</td>
<td style="text-align:left;">
1.588
</td>
<td style="text-align:left;">
0.6
</td>
<td style="text-align:left;">
C
</td>
</tr>
<tr>
<td style="text-align:left;">
3
</td>
<td style="text-align:left;">
2
</td>
<td style="text-align:left;">
3221
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
3222
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
0.4
</td>
<td style="text-align:left;">
UM
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
4211
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
4212
</td>
<td style="text-align:left;">
2.944
</td>
<td style="text-align:left;">
0.4
</td>
<td style="text-align:left;">
A
</td>
</tr>
<tr>
<td style="text-align:left;">
4
</td>
<td style="text-align:left;">
2
</td>
<td style="text-align:left;">
4221
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
4222
</td>
<td style="text-align:left;">
1.984
</td>
<td style="text-align:left;">
0.6
</td>
<td style="text-align:left;">
B
</td>
</tr>
</tbody>
</table>
</div>
<div id="froc-meanings-AFROC-plot-first-principles" class="section level2">
<h2><span class="header-section-number">28.8</span> AFROC plot from first principles</h2>
<p>The following example is based on the same data involving 8 cases that were used to generate Table <a href="froc-meanings.html#tab:froc-meanings-table-non-diseased">28.1</a> and Table <a href="froc-meanings.html#tab:froc-meanings-table-diseased">28.2</a>. It involves use of a linear or “one-dimensional” depiction of the ratings described next.</p>
<p>In Fig. <a href="froc-meanings.html#fig:froc-meanings-linear-plot-afroc-wafroc">28.3</a>, plot A, FPs and LLs, represented by green and red circles, respectively, are shown ordered, from left to right, with higher z-samples to the right, henceforth referred to as a <em>linear plot</em>. Each circle is labeled using the <span class="math inline">\(k_t t l_s s\)</span> notation. For example, the right-most red circle corresponds to the LL z-sample originating from the first lesion in the fourth diseased case, i.e., <span class="math inline">\(z_{4212}\)</span>. Consistent with the three unique values in the fourth column of Table <a href="froc-meanings.html#tab:froc-meanings-table-non-diseased">28.1</a>, there are three green circles (FPs).<a href="#fn26" class="footnote-ref" id="fnref26"><sup>26</sup></a> Likewise, consistent with the five unique values in the sixth column of Table <a href="froc-meanings.html#tab:froc-meanings-table-diseased">28.2</a>, there are five red circles (LLs).<a href="#fn27" class="footnote-ref" id="fnref27"><sup>27</sup></a></p>
<div class="figure"><span style="display:block;" id="fig:froc-meanings-linear-plot-afroc-wafroc"></span>
<img src="14-froc-meanings-foms-ocs_files/figure-html/froc-meanings-linear-plot-afroc-wafroc-1.png" alt="Plot A (illustrating generation of the AFROC): a one-dimensional depiction of the data in Table \@ref(tab:froc-meanings-table-non-diseased) and Table \@ref(tab:froc-meanings-table-diseased), showing z-samples used for plotting the AFROC; the red circles correspond to lesion localizations (LLs) and the green to false positives (FPs). Plot B (illustrating generation of the wAFROC): Data in same tables but this time including the weights, for plotting the weighted-AFROC plot; the sizes of the red circles code the lesions weights; the weights are shown below each z-sample." width="672" />
<p class="caption">
FIGURE 28.3: Plot A (illustrating generation of the AFROC): a one-dimensional depiction of the data in Table <a href="froc-meanings.html#tab:froc-meanings-table-non-diseased">28.1</a> and Table <a href="froc-meanings.html#tab:froc-meanings-table-diseased">28.2</a>, showing z-samples used for plotting the AFROC; the red circles correspond to lesion localizations (LLs) and the green to false positives (FPs). Plot B (illustrating generation of the wAFROC): Data in same tables but this time including the weights, for plotting the weighted-AFROC plot; the sizes of the red circles code the lesions weights; the weights are shown below each z-sample.
</p>
</div>
<p>Starting from <span class="math inline">\(\infty\)</span>, moving a virtual threshold continuously to the left generates the AFROC plot, see plot A in Fig. <a href="froc-meanings.html#fig:froc-meanings-linear-plot-afroc-wafroc">28.3</a>. As each FP is crossed, the operating point moves to the right by:</p>
<p><span class="math display">\[\frac{1}{K_1} = 0.025\]</span></p>
<p>As each LL is crossed, the operating point moves up by:</p>
<p><span class="math display">\[\sum_{k_2=1}^{K_2}L_{k_2}=\frac{1}{6}\]</span></p>
<p>Since it has one lesion, crossing the z-sample for the first case would result in an upward movement of 1/6, and likewise for the second case. Since the third case contains two lesions, crossing the corresponding z-samples would result in a net upward movement of the operating point by 1/3. <em>This behavior shows explicitly that the non-weighted method gives greater importance to diseased cases with more lesions, i.e., such case make a greater contribution to AUC.</em> The jumps from lesions in the same case need not be contiguous – they could be distributed, with intervening jumps from lesions on other cases, but eventually the jumps will occur and contribute to the net upward movement. As an example, the jumps due to the two lesions on the fourth diseased case are contiguous: see points A and B, in Fig. <a href="froc-meanings.html#fig:froc-meanings-linear-plot-afroc-wafroc">28.3</a>. However, the jumps due to the two lesions on the third diseased case are not contiguous: the first lesion gives the point C, but the unmarked lesion on this case, indicated by “UM” in Table <a href="froc-meanings.html#tab:froc-meanings-table-diseased">28.2</a>, eventually contributes when the operating point moves diagonally from point H to (1,1).</p>
<div class="figure"><span style="display:block;" id="fig:froc-meanings-afroc-wafroc"></span>
<img src="14-froc-meanings-foms-ocs_files/figure-html/froc-meanings-afroc-wafroc-1.png" alt="Plot A: The empirical AFROC plot for the data shown in Table \@ref(tab:froc-meanings-table-non-diseased) and Table \@ref(tab:froc-meanings-table-diseased). The labels correspond to the last columns of the tables. The corresponding one-dimensional depiction is plot A in Fig. \@ref(fig:froc-meanings-linear-plot-afroc-wafroc). The area under the empirical plot is 0.7708. Plot B: The empirical weighted-AFROC (wAFROC) plot for the data shown in Table \@ref(tab:froc-meanings-table-non-diseased) and Table \@ref(tab:froc-meanings-table-diseased). The corresponding one-dimensional plot is plot B in Fig. \@ref(fig:froc-meanings-linear-plot-afroc-wafroc). The area under the wAFROC is 0.7875. " width="672" />
<p class="caption">
FIGURE 28.4: Plot A: The empirical AFROC plot for the data shown in Table <a href="froc-meanings.html#tab:froc-meanings-table-non-diseased">28.1</a> and Table <a href="froc-meanings.html#tab:froc-meanings-table-diseased">28.2</a>. The labels correspond to the last columns of the tables. The corresponding one-dimensional depiction is plot A in Fig. <a href="froc-meanings.html#fig:froc-meanings-linear-plot-afroc-wafroc">28.3</a>. The area under the empirical plot is 0.7708. Plot B: The empirical weighted-AFROC (wAFROC) plot for the data shown in Table <a href="froc-meanings.html#tab:froc-meanings-table-non-diseased">28.1</a> and Table <a href="froc-meanings.html#tab:froc-meanings-table-diseased">28.2</a>. The corresponding one-dimensional plot is plot B in Fig. <a href="froc-meanings.html#fig:froc-meanings-linear-plot-afroc-wafroc">28.3</a>. The area under the wAFROC is 0.7875.
</p>
</div>
</div>
<div id="froc-meanings-wAFROC-plot-first-principles" class="section level2">
<h2><span class="header-section-number">28.9</span> wAFROC plot from first principles</h2>
<p>Plot B in Fig. <a href="froc-meanings.html#fig:froc-meanings-linear-plot-afroc-wafroc">28.3</a>, which is the wAFROC analog of plot A in the same figure, is a one-dimensional depiction of the data in Table <a href="froc-meanings.html#tab:froc-meanings-table-non-diseased">28.1</a> and Table <a href="froc-meanings.html#tab:froc-meanings-table-diseased">28.2</a>, but this time the lesion weights, shown in Table <a href="froc-meanings.html#tab:froc-meanings-table-diseased">28.2</a>, are incorporated, as indicated by varying the <em>size</em> of each red circle (in Fig. <a href="froc-meanings.html#fig:froc-meanings-linear-plot-afroc-wafroc">28.3</a> plot A, all red circles were of the same size). In addition, each lesion is labeled with its rating and weight.</p>
<p>Moving a virtual threshold continuously to the left generates the wAFROC plot, Fig. <a href="froc-meanings.html#fig:froc-meanings-afroc-wafroc">28.4</a> plot B. The movement of the operating point in response to crossing FPs is the same as before. However, as each LL is crossed the operating point moves up by an amount that depends on the lesion weight:</p>
<p><span class="math display">\[\frac{W_{k_2 l_2}}{K_2} = \frac{W_{k_2 l_2}}{4}\]</span></p>
<p>Since the first two diseased cases have one lesion each (i.e., unit weights), crossing the corresponding z-samples results in upward jumps of 0.25, Fig. <a href="froc-meanings.html#fig:froc-meanings-afroc-wafroc">28.4</a> plot B – compare the jumps C to D and from F to G. According to the weights in Fig. 14.4, crossing the z-sample of the first lesion in the third diseased case, results in an upward jump of 0.6/4. That from the second lesion in the same case results in an upward jump of 0.4/4, for a net upward jump of the third case of 0.25, the same as for each of the first two diseased cases. Likewise crossing the z-samples of the two lesions in the 4th disease case results in upward jump of 0.4/4 = 0.1 (compare the jump from O to A), for the 1st lesion and 0.6/4 = 0.15 (compare the jump from B to C), for the 2nd lesion, for a net upward jump of 1/4, which is the same as for each of the first three diseased cases. <em>This shows explicitly that the weighting method gives each diseased case the same importance, regardless of the number of lesions in it, a property not shared by the area under the AFROC.</em></p>
</div>
<div id="froc-meanings-physical-interpretions" class="section level2">
<h2><span class="header-section-number">28.10</span> Physical interpretations</h2>
<p>From the preceding sections, it is seen that the AFROC-based trapezoidal plots consist of upward and rightward jumps, starting from the origin (0,0) and ending at (1,1). This is true regardless of whether the z-samples are binned or not: i.e., at the “microscopic” level the jumps always exist. Each upward jump is associated with a LL rating exceeding a virtual threshold. Each rightward jump is associated with a FP rating exceeding the threshold. Upward jumps tend to increase the area under the AFROC-based plots and rightward jumps tend to decrease it. This makes physical sense in terms of correct decisions being rewarded and incorrect ones being penalized, and can be seen from two extreme-case examples. If there are only upward jumps, then the trapezoidal plot rises from the origin to (0,1), where all lesions are correctly localized without any generating FPs and performance is perfect – the straight-line extension to (1,1) ensures that the net area is unity. If there are only horizontal jumps, that takes the operating point from the origin to (1,0), where none of the lesions are localized and every non-diseased image has at least one NL mark, representing worst possible performance. Here, despite the straight line extension to (1,1), the net area is zero.</p>
<div id="physical-interpretation-of-area-under-afroc" class="section level3">
<h3><span class="header-section-number">28.10.1</span> Physical interpretation of area under AFROC</h3>
<p>The area under the AFROC has the following physical interpretation: it is the fraction of LL vs. FP z-sample comparisons where the LL sample is equal (counting as half a comparison) or greater (counting as a full comparison) than the FP z-sample. From Tables 1 and 2, there are four FPs and six LLs for 24 possible comparisons. Inspection of the tables reveals that there are 4 x 4 = 16 comparisons contributing ones, two comparisons (from the 2nd diseased case) contributing ones, and one comparison (from the 2nd lesion on the 3rd diseased case) contributing 0.5, which sum to 18.5. Dividing by 24 yields 18.5/24 = 0.7708, the empirical TBA AFROC-AUC, §14.5.1. In probabilistic terms:</p>
<p><em>The area under the AFROC is the probability that a lesion is rated higher than any mark on a non-diseased case.</em></p>
</div>
<div id="physical-interpretation-of-area-under-wafroc" class="section level3">
<h3><span class="header-section-number">28.10.2</span> Physical interpretation of area under wAFROC</h3>
<p>The area under the wAFROC has the following physical interpretation: it is the lesion-weight adjusted fraction of diseased cases vs. non-diseased case comparisons where LL z-samples are equal (counting as half a comparison times the weight of the lesion in question) or greater (counting as a full comparison times the weight of the lesion) than FP z-samples. Note that there are still 24 LL vs. FP comparisons but the counting proceeds differently. The fourth diseased case contributes 0.4 x 4 + 0.6 x 4, i.e., 4 (compared to 8 in the preceding example). The third diseased case contributes 0.6 x 4 + 0.4 x 0.5, i.e., 2.6 (compared to 4.5 in the preceding example). The second diseased case contributes 1 x 2 = 2 (compared to 2 in the preceding example), and the first diseased case contributes 1 x 4 = 4 (compared to 4 in the preceding example). Summing these values and dividing by 16 (the total number of diseased cases vs. non-diseased cases comparisons) one gets 12.6/16 = 0.7875, which is the area under the wAFROC, §14.5.1. In probabilistic terms:</p>
<p><em>The area under the weighted-AFROC is the lesion-weight adjusted probability that a lesion is rated higher than any mark on a non-diseased case.</em></p>
</div>
</div>
<div id="froc-meanings-Discussion" class="section level2">
<h2><span class="header-section-number">28.11</span> Discussion</h2>
<p>TBA
TODOLAST</p>
<p>The primary aim of this chapter was to develop expressions for FOMs (i.e., functions of ratings) and show their equivalences to the empirical AUCs under corresponding operating characteristics. Unlike the ROC, the AFROC and wAFROC figures of merit are represented by quasi-Wilcoxon like constructs, not the well-known Wilcoxon statistic5.</p>
<p>I am aware from users of my software that their manuscript submissions have sometimes been held up with the critique that the meaning of the AFROC FOM-statistic is “not intuitively clear”6 TBA. Any critique based on intuitive clarity or lack thereof suffers from a fundamental flaw: it is un-falsifiable. What is “intuitively not clear” to one could be “intuitively very clear” to another, and there is no way of testing either viewpoint. Un-falsifiable claims have no place in science.</p>
<p>An example was given in a previous chapter. This is one reason I have tried to make the meaning clear, perhaps at the risk of making it painfully clear. Clinical interpretations do not always fit into convenient easy to analyze paradigms. Not understanding something is not a reason for preferring a simpler method. Use of the simpler ROC paradigm to analyze location specific tasks results in loss of statistical power and sacrifices better understanding of what is limiting performance. It is unethical to analyze a study with a method with lower statistical power when one with greater power is available7-9. The title of the paper by Halpern et al is “The continuing unethical conduct of under-powered clinical trials”. The AFROC FOM-statistic was proposed in 1989 and it has been used, at the time of writing, in over 107 publications .</p>
<p>The subject material of this chapter is not that difficult. However, it does require the researcher to be receptive an unbiased. Dirac addressed an analogous then-existing concern about quantum mechanics, namely it did not provide a satisfying “picture” of what is going on, as did classical mechanics . To paraphrase him, the purpose of science (quantum physics in his case) is not to provide satisfying pictures but to explain data. FROC data is inherently more complex than the ROC paradigm and one should not expect a simple FOM-statistic. The detailed explanations given in this chapter should allow one to understand the wAFROC and AFROC FOMs.</p>
<p>A misconception regarding the wAFROC FOM-statistic is that the weighting may sacrifice statistical power and render the method equivalent to ROC analysis in terms of statistical power. Analysis of clinical datasets and simulation studies suggests that this is not the case; loss of power is minimal. As noted earlier, the highest rating carries more information than a randomly selected rating.</p>
<p>Bamber’s equivalence theorem led to much progress in non-parametric analysis of ROC data. The proofs of the equivalences between the areas under the AFROC and wAFROC and the corresponding quasi-Wilcoxon statistics provide a starting point. To realize the full potential of these proofs, similar work like that conducted by DeLong et al10 is needed for the FROC paradigm. This work is not going to be easy; one reason being the relative dearth of researchers working in this area, but it is possible. Indeed work has been published by Popescu11 on non-parametric analysis of the exponentially transformed FROC (EFROC) plot which, like the AFROC and wAFROC, is completely contained within the unit square. This work should be extended to the wAFROC. For reasons stated in Chapter 13, non-parametric analysis of FROC curves12-14 is not expected to be fruitful.</p>
<p>Current terminology prefixes each of the AFROC-based FOMs with the letter “J” for Jackknife. The author recommends dropping this prefix, which has to do with significance testing procedure rather than the actual definition of the FOM-statistic. For example, the correct way is to refer to the AFROC figure of merit, not the JAFROC figure of merit. For continuity, the software packages implementing the methods are still referred to as JAFROC (Windows) or RJAfroc (cross-platform, open-source).</p>
<p>To gain deeper insight into the FROC paradigm, it is necessary to look at methods used to measure visual search, the subject of the next chapter.</p>
</div>
<div id="froc-meanings-references" class="section level2">
<h2><span class="header-section-number">28.12</span> References</h2>

</div>
</div>
<h3>References</h3>
<div id="refs" class="references">
<div id="ref-RN2174">
<p>Bamber, Donald. 1975. “The Area Above the Ordinal Dominance Graph and the Area Below the Receiver Operating Characteristic Graph.” Journal Article. <em>Journal of Mathematical Psychology</em> 12 (4): 387–415. <a href="https://doi.org/10.1016/0022-2496(75)90001-2">https://doi.org/10.1016/0022-2496(75)90001-2</a>.</p>
</div>
<div id="ref-RN1385">
<p>Chakraborty, Dev P., and K. S. Berbaum. 2004. “Observer Studies Involving Detection and Localization: Modeling, Analysis and Validation.” Journal Article. <em>Med Phys</em> 31 (8): 2313–30.</p>
</div>
<div id="ref-RN2484">
<p>Chakraborty, Dev P, and Xuetong Zhai. 2016. “On the Meaning of the Weighted Alternative Free-Response Operating Characteristic Figure of Merit.” Journal Article. <em>Medical Physics</em> 43 (5): 2548–57.</p>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="24">
<li id="fn24"><p>The kernel function comparison yields 1 if the LL rating is higher, 0.5 if the ratings are identical and zero otherwise.<a href="froc-meanings.html#fnref24" class="footnote-back">↩︎</a></p></li>
<li id="fn25"><p>The <code>RJafroc</code> function <code>DfReadDataFile()</code> checks that the weights sum to unity to a precision of about 5 decimal places. The easy way to assign equal weights to all lesions on a diseased case is to set the corresponding <code>lesionWeights</code> field in the Excel file <code>Truth</code> worksheet to zeroes.<a href="froc-meanings.html#fnref25" class="footnote-back">↩︎</a></p></li>
<li id="fn26"><p>Not counting <span class="math inline">\(FP_{11}\)</span>, which occurs at <span class="math inline">\(z = -\infty\)</span>, representing the first non-diseased case with no marks.<a href="froc-meanings.html#fnref26" class="footnote-back">↩︎</a></p></li>
<li id="fn27"><p>Not counting <span class="math inline">\(z_{3222} = -\infty\)</span> representing the unmarked second lesion on the third diseased case.<a href="froc-meanings.html#fnref27" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="froc-vs-wafroc.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="visual-search.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["RJafrocBook.pdf", "RJafrocBook.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
