<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 19 Empirical plot examples | The RJafroc Book</title>
  <meta name="description" content="Updated observer-performance book based on RJafroc." />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 19 Empirical plot examples | The RJafroc Book" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Updated observer-performance book based on RJafroc." />
  <meta name="github-repo" content="dpc10ster/RJafrocBook" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 19 Empirical plot examples | The RJafroc Book" />
  
  <meta name="twitter:description" content="Updated observer-performance book based on RJafroc." />
  

<meta name="author" content="Dev P. Chakraborty, PhD" />


<meta name="date" content="2020-11-05" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="froc-empirical.html"/>
<link rel="next" href="froc-paradigm-froc-vs-afroc.html"/>
<script src="libs/header-attrs-2.5/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">RJafroc documentation</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#a-note-on-the-online-distribution-mechanism-of-the-book"><i class="fa fa-check"></i>A note on the online distribution mechanism of the book</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#contributing-to-this-book"><i class="fa fa-check"></i>Contributing to this book</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#is-this-book-relevant-to-you-and-what-are-the-alternatives"><i class="fa fa-check"></i>Is this book relevant to you and what are the alternatives?</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#todos"><i class="fa fa-check"></i>ToDos</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#chapters-needing-heavy-edits"><i class="fa fa-check"></i>Chapters needing heavy edits</a></li>
</ul></li>
<li class="part"><span><b>ROC paradigm</b></span></li>
<li class="chapter" data-level="1" data-path="preliminaries.html"><a href="preliminaries.html"><i class="fa fa-check"></i><b>1</b> Preliminaries</a>
<ul>
<li class="chapter" data-level="1.1" data-path="preliminaries.html"><a href="preliminaries.html#preliminariesIntro"><i class="fa fa-check"></i><b>1.1</b> Introduction</a></li>
<li class="chapter" data-level="1.2" data-path="preliminaries.html"><a href="preliminaries.html#clinical-tasks"><i class="fa fa-check"></i><b>1.2</b> Clinical tasks</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="preliminaries.html"><a href="preliminaries.html#workflow-in-an-imaging-study"><i class="fa fa-check"></i><b>1.2.1</b> Workflow in an imaging study</a></li>
<li class="chapter" data-level="1.2.2" data-path="preliminaries.html"><a href="preliminaries.html#the-screening-and-diagnostic-workup-tasks"><i class="fa fa-check"></i><b>1.2.2</b> The screening and diagnostic workup tasks</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="preliminaries.html"><a href="preliminaries.html#imaging-device-development-and-its-clinical-deployment"><i class="fa fa-check"></i><b>1.3</b> Imaging device development and its clinical deployment</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="preliminaries.html"><a href="preliminaries.html#physical-measurements"><i class="fa fa-check"></i><b>1.3.1</b> Physical measurements</a></li>
<li class="chapter" data-level="1.3.2" data-path="preliminaries.html"><a href="preliminaries.html#quality-control-and-image-quality-optimization"><i class="fa fa-check"></i><b>1.3.2</b> Quality Control and Image quality optimization</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="preliminaries.html"><a href="preliminaries.html#image-quality-vs.-task-performance"><i class="fa fa-check"></i><b>1.4</b> Image quality vs. task performance</a></li>
<li class="chapter" data-level="1.5" data-path="preliminaries.html"><a href="preliminaries.html#why-physical-measures-of-image-quality-are-not-enough"><i class="fa fa-check"></i><b>1.5</b> Why physical measures of image quality are not enough</a></li>
<li class="chapter" data-level="1.6" data-path="preliminaries.html"><a href="preliminaries.html#model-observers"><i class="fa fa-check"></i><b>1.6</b> Model observers</a></li>
<li class="chapter" data-level="1.7" data-path="preliminaries.html"><a href="preliminaries.html#measuring-observer-performance-four-paradigms"><i class="fa fa-check"></i><b>1.7</b> Measuring observer performance: four paradigms</a>
<ul>
<li class="chapter" data-level="1.7.1" data-path="preliminaries.html"><a href="preliminaries.html#basic-approach-to-the-analysis"><i class="fa fa-check"></i><b>1.7.1</b> Basic approach to the analysis</a></li>
<li class="chapter" data-level="1.7.2" data-path="preliminaries.html"><a href="preliminaries.html#historical-notes"><i class="fa fa-check"></i><b>1.7.2</b> Historical notes</a></li>
</ul></li>
<li class="chapter" data-level="1.8" data-path="preliminaries.html"><a href="preliminaries.html#hierarchy-of-assessment-methods"><i class="fa fa-check"></i><b>1.8</b> Hierarchy of assessment methods</a></li>
<li class="chapter" data-level="1.9" data-path="preliminaries.html"><a href="preliminaries.html#overview-of-the-book-and-how-to-use-it"><i class="fa fa-check"></i><b>1.9</b> Overview of the book and how to use it</a>
<ul>
<li class="chapter" data-level="1.9.1" data-path="preliminaries.html"><a href="preliminaries.html#overview-of-the-book"><i class="fa fa-check"></i><b>1.9.1</b> Overview of the book</a></li>
<li class="chapter" data-level="1.9.2" data-path="preliminaries.html"><a href="preliminaries.html#how-to-use-the-book"><i class="fa fa-check"></i><b>1.9.2</b> How to use the book</a></li>
</ul></li>
<li class="chapter" data-level="1.10" data-path="preliminaries.html"><a href="preliminaries.html#preliminaries-Summary"><i class="fa fa-check"></i><b>1.10</b> Summary</a></li>
<li class="chapter" data-level="1.11" data-path="preliminaries.html"><a href="preliminaries.html#preliminaries-Discussion"><i class="fa fa-check"></i><b>1.11</b> Discussion</a></li>
<li class="chapter" data-level="1.12" data-path="preliminaries.html"><a href="preliminaries.html#preliminaries-references"><i class="fa fa-check"></i><b>1.12</b> References</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="binaryTask0.html"><a href="binaryTask0.html"><i class="fa fa-check"></i><b>2</b> The Binary Task</a>
<ul>
<li class="chapter" data-level="2.1" data-path="binaryTask0.html"><a href="binaryTask0.html#binaryTask0Intro"><i class="fa fa-check"></i><b>2.1</b> Introduction</a></li>
<li class="chapter" data-level="2.2" data-path="binaryTask0.html"><a href="binaryTask0.html#binaryTask0Truth"><i class="fa fa-check"></i><b>2.2</b> The fundamental 2x2 table</a></li>
<li class="chapter" data-level="2.3" data-path="binaryTask0.html"><a href="binaryTask0.html#sensitivity-and-specificity"><i class="fa fa-check"></i><b>2.3</b> Sensitivity and specificity</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="binaryTask0.html"><a href="binaryTask0.html#reasons-for-the-names-sensitivity-and-specificity"><i class="fa fa-check"></i><b>2.3.1</b> Reasons for the names sensitivity and specificity</a></li>
<li class="chapter" data-level="2.3.2" data-path="binaryTask0.html"><a href="binaryTask0.html#estimating-sensitivity-and-specificity"><i class="fa fa-check"></i><b>2.3.2</b> Estimating sensitivity and specificity</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="binaryTask0.html"><a href="binaryTask0.html#disease-prevalence"><i class="fa fa-check"></i><b>2.4</b> Disease prevalence</a></li>
<li class="chapter" data-level="2.5" data-path="binaryTask0.html"><a href="binaryTask0.html#accuracy"><i class="fa fa-check"></i><b>2.5</b> Accuracy</a></li>
<li class="chapter" data-level="2.6" data-path="binaryTask0.html"><a href="binaryTask0.html#negative-and-positive-predictive-values"><i class="fa fa-check"></i><b>2.6</b> Negative and positive predictive values</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="binaryTask0.html"><a href="binaryTask0.html#binaryTask0NpvPpvCode"><i class="fa fa-check"></i><b>2.6.1</b> Example calculation of PPV, NPV and accuracy</a></li>
<li class="chapter" data-level="2.6.2" data-path="binaryTask0.html"><a href="binaryTask0.html#binaryTask0NpvPpvComments"><i class="fa fa-check"></i><b>2.6.2</b> Comments</a></li>
<li class="chapter" data-level="2.6.3" data-path="binaryTask0.html"><a href="binaryTask0.html#binaryTask0NpvPpvIrrel2LabTasks"><i class="fa fa-check"></i><b>2.6.3</b> PPV and NPV are irrelevant to laboratory tasks</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="binaryTask0.html"><a href="binaryTask0.html#binaryTask0-Summary"><i class="fa fa-check"></i><b>2.7</b> Summary</a></li>
<li class="chapter" data-level="2.8" data-path="binaryTask0.html"><a href="binaryTask0.html#binaryTask0-Discussion"><i class="fa fa-check"></i><b>2.8</b> Discussion</a></li>
<li class="chapter" data-level="2.9" data-path="binaryTask0.html"><a href="binaryTask0.html#binaryTask0-references"><i class="fa fa-check"></i><b>2.9</b> References</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="binaryTask.html"><a href="binaryTask.html"><i class="fa fa-check"></i><b>3</b> Modeling the Binary Task</a>
<ul>
<li class="chapter" data-level="3.1" data-path="binaryTask.html"><a href="binaryTask.html#binaryTaskIntro"><i class="fa fa-check"></i><b>3.1</b> Introduction</a></li>
<li class="chapter" data-level="3.2" data-path="binaryTask.html"><a href="binaryTask.html#decision-variable-and-decision-threshold"><i class="fa fa-check"></i><b>3.2</b> Decision variable and decision threshold</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="binaryTask.html"><a href="binaryTask.html#binaryTaskDecisionVariablelModel"><i class="fa fa-check"></i><b>3.2.1</b> Existence of a decision variable</a></li>
<li class="chapter" data-level="3.2.2" data-path="binaryTask.html"><a href="binaryTask.html#existence-of-a-decision-threshold"><i class="fa fa-check"></i><b>3.2.2</b> Existence of a decision threshold</a></li>
<li class="chapter" data-level="3.2.3" data-path="binaryTask.html"><a href="binaryTask.html#adequacy-of-the-training-session"><i class="fa fa-check"></i><b>3.2.3</b> Adequacy of the training session</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="binaryTask.html"><a href="binaryTask.html#changing-the-decision-threshold-example-i"><i class="fa fa-check"></i><b>3.3</b> Changing the decision threshold: Example I</a></li>
<li class="chapter" data-level="3.4" data-path="binaryTask.html"><a href="binaryTask.html#changing-the-decision-threshold-example-ii"><i class="fa fa-check"></i><b>3.4</b> Changing the decision threshold: Example II</a></li>
<li class="chapter" data-level="3.5" data-path="binaryTask.html"><a href="binaryTask.html#the-equal-variance-binormal-model"><i class="fa fa-check"></i><b>3.5</b> The equal-variance binormal model</a></li>
<li class="chapter" data-level="3.6" data-path="binaryTask.html"><a href="binaryTask.html#the-normal-distribution"><i class="fa fa-check"></i><b>3.6</b> The normal distribution</a></li>
<li class="chapter" data-level="3.7" data-path="binaryTask.html"><a href="binaryTask.html#analytic-expressions-for-specificity-and-sensitivity"><i class="fa fa-check"></i><b>3.7</b> Analytic expressions for specificity and sensitivity</a></li>
<li class="chapter" data-level="3.8" data-path="binaryTask.html"><a href="binaryTask.html#demonstration-of-the-concepts-of-sensitivity-and-specificity"><i class="fa fa-check"></i><b>3.8</b> Demonstration of the concepts of sensitivity and specificity</a>
<ul>
<li class="chapter" data-level="3.8.1" data-path="binaryTask.html"><a href="binaryTask.html#estimating-mu-from-a-finite-sample"><i class="fa fa-check"></i><b>3.8.1</b> Estimating mu from a finite sample</a></li>
<li class="chapter" data-level="3.8.2" data-path="binaryTask.html"><a href="binaryTask.html#changing-the-seed-variable-case-sampling-variability"><i class="fa fa-check"></i><b>3.8.2</b> Changing the seed variable: case-sampling variability</a></li>
<li class="chapter" data-level="3.8.3" data-path="binaryTask.html"><a href="binaryTask.html#increasing-the-numbers-of-cases"><i class="fa fa-check"></i><b>3.8.3</b> Increasing the numbers of cases</a></li>
</ul></li>
<li class="chapter" data-level="3.9" data-path="binaryTask.html"><a href="binaryTask.html#inverse-variation-of-sensitivity-and-specificity-and-the-need-for-a-single-fom"><i class="fa fa-check"></i><b>3.9</b> Inverse variation of sensitivity and specificity and the need for a single FOM</a></li>
<li class="chapter" data-level="3.10" data-path="binaryTask.html"><a href="binaryTask.html#the-roc-curve"><i class="fa fa-check"></i><b>3.10</b> The ROC curve</a>
<ul>
<li class="chapter" data-level="3.10.1" data-path="binaryTask.html"><a href="binaryTask.html#the-chance-diagonal"><i class="fa fa-check"></i><b>3.10.1</b> The chance diagonal</a></li>
<li class="chapter" data-level="3.10.2" data-path="binaryTask.html"><a href="binaryTask.html#the-guessing-observer"><i class="fa fa-check"></i><b>3.10.2</b> The guessing observer</a></li>
<li class="chapter" data-level="3.10.3" data-path="binaryTask.html"><a href="binaryTask.html#symmetry-with-respect-to-negative-diagonal"><i class="fa fa-check"></i><b>3.10.3</b> Symmetry with respect to negative diagonal</a></li>
<li class="chapter" data-level="3.10.4" data-path="binaryTask.html"><a href="binaryTask.html#area-under-the-roc-curve"><i class="fa fa-check"></i><b>3.10.4</b> Area under the ROC curve</a></li>
<li class="chapter" data-level="3.10.5" data-path="binaryTask.html"><a href="binaryTask.html#properties-of-the-equal-variance-binormal-model-roc-curve"><i class="fa fa-check"></i><b>3.10.5</b> Properties of the equal-variance binormal model ROC curve</a></li>
<li class="chapter" data-level="3.10.6" data-path="binaryTask.html"><a href="binaryTask.html#comments"><i class="fa fa-check"></i><b>3.10.6</b> Comments</a></li>
<li class="chapter" data-level="3.10.7" data-path="binaryTask.html"><a href="binaryTask.html#physical-interpretation-of-the-mu-parameter"><i class="fa fa-check"></i><b>3.10.7</b> Physical interpretation of the mu-parameter</a></li>
</ul></li>
<li class="chapter" data-level="3.11" data-path="binaryTask.html"><a href="binaryTask.html#assigning-confidence-intervals-to-an-operating-point"><i class="fa fa-check"></i><b>3.11</b> Assigning confidence intervals to an operating point</a></li>
<li class="chapter" data-level="3.12" data-path="binaryTask.html"><a href="binaryTask.html#variability-in-sensitivity-and-specificity-the-beam-et-al-study"><i class="fa fa-check"></i><b>3.12</b> Variability in sensitivity and specificity: the Beam et al study</a></li>
<li class="chapter" data-level="3.13" data-path="binaryTask.html"><a href="binaryTask.html#binaryTask-Summary"><i class="fa fa-check"></i><b>3.13</b> Summary</a></li>
<li class="chapter" data-level="3.14" data-path="binaryTask.html"><a href="binaryTask.html#binaryTask-Discussion"><i class="fa fa-check"></i><b>3.14</b> Discussion</a></li>
<li class="chapter" data-level="3.15" data-path="binaryTask.html"><a href="binaryTask.html#binaryTask-references"><i class="fa fa-check"></i><b>3.15</b> References</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="ratingsParadigm.html"><a href="ratingsParadigm.html"><i class="fa fa-check"></i><b>4</b> Ratings Paradigm</a>
<ul>
<li class="chapter" data-level="4.1" data-path="ratingsParadigm.html"><a href="ratingsParadigm.html#introduction"><i class="fa fa-check"></i><b>4.1</b> Introduction</a></li>
<li class="chapter" data-level="4.2" data-path="ratingsParadigm.html"><a href="ratingsParadigm.html#the-roc-counts-table"><i class="fa fa-check"></i><b>4.2</b> The ROC counts table</a></li>
<li class="chapter" data-level="4.3" data-path="ratingsParadigm.html"><a href="ratingsParadigm.html#operating-points-from-counts-table"><i class="fa fa-check"></i><b>4.3</b> Operating points from counts table</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="ratingsParadigm.html"><a href="ratingsParadigm.html#labeling-the-points"><i class="fa fa-check"></i><b>4.3.1</b> Labeling the points</a></li>
<li class="chapter" data-level="4.3.2" data-path="ratingsParadigm.html"><a href="ratingsParadigm.html#examples"><i class="fa fa-check"></i><b>4.3.2</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="ratingsParadigm.html"><a href="ratingsParadigm.html#automating-all-this"><i class="fa fa-check"></i><b>4.4</b> Automating all this</a></li>
<li class="chapter" data-level="4.5" data-path="ratingsParadigm.html"><a href="ratingsParadigm.html#relation-between-ratings-paradigm-and-the-binary-paradigm"><i class="fa fa-check"></i><b>4.5</b> Relation between ratings paradigm and the binary paradigm</a></li>
<li class="chapter" data-level="4.6" data-path="ratingsParadigm.html"><a href="ratingsParadigm.html#ratings-are-not-numerical-values"><i class="fa fa-check"></i><b>4.6</b> Ratings are not numerical values</a></li>
<li class="chapter" data-level="4.7" data-path="ratingsParadigm.html"><a href="ratingsParadigm.html#a-single-clinical-operating-point-from-ratings-data"><i class="fa fa-check"></i><b>4.7</b> A single “clinical” operating point from ratings data</a></li>
<li class="chapter" data-level="4.8" data-path="ratingsParadigm.html"><a href="ratingsParadigm.html#the-forced-choice-paradigm"><i class="fa fa-check"></i><b>4.8</b> The forced choice paradigm</a></li>
<li class="chapter" data-level="4.9" data-path="ratingsParadigm.html"><a href="ratingsParadigm.html#observer-performance-studies-as-laboratory-simulations-of-clinical-tasks"><i class="fa fa-check"></i><b>4.9</b> Observer performance studies as laboratory simulations of clinical tasks</a></li>
<li class="chapter" data-level="4.10" data-path="ratingsParadigm.html"><a href="ratingsParadigm.html#discrete-vs.-continuous-ratings-the-miller-study"><i class="fa fa-check"></i><b>4.10</b> Discrete vs. continuous ratings: the Miller study</a></li>
<li class="chapter" data-level="4.11" data-path="ratingsParadigm.html"><a href="ratingsParadigm.html#the-controversy"><i class="fa fa-check"></i><b>4.11</b> The controversy</a></li>
<li class="chapter" data-level="4.12" data-path="ratingsParadigm.html"><a href="ratingsParadigm.html#ratingsParadigm-discussion"><i class="fa fa-check"></i><b>4.12</b> Discussion</a></li>
<li class="chapter" data-level="4.13" data-path="ratingsParadigm.html"><a href="ratingsParadigm.html#ratingsParadigm-references"><i class="fa fa-check"></i><b>4.13</b> References</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="empiricalAUC.html"><a href="empiricalAUC.html"><i class="fa fa-check"></i><b>5</b> Empirical AUC</a>
<ul>
<li class="chapter" data-level="5.1" data-path="empiricalAUC.html"><a href="empiricalAUC.html#empiricalAUC-Intro"><i class="fa fa-check"></i><b>5.1</b> Introduction</a></li>
<li class="chapter" data-level="5.2" data-path="empiricalAUC.html"><a href="empiricalAUC.html#empirical-ROC-plot"><i class="fa fa-check"></i><b>5.2</b> The empirical ROC plot</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="empiricalAUC.html"><a href="empiricalAUC.html#notation-for-cases"><i class="fa fa-check"></i><b>5.2.1</b> Notation for cases</a></li>
<li class="chapter" data-level="5.2.2" data-path="empiricalAUC.html"><a href="empiricalAUC.html#an-empirical-operating-point"><i class="fa fa-check"></i><b>5.2.2</b> An empirical operating point</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="empiricalAUC.html"><a href="empiricalAUC.html#empirical-operating-points-from-ratings-data"><i class="fa fa-check"></i><b>5.3</b> Empirical operating points from ratings data</a></li>
<li class="chapter" data-level="5.4" data-path="empiricalAUC.html"><a href="empiricalAUC.html#auc-under-the-empirical-roc-plot"><i class="fa fa-check"></i><b>5.4</b> AUC under the empirical ROC plot</a></li>
<li class="chapter" data-level="5.5" data-path="empiricalAUC.html"><a href="empiricalAUC.html#the-wilcoxon-statistic"><i class="fa fa-check"></i><b>5.5</b> The Wilcoxon statistic</a></li>
<li class="chapter" data-level="5.6" data-path="empiricalAUC.html"><a href="empiricalAUC.html#bambers-equivalence-theorem"><i class="fa fa-check"></i><b>5.6</b> Bamber’s Equivalence theorem</a></li>
<li class="chapter" data-level="5.7" data-path="empiricalAUC.html"><a href="empiricalAUC.html#importance-of-bambers-theorem"><i class="fa fa-check"></i><b>5.7</b> Importance of Bamber’s theorem</a></li>
<li class="chapter" data-level="5.8" data-path="empiricalAUC.html"><a href="empiricalAUC.html#discussion-summary"><i class="fa fa-check"></i><b>5.8</b> Discussion / Summary</a></li>
<li class="chapter" data-level="5.9" data-path="empiricalAUC.html"><a href="empiricalAUC.html#appendix-5.a-details-of-wilcoxon-theorem"><i class="fa fa-check"></i><b>5.9</b> Appendix 5.A: Details of Wilcoxon theorem</a>
<ul>
<li class="chapter" data-level="5.9.1" data-path="empiricalAUC.html"><a href="empiricalAUC.html#upper-triangle"><i class="fa fa-check"></i><b>5.9.1</b> Upper triangle</a></li>
<li class="chapter" data-level="5.9.2" data-path="empiricalAUC.html"><a href="empiricalAUC.html#lowest-trapezoid"><i class="fa fa-check"></i><b>5.9.2</b> Lowest trapezoid</a></li>
</ul></li>
<li class="chapter" data-level="5.10" data-path="empiricalAUC.html"><a href="empiricalAUC.html#empiricalAUC-references"><i class="fa fa-check"></i><b>5.10</b> References</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="BinormalModel.html"><a href="BinormalModel.html"><i class="fa fa-check"></i><b>6</b> Binormal model</a>
<ul>
<li class="chapter" data-level="6.1" data-path="BinormalModel.html"><a href="BinormalModel.html#BinormalModelIntro"><i class="fa fa-check"></i><b>6.1</b> Introduction</a></li>
<li class="chapter" data-level="6.2" data-path="BinormalModel.html"><a href="BinormalModel.html#BinormalModelTheModel"><i class="fa fa-check"></i><b>6.2</b> The binormal model</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="BinormalModel.html"><a href="BinormalModel.html#binning-the-data"><i class="fa fa-check"></i><b>6.2.1</b> Binning the data</a></li>
<li class="chapter" data-level="6.2.2" data-path="BinormalModel.html"><a href="BinormalModel.html#invariance-of-the-binormal-model-to-arbitrary-monotone-transformations"><i class="fa fa-check"></i><b>6.2.2</b> Invariance of the binormal model to arbitrary monotone transformations</a></li>
<li class="chapter" data-level="6.2.3" data-path="BinormalModel.html"><a href="BinormalModel.html#expressions-for-sensitivity-and-specificity"><i class="fa fa-check"></i><b>6.2.3</b> Expressions for sensitivity and specificity</a></li>
<li class="chapter" data-level="6.2.4" data-path="BinormalModel.html"><a href="BinormalModel.html#binormal-model-in-standard-notation"><i class="fa fa-check"></i><b>6.2.4</b> Binormal model in standard notation</a></li>
<li class="chapter" data-level="6.2.5" data-path="BinormalModel.html"><a href="BinormalModel.html#properties-of-the-binormal-model-roc-curve"><i class="fa fa-check"></i><b>6.2.5</b> Properties of the binormal model ROC curve</a></li>
<li class="chapter" data-level="6.2.6" data-path="BinormalModel.html"><a href="BinormalModel.html#density-functions-pdfs-of-the-binormal-model"><i class="fa fa-check"></i><b>6.2.6</b> Density functions (pdfs) of the binormal model</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="BinormalModel.html"><a href="BinormalModel.html#fitting-an-roc-curve-to-data-points"><i class="fa fa-check"></i><b>6.3</b> Fitting an ROC curve to data points</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="BinormalModel.html"><a href="BinormalModel.html#a-java-fitted-roc-curve"><i class="fa fa-check"></i><b>6.3.1</b> A JAVA fitted ROC curve</a></li>
<li class="chapter" data-level="6.3.2" data-path="BinormalModel.html"><a href="BinormalModel.html#a-simplistic-straight-line-fit-to-the-roc-curve"><i class="fa fa-check"></i><b>6.3.2</b> A simplistic straight line fit to the ROC curve</a></li>
<li class="chapter" data-level="6.3.3" data-path="BinormalModel.html"><a href="BinormalModel.html#maximum-likelihood-estimation-mle"><i class="fa fa-check"></i><b>6.3.3</b> Maximum likelihood estimation (MLE)</a></li>
<li class="chapter" data-level="6.3.4" data-path="BinormalModel.html"><a href="BinormalModel.html#code-implementing-mle"><i class="fa fa-check"></i><b>6.3.4</b> Code implementing MLE</a></li>
<li class="chapter" data-level="6.3.5" data-path="BinormalModel.html"><a href="BinormalModel.html#validating-the-fitting-model"><i class="fa fa-check"></i><b>6.3.5</b> Validating the fitting model</a></li>
<li class="chapter" data-level="6.3.6" data-path="BinormalModel.html"><a href="BinormalModel.html#estimating-the-covariance-matrix"><i class="fa fa-check"></i><b>6.3.6</b> Estimating the covariance matrix</a></li>
<li class="chapter" data-level="6.3.7" data-path="BinormalModel.html"><a href="BinormalModel.html#estimating-the-variance-of-az"><i class="fa fa-check"></i><b>6.3.7</b> Estimating the variance of Az</a></li>
<li class="chapter" data-level="6.3.8" data-path="BinormalModel.html"><a href="BinormalModel.html#single-fom-derived-from-roc-curve"><i class="fa fa-check"></i><b>6.3.8</b> Single FOM derived from ROC curve</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="BinormalModel.html"><a href="BinormalModel.html#BinormalModel-Discussion"><i class="fa fa-check"></i><b>6.4</b> Discussion</a></li>
<li class="chapter" data-level="6.5" data-path="BinormalModel.html"><a href="BinormalModel.html#BinormalModel-references"><i class="fa fa-check"></i><b>6.5</b> References</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="sourcesVariability.html"><a href="sourcesVariability.html"><i class="fa fa-check"></i><b>7</b> Sources of AUC variability</a>
<ul>
<li class="chapter" data-level="7.1" data-path="sourcesVariability.html"><a href="sourcesVariability.html#sourcesVariabilityIntro"><i class="fa fa-check"></i><b>7.1</b> Introduction</a></li>
<li class="chapter" data-level="7.2" data-path="sourcesVariability.html"><a href="sourcesVariability.html#sourcesVariability3sources"><i class="fa fa-check"></i><b>7.2</b> Three sources of variability</a></li>
<li class="chapter" data-level="7.3" data-path="sourcesVariability.html"><a href="sourcesVariability.html#dependence-of-auc-on-the-case-sample"><i class="fa fa-check"></i><b>7.3</b> Dependence of AUC on the case sample</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="sourcesVariability.html"><a href="sourcesVariability.html#case-sampling-variability-of-auc"><i class="fa fa-check"></i><b>7.3.1</b> Case sampling variability of AUC</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="sourcesVariability.html"><a href="sourcesVariability.html#sourcesVariabilityDeLong"><i class="fa fa-check"></i><b>7.4</b> DeLong method</a></li>
<li class="chapter" data-level="7.5" data-path="sourcesVariability.html"><a href="sourcesVariability.html#sourcesVariabilityBootstrap"><i class="fa fa-check"></i><b>7.5</b> Bootstrap method</a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="sourcesVariability.html"><a href="sourcesVariability.html#demonstration-of-the-bootstrap-method"><i class="fa fa-check"></i><b>7.5.1</b> Demonstration of the bootstrap method</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="sourcesVariability.html"><a href="sourcesVariability.html#sourcesVariabilityJackknife"><i class="fa fa-check"></i><b>7.6</b> Jackknife method</a></li>
<li class="chapter" data-level="7.7" data-path="sourcesVariability.html"><a href="sourcesVariability.html#sourcesVariabilityCalSimulator"><i class="fa fa-check"></i><b>7.7</b> Calibrated simulator</a>
<ul>
<li class="chapter" data-level="7.7.1" data-path="sourcesVariability.html"><a href="sourcesVariability.html#the-need-for-a-calibrated-simulator"><i class="fa fa-check"></i><b>7.7.1</b> The need for a calibrated simulator</a></li>
<li class="chapter" data-level="7.7.2" data-path="sourcesVariability.html"><a href="sourcesVariability.html#implementation-of-a-simple-calibrated-simulator"><i class="fa fa-check"></i><b>7.7.2</b> Implementation of a simple calibrated simulator</a></li>
</ul></li>
<li class="chapter" data-level="7.8" data-path="sourcesVariability.html"><a href="sourcesVariability.html#sourcesVariability-Discussion"><i class="fa fa-check"></i><b>7.8</b> Discussion</a></li>
<li class="chapter" data-level="7.9" data-path="sourcesVariability.html"><a href="sourcesVariability.html#sourcesVariability-references"><i class="fa fa-check"></i><b>7.9</b> References</a></li>
</ul></li>
<li class="part"><span><b>Significance Testing</b></span></li>
<li class="chapter" data-level="8" data-path="HypothesisTesting.html"><a href="HypothesisTesting.html"><i class="fa fa-check"></i><b>8</b> Hypothesis Testing</a>
<ul>
<li class="chapter" data-level="8.1" data-path="HypothesisTesting.html"><a href="HypothesisTesting.html#HypothesisTesting-introduction"><i class="fa fa-check"></i><b>8.1</b> Introduction</a></li>
<li class="chapter" data-level="8.2" data-path="HypothesisTesting.html"><a href="HypothesisTesting.html#single-modality-single-reader-roc-study"><i class="fa fa-check"></i><b>8.2</b> Single-modality single-reader ROC study</a></li>
<li class="chapter" data-level="8.3" data-path="HypothesisTesting.html"><a href="HypothesisTesting.html#type-i-errors"><i class="fa fa-check"></i><b>8.3</b> Type-I errors</a></li>
<li class="chapter" data-level="8.4" data-path="HypothesisTesting.html"><a href="HypothesisTesting.html#one-vs.-two-sided-tests"><i class="fa fa-check"></i><b>8.4</b> One vs. two sided tests</a></li>
<li class="chapter" data-level="8.5" data-path="HypothesisTesting.html"><a href="HypothesisTesting.html#statistical-power"><i class="fa fa-check"></i><b>8.5</b> Statistical power</a>
<ul>
<li class="chapter" data-level="8.5.1" data-path="HypothesisTesting.html"><a href="HypothesisTesting.html#factors-affecting-statistical-power"><i class="fa fa-check"></i><b>8.5.1</b> Factors affecting statistical power</a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="HypothesisTesting.html"><a href="HypothesisTesting.html#HypothesisTestingComments"><i class="fa fa-check"></i><b>8.6</b> Comments</a></li>
<li class="chapter" data-level="8.7" data-path="HypothesisTesting.html"><a href="HypothesisTesting.html#why-alpha-is-chosen-as-5"><i class="fa fa-check"></i><b>8.7</b> Why alpha is chosen as 5%</a></li>
<li class="chapter" data-level="8.8" data-path="HypothesisTesting.html"><a href="HypothesisTesting.html#HypothesisTestingDiscussion"><i class="fa fa-check"></i><b>8.8</b> Discussion</a></li>
<li class="chapter" data-level="8.9" data-path="HypothesisTesting.html"><a href="HypothesisTesting.html#HypothesisTesting-references"><i class="fa fa-check"></i><b>8.9</b> References</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="DBMAnalysisBkgrnd.html"><a href="DBMAnalysisBkgrnd.html"><i class="fa fa-check"></i><b>9</b> DBM method background</a>
<ul>
<li class="chapter" data-level="9.1" data-path="DBMAnalysisBkgrnd.html"><a href="DBMAnalysisBkgrnd.html#DBMAnalysisBkgrnd-introduction"><i class="fa fa-check"></i><b>9.1</b> Introduction</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="DBMAnalysisBkgrnd.html"><a href="DBMAnalysisBkgrnd.html#historical-background"><i class="fa fa-check"></i><b>9.1.1</b> Historical background</a></li>
<li class="chapter" data-level="9.1.2" data-path="DBMAnalysisBkgrnd.html"><a href="DBMAnalysisBkgrnd.html#the-wagner-analogy"><i class="fa fa-check"></i><b>9.1.2</b> The Wagner analogy</a></li>
<li class="chapter" data-level="9.1.3" data-path="DBMAnalysisBkgrnd.html"><a href="DBMAnalysisBkgrnd.html#the-shortage-of-numbers-to-analyze-and-a-pivotal-breakthrough"><i class="fa fa-check"></i><b>9.1.3</b> The shortage of numbers to analyze and a pivotal breakthrough</a></li>
<li class="chapter" data-level="9.1.4" data-path="DBMAnalysisBkgrnd.html"><a href="DBMAnalysisBkgrnd.html#organization-of-chapter"><i class="fa fa-check"></i><b>9.1.4</b> Organization of chapter</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="DBMAnalysisBkgrnd.html"><a href="DBMAnalysisBkgrnd.html#DBMAnalysisBkgrnd-random-fixed-factors"><i class="fa fa-check"></i><b>9.2</b> Random and fixed factors</a></li>
<li class="chapter" data-level="9.3" data-path="DBMAnalysisBkgrnd.html"><a href="DBMAnalysisBkgrnd.html#DBMAnalysisBkgrnd-reader-case-populations"><i class="fa fa-check"></i><b>9.3</b> Reader and case populations</a></li>
<li class="chapter" data-level="9.4" data-path="DBMAnalysisBkgrnd.html"><a href="DBMAnalysisBkgrnd.html#DBMAnalysisBkgrnd-threeAnalyses"><i class="fa fa-check"></i><b>9.4</b> Three types of analyses</a></li>
<li class="chapter" data-level="9.5" data-path="DBMAnalysisBkgrnd.html"><a href="DBMAnalysisBkgrnd.html#DBMAnalysisBkgrnd-approach"><i class="fa fa-check"></i><b>9.5</b> General approach</a></li>
<li class="chapter" data-level="9.6" data-path="DBMAnalysisBkgrnd.html"><a href="DBMAnalysisBkgrnd.html#DBMAnalysisBkgrnd-summary"><i class="fa fa-check"></i><b>9.6</b> Summary TBA</a></li>
<li class="chapter" data-level="9.7" data-path="DBMAnalysisBkgrnd.html"><a href="DBMAnalysisBkgrnd.html#DBMAnalysisBkgrnd-references"><i class="fa fa-check"></i><b>9.7</b> References</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="DBMAnalysisSigtesting.html"><a href="DBMAnalysisSigtesting.html"><i class="fa fa-check"></i><b>10</b> Significance Testing using the DBM Method</a>
<ul>
<li class="chapter" data-level="10.1" data-path="DBMAnalysisSigtesting.html"><a href="DBMAnalysisSigtesting.html#the-dbm-sampling-model"><i class="fa fa-check"></i><b>10.1</b> The DBM sampling model</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="DBMAnalysisSigtesting.html"><a href="DBMAnalysisSigtesting.html#explanation-of-terms-in-the-model"><i class="fa fa-check"></i><b>10.1.1</b> Explanation of terms in the model</a></li>
<li class="chapter" data-level="10.1.2" data-path="DBMAnalysisSigtesting.html"><a href="DBMAnalysisSigtesting.html#meanings-of-variance-components-in-the-dbm-model-tba-this-section-can-be-improved"><i class="fa fa-check"></i><b>10.1.2</b> Meanings of variance components in the DBM model (<strong>TBA this section can be improved</strong>)</a></li>
<li class="chapter" data-level="10.1.3" data-path="DBMAnalysisSigtesting.html"><a href="DBMAnalysisSigtesting.html#definitions-of-mean-squares"><i class="fa fa-check"></i><b>10.1.3</b> Definitions of mean-squares</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="DBMAnalysisSigtesting.html"><a href="DBMAnalysisSigtesting.html#expected-values-of-mean-squares"><i class="fa fa-check"></i><b>10.2</b> Expected values of mean squares</a></li>
<li class="chapter" data-level="10.3" data-path="DBMAnalysisSigtesting.html"><a href="DBMAnalysisSigtesting.html#DBMAnalysisSigtesting-RRRC-analysis"><i class="fa fa-check"></i><b>10.3</b> Random-reader random-case (RRRC) analysis</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="DBMAnalysisSigtesting.html"><a href="DBMAnalysisSigtesting.html#calculation-of-mean-squares-an-example"><i class="fa fa-check"></i><b>10.3.1</b> Calculation of mean squares: an example</a></li>
<li class="chapter" data-level="10.3.2" data-path="DBMAnalysisSigtesting.html"><a href="DBMAnalysisSigtesting.html#DBMAnalysisSigtesting-sig-testing"><i class="fa fa-check"></i><b>10.3.2</b> Significance testing</a></li>
<li class="chapter" data-level="10.3.3" data-path="DBMAnalysisSigtesting.html"><a href="DBMAnalysisSigtesting.html#the-satterthwaite-approximation"><i class="fa fa-check"></i><b>10.3.3</b> The Satterthwaite approximation</a></li>
<li class="chapter" data-level="10.3.4" data-path="DBMAnalysisSigtesting.html"><a href="DBMAnalysisSigtesting.html#decision-rules-p-value-and-confidence-intervals"><i class="fa fa-check"></i><b>10.3.4</b> Decision rules, p-value and confidence intervals</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="DBMAnalysisSigtesting.html"><a href="DBMAnalysisSigtesting.html#sample-size-estimation-for-random-reader-random-case-generalization"><i class="fa fa-check"></i><b>10.4</b> Sample size estimation for random-reader random-case generalization</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="DBMAnalysisSigtesting.html"><a href="DBMAnalysisSigtesting.html#the-non-centrality-parameter"><i class="fa fa-check"></i><b>10.4.1</b> The non-centrality parameter</a></li>
<li class="chapter" data-level="10.4.2" data-path="DBMAnalysisSigtesting.html"><a href="DBMAnalysisSigtesting.html#the-denominator-degrees-of-freedom"><i class="fa fa-check"></i><b>10.4.2</b> The denominator degrees of freedom</a></li>
<li class="chapter" data-level="10.4.3" data-path="DBMAnalysisSigtesting.html"><a href="DBMAnalysisSigtesting.html#example-of-sample-size-estimation-rrrc-generalization"><i class="fa fa-check"></i><b>10.4.3</b> Example of sample size estimation, RRRC generalization</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="DBMAnalysisSigtesting.html"><a href="DBMAnalysisSigtesting.html#significance-testing-and-sample-size-estimation-for-fixed-reader-random-case-generalization"><i class="fa fa-check"></i><b>10.5</b> Significance testing and sample size estimation for fixed-reader random-case generalization</a></li>
<li class="chapter" data-level="10.6" data-path="DBMAnalysisSigtesting.html"><a href="DBMAnalysisSigtesting.html#significance-testing-and-sample-size-estimation-for-random-reader-fixed-case-generalization"><i class="fa fa-check"></i><b>10.6</b> Significance testing and sample size estimation for random-reader fixed-case generalization</a></li>
<li class="chapter" data-level="10.7" data-path="DBMAnalysisSigtesting.html"><a href="DBMAnalysisSigtesting.html#DBMAnalysisSigtesting-summary"><i class="fa fa-check"></i><b>10.7</b> Summary TBA</a></li>
<li class="chapter" data-level="10.8" data-path="DBMAnalysisSigtesting.html"><a href="DBMAnalysisSigtesting.html#things-for-me-to-think-about"><i class="fa fa-check"></i><b>10.8</b> Things for me to think about</a>
<ul>
<li class="chapter" data-level="10.8.1" data-path="DBMAnalysisSigtesting.html"><a href="DBMAnalysisSigtesting.html#expected-values-of-mean-squares-1"><i class="fa fa-check"></i><b>10.8.1</b> Expected values of mean squares</a></li>
</ul></li>
<li class="chapter" data-level="10.9" data-path="DBMAnalysisSigtesting.html"><a href="DBMAnalysisSigtesting.html#DBMAnalysisSigtesting-references"><i class="fa fa-check"></i><b>10.9</b> References</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="DBMSpecialCases.html"><a href="DBMSpecialCases.html"><i class="fa fa-check"></i><b>11</b> DBM method special cases</a>
<ul>
<li class="chapter" data-level="11.1" data-path="DBMSpecialCases.html"><a href="DBMSpecialCases.html#FRRCDBMAnalysis"><i class="fa fa-check"></i><b>11.1</b> Fixed-reader random-case (FRRC) analysis</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="DBMSpecialCases.html"><a href="DBMSpecialCases.html#FRRCSingleReaderDBMAnalysis"><i class="fa fa-check"></i><b>11.1.1</b> Single-reader multiple-treatment analysis</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="DBMSpecialCases.html"><a href="DBMSpecialCases.html#DBMSpecialCases-RRFCAnalysis"><i class="fa fa-check"></i><b>11.2</b> Random-reader fixed-case (RRFC) analysis</a></li>
<li class="chapter" data-level="11.3" data-path="DBMSpecialCases.html"><a href="DBMSpecialCases.html#DBMSpecialCases-references"><i class="fa fa-check"></i><b>11.3</b> References</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="ORMethodIntro.html"><a href="ORMethodIntro.html"><i class="fa fa-check"></i><b>12</b> Introduction to the Obuchowski-Rockette method</a>
<ul>
<li class="chapter" data-level="12.1" data-path="ORMethodIntro.html"><a href="ORMethodIntro.html#ORMethodIntro-introduction"><i class="fa fa-check"></i><b>12.1</b> Introduction</a></li>
<li class="chapter" data-level="12.2" data-path="ORMethodIntro.html"><a href="ORMethodIntro.html#OR1RMTModel"><i class="fa fa-check"></i><b>12.2</b> Single-reader multiple-treatment</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="ORMethodIntro.html"><a href="ORMethodIntro.html#definitions-of-covariance-and-correlation"><i class="fa fa-check"></i><b>12.2.1</b> Definitions of covariance and correlation</a></li>
<li class="chapter" data-level="12.2.2" data-path="ORMethodIntro.html"><a href="ORMethodIntro.html#special-case-when-variables-have-equal-variances"><i class="fa fa-check"></i><b>12.2.2</b> Special case when variables have equal variances</a></li>
<li class="chapter" data-level="12.2.3" data-path="ORMethodIntro.html"><a href="ORMethodIntro.html#estimating-the-variance-covariance-matrix"><i class="fa fa-check"></i><b>12.2.3</b> Estimating the variance-covariance matrix</a></li>
<li class="chapter" data-level="12.2.4" data-path="ORMethodIntro.html"><a href="ORMethodIntro.html#the-variance-inflation-factor"><i class="fa fa-check"></i><b>12.2.4</b> The variance inflation factor</a></li>
<li class="chapter" data-level="12.2.5" data-path="ORMethodIntro.html"><a href="ORMethodIntro.html#meaning-of-the-covariance-matrix-in-eqn.-refeqexamplesigma"><i class="fa fa-check"></i><b>12.2.5</b> Meaning of the covariance matrix in Eqn. @ref(eq:ExampleSigma)</a></li>
<li class="chapter" data-level="12.2.6" data-path="ORMethodIntro.html"><a href="ORMethodIntro.html#code-illustrating-the-covariance-matrix"><i class="fa fa-check"></i><b>12.2.6</b> Code illustrating the covariance matrix</a></li>
<li class="chapter" data-level="12.2.7" data-path="ORMethodIntro.html"><a href="ORMethodIntro.html#SignificanceTesting1ROR"><i class="fa fa-check"></i><b>12.2.7</b> Significance testing</a></li>
<li class="chapter" data-level="12.2.8" data-path="ORMethodIntro.html"><a href="ORMethodIntro.html#ORMethodIntro-pvalue-ci"><i class="fa fa-check"></i><b>12.2.8</b> p-value and confidence interval</a></li>
<li class="chapter" data-level="12.2.9" data-path="ORMethodIntro.html"><a href="ORMethodIntro.html#ORMethodIntro-CompareDBM2OR41R"><i class="fa fa-check"></i><b>12.2.9</b> Comparing DBM to Obuchowski and Rockette for single-reader multiple-treatments</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="ORMethodIntro.html"><a href="ORMethodIntro.html#SignificanceTestingORMRMC"><i class="fa fa-check"></i><b>12.3</b> Multiple-reader multiple-treatment</a>
<ul>
<li class="chapter" data-level="12.3.1" data-path="ORMethodIntro.html"><a href="ORMethodIntro.html#StrCovMatrix"><i class="fa fa-check"></i><b>12.3.1</b> Structure of the covariance matrix</a></li>
<li class="chapter" data-level="12.3.2" data-path="ORMethodIntro.html"><a href="ORMethodIntro.html#PhysicalMeaningsOfCovMatrix"><i class="fa fa-check"></i><b>12.3.2</b> Physical meanings of the covariance terms</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="ORMethodIntro.html"><a href="ORMethodIntro.html#ORMethodIntro-Summary"><i class="fa fa-check"></i><b>12.4</b> Summary</a></li>
<li class="chapter" data-level="12.5" data-path="ORMethodIntro.html"><a href="ORMethodIntro.html#ORMethodIntro-Discussion"><i class="fa fa-check"></i><b>12.5</b> Discussion</a></li>
<li class="chapter" data-level="12.6" data-path="ORMethodIntro.html"><a href="ORMethodIntro.html#ORMethodIntro-references"><i class="fa fa-check"></i><b>12.6</b> References</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="ORAnalysisSigTesting.html"><a href="ORAnalysisSigTesting.html"><i class="fa fa-check"></i><b>13</b> Obuchowski Rockette (OR) Analysis</a>
<ul>
<li class="chapter" data-level="13.1" data-path="ORAnalysisSigTesting.html"><a href="ORAnalysisSigTesting.html#ORAnalysisSigTesting-introduction"><i class="fa fa-check"></i><b>13.1</b> Introduction</a></li>
<li class="chapter" data-level="13.2" data-path="ORAnalysisSigTesting.html"><a href="ORAnalysisSigTesting.html#OR_RRRC"><i class="fa fa-check"></i><b>13.2</b> Random-reader random-case</a>
<ul>
<li class="chapter" data-level="13.2.1" data-path="ORAnalysisSigTesting.html"><a href="ORAnalysisSigTesting.html#TwoAnecdotes"><i class="fa fa-check"></i><b>13.2.1</b> Two anecdotes</a></li>
<li class="chapter" data-level="13.2.2" data-path="ORAnalysisSigTesting.html"><a href="ORAnalysisSigTesting.html#Hills-ddf"><i class="fa fa-check"></i><b>13.2.2</b> Hillis ddf</a></li>
<li class="chapter" data-level="13.2.3" data-path="ORAnalysisSigTesting.html"><a href="ORAnalysisSigTesting.html#decision-rule-p-value-and-confidence-interval"><i class="fa fa-check"></i><b>13.2.3</b> Decision rule, p-value and confidence interval</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="ORAnalysisSigTesting.html"><a href="ORAnalysisSigTesting.html#OR-FRRC"><i class="fa fa-check"></i><b>13.3</b> Fixed-reader random-case</a></li>
<li class="chapter" data-level="13.4" data-path="ORAnalysisSigTesting.html"><a href="ORAnalysisSigTesting.html#ORAnalysisSigTesting-RRFCAnalysis"><i class="fa fa-check"></i><b>13.4</b> Random-reader fixed-case</a></li>
<li class="chapter" data-level="13.5" data-path="ORAnalysisSigTesting.html"><a href="ORAnalysisSigTesting.html#ORAnalysisSigTesting-Summary"><i class="fa fa-check"></i><b>13.5</b> Summary</a></li>
<li class="chapter" data-level="13.6" data-path="ORAnalysisSigTesting.html"><a href="ORAnalysisSigTesting.html#ORAnalysisSigTesting-Discussion"><i class="fa fa-check"></i><b>13.6</b> Discussion</a></li>
<li class="chapter" data-level="13.7" data-path="ORAnalysisSigTesting.html"><a href="ORAnalysisSigTesting.html#ORAnalysisSigTesting-references"><i class="fa fa-check"></i><b>13.7</b> References</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="ORApplications.html"><a href="ORApplications.html"><i class="fa fa-check"></i><b>14</b> Obuchowski Rockette Applications</a>
<ul>
<li class="chapter" data-level="14.1" data-path="ORApplications.html"><a href="ORApplications.html#ORApplications-introduction"><i class="fa fa-check"></i><b>14.1</b> Introduction</a></li>
<li class="chapter" data-level="14.2" data-path="ORApplications.html"><a href="ORApplications.html#ORApplications-dataset02-hand"><i class="fa fa-check"></i><b>14.2</b> Hand calculation</a>
<ul>
<li class="chapter" data-level="14.2.1" data-path="ORApplications.html"><a href="ORApplications.html#ORApplications-RRRC-dataset02-hand"><i class="fa fa-check"></i><b>14.2.1</b> Random-Reader Random-Case (RRRC) analysis</a></li>
<li class="chapter" data-level="14.2.2" data-path="ORApplications.html"><a href="ORApplications.html#ORApplications-FRRC-dataset02-hand"><i class="fa fa-check"></i><b>14.2.2</b> Fixed-Reader Random-Case (FRRC) analysis</a></li>
<li class="chapter" data-level="14.2.3" data-path="ORApplications.html"><a href="ORApplications.html#ORApplications-RRFC-dataset02-hand"><i class="fa fa-check"></i><b>14.2.3</b> Random-Reader Fixed-Case (RRFC) analysis</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="ORApplications.html"><a href="ORApplications.html#ORApplications-dataset02-RJafroc"><i class="fa fa-check"></i><b>14.3</b> RJafroc: dataset02</a>
<ul>
<li class="chapter" data-level="14.3.1" data-path="ORApplications.html"><a href="ORApplications.html#ORApplications-RRRC-dataset02-RJafroc"><i class="fa fa-check"></i><b>14.3.1</b> Random-Reader Random-Case (RRRC) analysis</a></li>
<li class="chapter" data-level="14.3.2" data-path="ORApplications.html"><a href="ORApplications.html#ORApplications-FRRC-dataset02-RJafroc"><i class="fa fa-check"></i><b>14.3.2</b> Fixed-Reader Random-Case (FRRC) analysis</a></li>
<li class="chapter" data-level="14.3.3" data-path="ORApplications.html"><a href="ORApplications.html#ORApplications-RRFC-dataset02-RJafroc"><i class="fa fa-check"></i><b>14.3.3</b> Random-Reader Fixed-Case (RRFC) analysis</a></li>
</ul></li>
<li class="chapter" data-level="14.4" data-path="ORApplications.html"><a href="ORApplications.html#ORApplications-dataset04-RJafroc"><i class="fa fa-check"></i><b>14.4</b> RJafroc: dataset04</a>
<ul>
<li class="chapter" data-level="14.4.1" data-path="ORApplications.html"><a href="ORApplications.html#ORApplications-RRRC-dataset04"><i class="fa fa-check"></i><b>14.4.1</b> Random-Reader Random-Case (RRRC) analysis</a></li>
<li class="chapter" data-level="14.4.2" data-path="ORApplications.html"><a href="ORApplications.html#ORApplications-FRRC-dataset04"><i class="fa fa-check"></i><b>14.4.2</b> Fixed-Reader Random-Case (FRRC) analysis</a></li>
<li class="chapter" data-level="14.4.3" data-path="ORApplications.html"><a href="ORApplications.html#ORApplications-RRFC-dataset04"><i class="fa fa-check"></i><b>14.4.3</b> Random-Reader Fixed-Case (RRFC) analysis</a></li>
</ul></li>
<li class="chapter" data-level="14.5" data-path="ORApplications.html"><a href="ORApplications.html#ORApplications-dataset04-FROC-RJafroc"><i class="fa fa-check"></i><b>14.5</b> RJafroc: dataset04, FROC</a>
<ul>
<li class="chapter" data-level="14.5.1" data-path="ORApplications.html"><a href="ORApplications.html#ORApplications-RRRC-dataset04-FROC"><i class="fa fa-check"></i><b>14.5.1</b> Random-Reader Random-Case (RRRC) analysis</a></li>
<li class="chapter" data-level="14.5.2" data-path="ORApplications.html"><a href="ORApplications.html#ORApplications-FRRC-dataset04-FROC"><i class="fa fa-check"></i><b>14.5.2</b> Fixed-Reader Random-Case (FRRC) analysis</a></li>
<li class="chapter" data-level="14.5.3" data-path="ORApplications.html"><a href="ORApplications.html#ORApplications-RRFC-dataset04-FROC"><i class="fa fa-check"></i><b>14.5.3</b> Random-Reader Fixed-Case (RRFC) analysis</a></li>
</ul></li>
<li class="chapter" data-level="14.6" data-path="ORApplications.html"><a href="ORApplications.html#ORApplications-dataset04-FROC-DBM-RJafroc"><i class="fa fa-check"></i><b>14.6</b> RJafroc: dataset04, FROC/DBM</a>
<ul>
<li class="chapter" data-level="14.6.1" data-path="ORApplications.html"><a href="ORApplications.html#ORApplications-RRRC-dataset04-FROC-DBM"><i class="fa fa-check"></i><b>14.6.1</b> Random-Reader Random-Case (RRRC) analysis</a></li>
<li class="chapter" data-level="14.6.2" data-path="ORApplications.html"><a href="ORApplications.html#ORApplications-FRRC-dataset04-FROC-DBM"><i class="fa fa-check"></i><b>14.6.2</b> Fixed-Reader Random-Case (FRRC) analysis</a></li>
<li class="chapter" data-level="14.6.3" data-path="ORApplications.html"><a href="ORApplications.html#ORApplications-RRFC-dataset04-FROC-DBM"><i class="fa fa-check"></i><b>14.6.3</b> Random-Reader Fixed-Case (RRFC) analysis</a></li>
</ul></li>
<li class="chapter" data-level="14.7" data-path="ORApplications.html"><a href="ORApplications.html#ORApplications-Summary"><i class="fa fa-check"></i><b>14.7</b> Summary</a></li>
<li class="chapter" data-level="14.8" data-path="ORApplications.html"><a href="ORApplications.html#ORApplications-Discussion"><i class="fa fa-check"></i><b>14.8</b> Discussion</a></li>
<li class="chapter" data-level="14.9" data-path="ORApplications.html"><a href="ORApplications.html#ToMullOver1-tentative"><i class="fa fa-check"></i><b>14.9</b> Tentative</a></li>
<li class="chapter" data-level="14.10" data-path="ORApplications.html"><a href="ORApplications.html#ORApplications-references"><i class="fa fa-check"></i><b>14.10</b> References</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="RocSampleSizeDBM.html"><a href="RocSampleSizeDBM.html"><i class="fa fa-check"></i><b>15</b> Sample size estimation for ROC studies DBM method</a>
<ul>
<li class="chapter" data-level="15.1" data-path="RocSampleSizeDBM.html"><a href="RocSampleSizeDBM.html#RocSampleSizeDBM-introduction"><i class="fa fa-check"></i><b>15.1</b> Introduction</a></li>
<li class="chapter" data-level="15.2" data-path="RocSampleSizeDBM.html"><a href="RocSampleSizeDBM.html#StatPower1"><i class="fa fa-check"></i><b>15.2</b> Statistical Power</a>
<ul>
<li class="chapter" data-level="15.2.1" data-path="RocSampleSizeDBM.html"><a href="RocSampleSizeDBM.html#observed-vs.-anticipated-effect-size"><i class="fa fa-check"></i><b>15.2.1</b> Observed vs. anticipated effect-size</a></li>
<li class="chapter" data-level="15.2.2" data-path="RocSampleSizeDBM.html"><a href="RocSampleSizeDBM.html#RocSampleSizeDBM-dependence-of-stats-power"><i class="fa fa-check"></i><b>15.2.2</b> Dependence of statistical power on estimates of model parameters</a></li>
<li class="chapter" data-level="15.2.3" data-path="RocSampleSizeDBM.html"><a href="RocSampleSizeDBM.html#RocSampleSizeDBM-RRRC-sample-size-estimation"><i class="fa fa-check"></i><b>15.2.3</b> Formulae for random-reader random-case (RRRC) sample size estimation</a></li>
<li class="chapter" data-level="15.2.4" data-path="RocSampleSizeDBM.html"><a href="RocSampleSizeDBM.html#RocSampleSizeDBM-sig-testing"><i class="fa fa-check"></i><b>15.2.4</b> Significance testing</a></li>
<li class="chapter" data-level="15.2.5" data-path="RocSampleSizeDBM.html"><a href="RocSampleSizeDBM.html#RocSampleSizeDBM-pvalue-ci"><i class="fa fa-check"></i><b>15.2.5</b> p-value and confidence interval</a></li>
<li class="chapter" data-level="15.2.6" data-path="RocSampleSizeDBM.html"><a href="RocSampleSizeDBM.html#RocSampleSizeDBM-CompareDBM2OR"><i class="fa fa-check"></i><b>15.2.6</b> Comparing DBM to Obuchowski and Rockette for single-reader multiple-treatments</a></li>
</ul></li>
<li class="chapter" data-level="15.3" data-path="RocSampleSizeDBM.html"><a href="RocSampleSizeDBM.html#RocSampleSizeDBM-FRRC-sample-size-estimation"><i class="fa fa-check"></i><b>15.3</b> Formulae for fixed-reader random-case (FRRC) sample size estimation</a>
<ul>
<li class="chapter" data-level="15.3.1" data-path="RocSampleSizeDBM.html"><a href="RocSampleSizeDBM.html#RocSampleSizeDBM-RRFC-sample-size-estimation"><i class="fa fa-check"></i><b>15.3.1</b> Formulae for random-reader fixed-case (RRFC) sample size estimation</a></li>
<li class="chapter" data-level="15.3.2" data-path="RocSampleSizeDBM.html"><a href="RocSampleSizeDBM.html#RocSampleSizeDBM-FRRCAnalysis"><i class="fa fa-check"></i><b>15.3.2</b> Fixed-reader random-case (FRRC) analysis TBA</a></li>
<li class="chapter" data-level="15.3.3" data-path="RocSampleSizeDBM.html"><a href="RocSampleSizeDBM.html#RocSampleSizeDBM-RRFCAnalysis"><i class="fa fa-check"></i><b>15.3.3</b> Random-reader fixed-case (RRFC) analysis</a></li>
<li class="chapter" data-level="15.3.4" data-path="RocSampleSizeDBM.html"><a href="RocSampleSizeDBM.html#RocSampleSizeDBM-STMRAnalysis"><i class="fa fa-check"></i><b>15.3.4</b> Single-treatment multiple-reader analysis</a></li>
</ul></li>
<li class="chapter" data-level="15.4" data-path="RocSampleSizeDBM.html"><a href="RocSampleSizeDBM.html#discussionsummary2"><i class="fa fa-check"></i><b>15.4</b> Discussion/Summary/2</a></li>
<li class="chapter" data-level="15.5" data-path="RocSampleSizeDBM.html"><a href="RocSampleSizeDBM.html#RocSampleSizeDBM-references"><i class="fa fa-check"></i><b>15.5</b> References</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="RocSampleSizeOR.html"><a href="RocSampleSizeOR.html"><i class="fa fa-check"></i><b>16</b> Sample size estimation for ROC studies OR method</a>
<ul>
<li class="chapter" data-level="16.1" data-path="RocSampleSizeOR.html"><a href="RocSampleSizeOR.html#RocSampleSizeOR-introduction"><i class="fa fa-check"></i><b>16.1</b> Introduction</a></li>
<li class="chapter" data-level="16.2" data-path="RocSampleSizeOR.html"><a href="RocSampleSizeOR.html#StatPower2"><i class="fa fa-check"></i><b>16.2</b> Statistical Power</a>
<ul>
<li class="chapter" data-level="16.2.1" data-path="RocSampleSizeOR.html"><a href="RocSampleSizeOR.html#sample-size-estimation-for-random-reader-random-cases"><i class="fa fa-check"></i><b>16.2.1</b> Sample size estimation for random-reader random-cases</a></li>
<li class="chapter" data-level="16.2.2" data-path="RocSampleSizeOR.html"><a href="RocSampleSizeOR.html#RocSampleSizeOR-dependence-of-stats-power"><i class="fa fa-check"></i><b>16.2.2</b> Dependence of statistical power on estimates of model parameters</a></li>
<li class="chapter" data-level="16.2.3" data-path="RocSampleSizeOR.html"><a href="RocSampleSizeOR.html#RocSampleSizeOR-RRRC-sample-size-estimation"><i class="fa fa-check"></i><b>16.2.3</b> Formulae for random-reader random-case (RRRC) sample size estimation</a></li>
<li class="chapter" data-level="16.2.4" data-path="RocSampleSizeOR.html"><a href="RocSampleSizeOR.html#RocSampleSizeOR-sig-testing"><i class="fa fa-check"></i><b>16.2.4</b> Significance testing</a></li>
<li class="chapter" data-level="16.2.5" data-path="RocSampleSizeOR.html"><a href="RocSampleSizeOR.html#RocSampleSizeOR-pvalue-ci"><i class="fa fa-check"></i><b>16.2.5</b> p-value and confidence interval</a></li>
<li class="chapter" data-level="16.2.6" data-path="RocSampleSizeOR.html"><a href="RocSampleSizeOR.html#RocSampleSizeOR-CompareDBM2OR"><i class="fa fa-check"></i><b>16.2.6</b> Comparing DBM to Obuchowski and Rockette for single-reader multiple-treatments</a></li>
</ul></li>
<li class="chapter" data-level="16.3" data-path="RocSampleSizeOR.html"><a href="RocSampleSizeOR.html#RocSampleSizeOR-FRRC-sample-size-estimation"><i class="fa fa-check"></i><b>16.3</b> Formulae for fixed-reader random-case (FRRC) sample size estimation</a>
<ul>
<li class="chapter" data-level="16.3.1" data-path="RocSampleSizeOR.html"><a href="RocSampleSizeOR.html#RocSampleSizeOR-RRFC-sample-size-estimation"><i class="fa fa-check"></i><b>16.3.1</b> Formulae for random-reader fixed-case (RRFC) sample size estimation</a></li>
<li class="chapter" data-level="16.3.2" data-path="RocSampleSizeOR.html"><a href="RocSampleSizeOR.html#example-1"><i class="fa fa-check"></i><b>16.3.2</b> Example 1</a></li>
<li class="chapter" data-level="16.3.3" data-path="RocSampleSizeOR.html"><a href="RocSampleSizeOR.html#RocSampleSizeOR-FRRCAnalysis"><i class="fa fa-check"></i><b>16.3.3</b> Fixed-reader random-case (FRRC) analysis</a></li>
<li class="chapter" data-level="16.3.4" data-path="RocSampleSizeOR.html"><a href="RocSampleSizeOR.html#RocSampleSizeOR-RRFCAnalysis"><i class="fa fa-check"></i><b>16.3.4</b> Random-reader fixed-case (RRFC) analysis</a></li>
<li class="chapter" data-level="16.3.5" data-path="RocSampleSizeOR.html"><a href="RocSampleSizeOR.html#RocSampleSizeOR-STMRAnalysis"><i class="fa fa-check"></i><b>16.3.5</b> Single-treatment multiple-reader analysis</a></li>
</ul></li>
<li class="chapter" data-level="16.4" data-path="RocSampleSizeOR.html"><a href="RocSampleSizeOR.html#discussionsummary3"><i class="fa fa-check"></i><b>16.4</b> Discussion/Summary/3</a></li>
<li class="chapter" data-level="16.5" data-path="RocSampleSizeOR.html"><a href="RocSampleSizeOR.html#RocSampleSizeOR-references"><i class="fa fa-check"></i><b>16.5</b> References</a></li>
</ul></li>
<li class="part"><span><b>FROC paradigm</b></span></li>
<li class="chapter" data-level="17" data-path="froc-paradigm.html"><a href="froc-paradigm.html"><i class="fa fa-check"></i><b>17</b> The FROC paradigm</a>
<ul>
<li class="chapter" data-level="17.1" data-path="froc-paradigm.html"><a href="froc-paradigm.html#froc-paradigmIntro"><i class="fa fa-check"></i><b>17.1</b> Introduction</a></li>
<li class="chapter" data-level="17.2" data-path="froc-paradigm.html"><a href="froc-paradigm.html#location-specific-paradigms"><i class="fa fa-check"></i><b>17.2</b> Location specific paradigms</a></li>
<li class="chapter" data-level="17.3" data-path="froc-paradigm.html"><a href="froc-paradigm.html#the-froc-paradigm-as-a-search-task"><i class="fa fa-check"></i><b>17.3</b> The FROC paradigm as a search task</a>
<ul>
<li class="chapter" data-level="17.3.1" data-path="froc-paradigm.html"><a href="froc-paradigm.html#froc-paradigm-scoring-the-data"><i class="fa fa-check"></i><b>17.3.1</b> Proximity criterion and scoring the data</a></li>
<li class="chapter" data-level="17.3.2" data-path="froc-paradigm.html"><a href="froc-paradigm.html#multiple-marks-in-the-same-vicinity"><i class="fa fa-check"></i><b>17.3.2</b> Multiple marks in the same vicinity</a></li>
<li class="chapter" data-level="17.3.3" data-path="froc-paradigm.html"><a href="froc-paradigm.html#historical-context"><i class="fa fa-check"></i><b>17.3.3</b> Historical context</a></li>
</ul></li>
<li class="chapter" data-level="17.4" data-path="froc-paradigm.html"><a href="froc-paradigm.html#a-pioneering-froc-study-in-medical-imaging"><i class="fa fa-check"></i><b>17.4</b> A pioneering FROC study in medical imaging</a>
<ul>
<li class="chapter" data-level="17.4.1" data-path="froc-paradigm.html"><a href="froc-paradigm.html#image-preparation"><i class="fa fa-check"></i><b>17.4.1</b> Image preparation</a></li>
<li class="chapter" data-level="17.4.2" data-path="froc-paradigm.html"><a href="froc-paradigm.html#image-interpretation-and-the-1-rating"><i class="fa fa-check"></i><b>17.4.2</b> Image Interpretation and the 1-rating</a></li>
<li class="chapter" data-level="17.4.3" data-path="froc-paradigm.html"><a href="froc-paradigm.html#scoring-the-data"><i class="fa fa-check"></i><b>17.4.3</b> Scoring the data</a></li>
<li class="chapter" data-level="17.4.4" data-path="froc-paradigm.html"><a href="froc-paradigm.html#the-free-response-receiver-operating-characteristic-froc-plot"><i class="fa fa-check"></i><b>17.4.4</b> The free-response receiver operating characteristic (FROC) plot</a></li>
<li class="chapter" data-level="17.4.5" data-path="froc-paradigm.html"><a href="froc-paradigm.html#population-and-binned-froc-plots"><i class="fa fa-check"></i><b>17.4.5</b> Population and binned FROC plots</a></li>
<li class="chapter" data-level="17.4.6" data-path="froc-paradigm.html"><a href="froc-paradigm.html#perceptual-snr"><i class="fa fa-check"></i><b>17.4.6</b> Perceptual SNR</a></li>
</ul></li>
<li class="chapter" data-level="17.5" data-path="froc-paradigm.html"><a href="froc-paradigm.html#the-solar-analogy-search-vs.-classification-performance"><i class="fa fa-check"></i><b>17.5</b> The “solar” analogy: search vs. classification performance</a></li>
<li class="chapter" data-level="17.6" data-path="froc-paradigm.html"><a href="froc-paradigm.html#froc-paradigm-Discussion"><i class="fa fa-check"></i><b>17.6</b> Discussion</a></li>
<li class="chapter" data-level="17.7" data-path="froc-paradigm.html"><a href="froc-paradigm.html#froc-paradigm-references"><i class="fa fa-check"></i><b>17.7</b> References</a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="froc-empirical.html"><a href="froc-empirical.html"><i class="fa fa-check"></i><b>18</b> Empirical plots</a>
<ul>
<li class="chapter" data-level="18.1" data-path="froc-empirical.html"><a href="froc-empirical.html#froc-empirical-intro"><i class="fa fa-check"></i><b>18.1</b> Introduction TBA</a></li>
<li class="chapter" data-level="18.2" data-path="froc-empirical.html"><a href="froc-empirical.html#froc-empirical-mark-rating-pairs"><i class="fa fa-check"></i><b>18.2</b> Mark rating pairs</a>
<ul>
<li class="chapter" data-level="18.2.1" data-path="froc-empirical.html"><a href="froc-empirical.html#latent-vs.-actual-marks"><i class="fa fa-check"></i><b>18.2.1</b> Latent vs. actual marks</a></li>
<li class="chapter" data-level="18.2.2" data-path="froc-empirical.html"><a href="froc-empirical.html#binning-rule"><i class="fa fa-check"></i><b>18.2.2</b> Binning rule</a></li>
</ul></li>
<li class="chapter" data-level="18.3" data-path="froc-empirical.html"><a href="froc-empirical.html#froc-empirical-notation"><i class="fa fa-check"></i><b>18.3</b> FROC notation</a>
<ul>
<li class="chapter" data-level="18.3.1" data-path="froc-empirical.html"><a href="froc-empirical.html#comments-on-table-reftabfroc-empirical-notation"><i class="fa fa-check"></i><b>18.3.1</b> Comments on Table @ref(tab:froc-empirical-notation)</a></li>
<li class="chapter" data-level="18.3.2" data-path="froc-empirical.html"><a href="froc-empirical.html#discussion-cases-with-zero-latent-nl-marks"><i class="fa fa-check"></i><b>18.3.2</b> Discussion: cases with zero latent NL marks</a></li>
</ul></li>
<li class="chapter" data-level="18.4" data-path="froc-empirical.html"><a href="froc-empirical.html#froc-empirical-froc-plot"><i class="fa fa-check"></i><b>18.4</b> The empirical FROC</a>
<ul>
<li class="chapter" data-level="18.4.1" data-path="froc-empirical.html"><a href="froc-empirical.html#froc-empirical-definition-auc-FROC"><i class="fa fa-check"></i><b>18.4.1</b> Definition</a></li>
<li class="chapter" data-level="18.4.2" data-path="froc-empirical.html"><a href="froc-empirical.html#froc-empirical-origin-trivial-point"><i class="fa fa-check"></i><b>18.4.2</b> The origin, a trivial point</a></li>
<li class="chapter" data-level="18.4.3" data-path="froc-empirical.html"><a href="froc-empirical.html#froc-empirical-end-point"><i class="fa fa-check"></i><b>18.4.3</b> The observed end-point and its semi-constrained property</a></li>
<li class="chapter" data-level="18.4.4" data-path="froc-empirical.html"><a href="froc-empirical.html#froc-empirical-froc-plot-futility-extrapolation"><i class="fa fa-check"></i><b>18.4.4</b> Futility of extrapolation outside the observed end-point</a></li>
</ul></li>
<li class="chapter" data-level="18.5" data-path="froc-empirical.html"><a href="froc-empirical.html#froc-empirical-ROC"><i class="fa fa-check"></i><b>18.5</b> The inferred ROC plot</a>
<ul>
<li class="chapter" data-level="18.5.1" data-path="froc-empirical.html"><a href="froc-empirical.html#inferred-roc-rating"><i class="fa fa-check"></i><b>18.5.1</b> Inferred-ROC rating</a></li>
<li class="chapter" data-level="18.5.2" data-path="froc-empirical.html"><a href="froc-empirical.html#inferred-fpf"><i class="fa fa-check"></i><b>18.5.2</b> Inferred FPF</a></li>
<li class="chapter" data-level="18.5.3" data-path="froc-empirical.html"><a href="froc-empirical.html#inferred-tpf"><i class="fa fa-check"></i><b>18.5.3</b> Inferred TPF</a></li>
<li class="chapter" data-level="18.5.4" data-path="froc-empirical.html"><a href="froc-empirical.html#froc-empirical-definition-auc-ROC"><i class="fa fa-check"></i><b>18.5.4</b> Definition</a></li>
</ul></li>
<li class="chapter" data-level="18.6" data-path="froc-empirical.html"><a href="froc-empirical.html#froc-empirical-AFROC"><i class="fa fa-check"></i><b>18.6</b> The alternative FROC (AFROC) plot</a>
<ul>
<li class="chapter" data-level="18.6.1" data-path="froc-empirical.html"><a href="froc-empirical.html#froc-empirical-definition-auc-AFROC"><i class="fa fa-check"></i><b>18.6.1</b> Definition</a></li>
<li class="chapter" data-level="18.6.2" data-path="froc-empirical.html"><a href="froc-empirical.html#froc-empirical-AFROC-constrained"><i class="fa fa-check"></i><b>18.6.2</b> The constrained observed end-point of the AFROC</a></li>
</ul></li>
<li class="chapter" data-level="18.7" data-path="froc-empirical.html"><a href="froc-empirical.html#froc-empirical-wAFROC"><i class="fa fa-check"></i><b>18.7</b> The weighted-AFROC (wAFROC) plot</a>
<ul>
<li class="chapter" data-level="18.7.1" data-path="froc-empirical.html"><a href="froc-empirical.html#froc-empirical-definition-auc-wAFROC"><i class="fa fa-check"></i><b>18.7.1</b> Definition</a></li>
</ul></li>
<li class="chapter" data-level="18.8" data-path="froc-empirical.html"><a href="froc-empirical.html#froc-empirical-AFROC1"><i class="fa fa-check"></i><b>18.8</b> The AFROC1 plot</a>
<ul>
<li class="chapter" data-level="18.8.1" data-path="froc-empirical.html"><a href="froc-empirical.html#froc-empirical-definition-auc-AFROC1"><i class="fa fa-check"></i><b>18.8.1</b> Definition</a></li>
</ul></li>
<li class="chapter" data-level="18.9" data-path="froc-empirical.html"><a href="froc-empirical.html#froc-empirical-wAFROC1"><i class="fa fa-check"></i><b>18.9</b> The weighted-AFROC1 (wAFROC1) plot</a>
<ul>
<li class="chapter" data-level="18.9.1" data-path="froc-empirical.html"><a href="froc-empirical.html#froc-empirical-definition-auc-wAFROC1"><i class="fa fa-check"></i><b>18.9.1</b> Definition</a></li>
</ul></li>
<li class="chapter" data-level="18.10" data-path="froc-empirical.html"><a href="froc-empirical.html#froc-empirical-EFROC"><i class="fa fa-check"></i><b>18.10</b> The EFROC plot</a>
<ul>
<li class="chapter" data-level="18.10.1" data-path="froc-empirical.html"><a href="froc-empirical.html#froc-empirical-definition-auc-EFROC"><i class="fa fa-check"></i><b>18.10.1</b> Definition</a></li>
</ul></li>
<li class="chapter" data-level="18.11" data-path="froc-empirical.html"><a href="froc-empirical.html#the-chance-level-froc-and-afroc"><i class="fa fa-check"></i><b>18.11</b> The chance level FROC and AFROC</a></li>
<li class="chapter" data-level="18.12" data-path="froc-empirical.html"><a href="froc-empirical.html#raw-frocafrocroc-plots"><i class="fa fa-check"></i><b>18.12</b> Raw FROC/AFROC/ROC plots</a>
<ul>
<li class="chapter" data-level="18.12.1" data-path="froc-empirical.html"><a href="froc-empirical.html#raw-plots-code1"><i class="fa fa-check"></i><b>18.12.1</b> Code for raw plots</a></li>
<li class="chapter" data-level="18.12.2" data-path="froc-empirical.html"><a href="froc-empirical.html#explanation-of-the-code"><i class="fa fa-check"></i><b>18.12.2</b> Explanation of the code</a></li>
<li class="chapter" data-level="18.12.3" data-path="froc-empirical.html"><a href="froc-empirical.html#explanation-of-the-code-continued"><i class="fa fa-check"></i><b>18.12.3</b> Explanation of the code, continued</a></li>
<li class="chapter" data-level="18.12.4" data-path="froc-empirical.html"><a href="froc-empirical.html#key-differences-from-the-roc-paradigm"><i class="fa fa-check"></i><b>18.12.4</b> Key differences from the ROC paradigm:</a></li>
</ul></li>
<li class="chapter" data-level="18.13" data-path="froc-empirical.html"><a href="froc-empirical.html#binned-frocafrocroc-plots"><i class="fa fa-check"></i><b>18.13</b> Binned FROC/AFROC/ROC plots</a>
<ul>
<li class="chapter" data-level="18.13.1" data-path="froc-empirical.html"><a href="froc-empirical.html#binned-plots-code1"><i class="fa fa-check"></i><b>18.13.1</b> Code for binned plots</a></li>
<li class="chapter" data-level="18.13.2" data-path="froc-empirical.html"><a href="froc-empirical.html#structure-of-the-binned-data"><i class="fa fa-check"></i><b>18.13.2</b> Structure of the binned data</a></li>
</ul></li>
<li class="chapter" data-level="18.14" data-path="froc-empirical.html"><a href="froc-empirical.html#misconceptions-about-location-level-true-negatives"><i class="fa fa-check"></i><b>18.14</b> Misconceptions about location-level “true-negatives”</a></li>
<li class="chapter" data-level="18.15" data-path="froc-empirical.html"><a href="froc-empirical.html#comments-and-recommendations"><i class="fa fa-check"></i><b>18.15</b> Comments and recommendations</a>
<ul>
<li class="chapter" data-level="18.15.1" data-path="froc-empirical.html"><a href="froc-empirical.html#why-not-use-nls-on-diseased-cases"><i class="fa fa-check"></i><b>18.15.1</b> Why not use NLs on diseased cases?</a></li>
<li class="chapter" data-level="18.15.2" data-path="froc-empirical.html"><a href="froc-empirical.html#recommendations"><i class="fa fa-check"></i><b>18.15.2</b> Recommendations</a></li>
</ul></li>
<li class="chapter" data-level="18.16" data-path="froc-empirical.html"><a href="froc-empirical.html#froc-empirical-Discussion"><i class="fa fa-check"></i><b>18.16</b> Discussion</a></li>
<li class="chapter" data-level="18.17" data-path="froc-empirical.html"><a href="froc-empirical.html#froc-empirical-miscellaneous"><i class="fa fa-check"></i><b>18.17</b> Miscellaneous</a>
<ul>
<li class="chapter" data-level="18.17.1" data-path="froc-empirical.html"><a href="froc-empirical.html#froc-empirical-case-vs-view"><i class="fa fa-check"></i><b>18.17.1</b> TBA Cased based vs. view-based scoring</a></li>
</ul></li>
<li class="chapter" data-level="18.18" data-path="froc-empirical.html"><a href="froc-empirical.html#froc-empirical-references"><i class="fa fa-check"></i><b>18.18</b> References</a></li>
</ul></li>
<li class="chapter" data-level="19" data-path="froc-empirical-examples.html"><a href="froc-empirical-examples.html"><i class="fa fa-check"></i><b>19</b> Empirical plot examples</a>
<ul>
<li class="chapter" data-level="19.1" data-path="froc-empirical.html"><a href="froc-empirical.html#froc-empirical-intro"><i class="fa fa-check"></i><b>19.1</b> Introduction TBA</a></li>
<li class="chapter" data-level="19.2" data-path="froc-empirical-examples.html"><a href="froc-empirical-examples.html#the-chance-level-froc-and-afroc-1"><i class="fa fa-check"></i><b>19.2</b> The chance level FROC and AFROC</a></li>
<li class="chapter" data-level="19.3" data-path="froc-empirical-examples.html"><a href="froc-empirical-examples.html#raw-frocafrocroc-plots-1"><i class="fa fa-check"></i><b>19.3</b> Raw FROC/AFROC/ROC plots</a>
<ul>
<li class="chapter" data-level="19.3.1" data-path="froc-empirical.html"><a href="froc-empirical.html#raw-plots-code1"><i class="fa fa-check"></i><b>19.3.1</b> Code for raw plots</a></li>
<li class="chapter" data-level="19.3.2" data-path="froc-empirical-examples.html"><a href="froc-empirical-examples.html#explanation-of-the-code-1"><i class="fa fa-check"></i><b>19.3.2</b> Explanation of the code</a></li>
<li class="chapter" data-level="19.3.3" data-path="froc-empirical-examples.html"><a href="froc-empirical-examples.html#explanation-of-the-code-continued-1"><i class="fa fa-check"></i><b>19.3.3</b> Explanation of the code, continued</a></li>
<li class="chapter" data-level="19.3.4" data-path="froc-empirical-examples.html"><a href="froc-empirical-examples.html#key-differences-from-the-roc-paradigm-1"><i class="fa fa-check"></i><b>19.3.4</b> Key differences from the ROC paradigm:</a></li>
</ul></li>
<li class="chapter" data-level="19.4" data-path="froc-empirical-examples.html"><a href="froc-empirical-examples.html#binned-frocafrocroc-plots-1"><i class="fa fa-check"></i><b>19.4</b> Binned FROC/AFROC/ROC plots</a>
<ul>
<li class="chapter" data-level="19.4.1" data-path="froc-empirical.html"><a href="froc-empirical.html#binned-plots-code1"><i class="fa fa-check"></i><b>19.4.1</b> Code for binned plots</a></li>
<li class="chapter" data-level="19.4.2" data-path="froc-empirical-examples.html"><a href="froc-empirical-examples.html#structure-of-the-binned-data-1"><i class="fa fa-check"></i><b>19.4.2</b> Structure of the binned data</a></li>
</ul></li>
<li class="chapter" data-level="19.5" data-path="froc-empirical-examples.html"><a href="froc-empirical-examples.html#misconceptions-about-location-level-true-negatives-1"><i class="fa fa-check"></i><b>19.5</b> Misconceptions about location-level “true-negatives”</a></li>
<li class="chapter" data-level="19.6" data-path="froc-empirical-examples.html"><a href="froc-empirical-examples.html#comments-and-recommendations-1"><i class="fa fa-check"></i><b>19.6</b> Comments and recommendations</a>
<ul>
<li class="chapter" data-level="19.6.1" data-path="froc-empirical-examples.html"><a href="froc-empirical-examples.html#why-not-use-nls-on-diseased-cases-1"><i class="fa fa-check"></i><b>19.6.1</b> Why not use NLs on diseased cases?</a></li>
<li class="chapter" data-level="19.6.2" data-path="froc-empirical-examples.html"><a href="froc-empirical-examples.html#recommendations-1"><i class="fa fa-check"></i><b>19.6.2</b> Recommendations</a></li>
</ul></li>
<li class="chapter" data-level="19.7" data-path="froc-empirical.html"><a href="froc-empirical.html#froc-empirical-Discussion"><i class="fa fa-check"></i><b>19.7</b> Discussion</a></li>
<li class="chapter" data-level="19.8" data-path="froc-empirical.html"><a href="froc-empirical.html#froc-empirical-miscellaneous"><i class="fa fa-check"></i><b>19.8</b> Miscellaneous</a>
<ul>
<li class="chapter" data-level="19.8.1" data-path="froc-empirical.html"><a href="froc-empirical.html#froc-empirical-case-vs-view"><i class="fa fa-check"></i><b>19.8.1</b> TBA Cased based vs. view-based scoring</a></li>
</ul></li>
<li class="chapter" data-level="19.9" data-path="froc-empirical.html"><a href="froc-empirical.html#froc-empirical-references"><i class="fa fa-check"></i><b>19.9</b> References</a></li>
</ul></li>
<li class="chapter" data-level="20" data-path="froc-paradigm-froc-vs-afroc.html"><a href="froc-paradigm-froc-vs-afroc.html"><i class="fa fa-check"></i><b>20</b> FROC vs. wAFROC</a>
<ul>
<li class="chapter" data-level="20.1" data-path="froc-paradigm-froc-vs-afroc.html"><a href="froc-paradigm-froc-vs-afroc.html#froc-paradigm-froc-vs-afroc-froc-vs-afrocs-intro1"><i class="fa fa-check"></i><b>20.1</b> Introduction</a></li>
<li class="chapter" data-level="20.2" data-path="froc-paradigm-froc-vs-afroc.html"><a href="froc-paradigm-froc-vs-afroc.html#froc-paradigm-froc-vs-afroc-froc-vs-afrocs-intro"><i class="fa fa-check"></i><b>20.2</b> Introduction</a></li>
<li class="chapter" data-level="20.3" data-path="froc-paradigm-froc-vs-afroc.html"><a href="froc-paradigm-froc-vs-afroc.html#froc-vs.-wafroc"><i class="fa fa-check"></i><b>20.3</b> FROC vs. wAFROC</a></li>
<li class="chapter" data-level="20.4" data-path="froc-paradigm-froc-vs-afroc.html"><a href="froc-paradigm-froc-vs-afroc.html#two-other-examples-are-given."><i class="fa fa-check"></i><b>20.4</b> Two other examples are given.</a>
<ul>
<li class="chapter" data-level="20.4.1" data-path="froc-paradigm-froc-vs-afroc.html"><a href="froc-paradigm-froc-vs-afroc.html#an-example-where-the-froc-can-be-used-for-comparisons"><i class="fa fa-check"></i><b>20.4.1</b> An example where the FROC can be used for comparisons</a></li>
</ul></li>
<li class="chapter" data-level="20.5" data-path="froc-paradigm-froc-vs-afroc.html"><a href="froc-paradigm-froc-vs-afroc.html#froc-paradigm-froc-vs-afroc-froc-vs-afrocs-Discussion"><i class="fa fa-check"></i><b>20.5</b> Discussion</a></li>
<li class="chapter" data-level="20.6" data-path="froc-paradigm-froc-vs-afroc.html"><a href="froc-paradigm-froc-vs-afroc.html#froc-paradigm-froc-vs-afroc-froc-vs-afrocs-references"><i class="fa fa-check"></i><b>20.6</b> References</a></li>
</ul></li>
<li class="chapter" data-level="21" data-path="froc-meanings.html"><a href="froc-meanings.html"><i class="fa fa-check"></i><b>21</b> Meanings of FROC figures of merit</a>
<ul>
<li class="chapter" data-level="21.1" data-path="froc-meanings.html"><a href="froc-meanings.html#froc-meanings-intro1"><i class="fa fa-check"></i><b>21.1</b> This chapter is in progress</a></li>
<li class="chapter" data-level="21.2" data-path="froc-meanings.html"><a href="froc-meanings.html#froc-meanings-intro"><i class="fa fa-check"></i><b>21.2</b> Introduction</a></li>
<li class="chapter" data-level="21.3" data-path="froc-meanings.html"><a href="froc-meanings.html#empirical-afroc-fom-statistic"><i class="fa fa-check"></i><b>21.3</b> Empirical AFROC FOM-statistic</a>
<ul>
<li class="chapter" data-level="21.3.1" data-path="froc-meanings.html"><a href="froc-meanings.html#upper-limit-for-afroc-fom-statistic"><i class="fa fa-check"></i><b>21.3.1</b> Upper limit for AFROC FOM-statistic</a></li>
<li class="chapter" data-level="21.3.2" data-path="froc-meanings.html"><a href="froc-meanings.html#range-of-afroc-fom-statistic"><i class="fa fa-check"></i><b>21.3.2</b> Range of AFROC FOM-statistic</a></li>
</ul></li>
<li class="chapter" data-level="21.4" data-path="froc-meanings.html"><a href="froc-meanings.html#empirical-weighted-afroc-fom-statistic"><i class="fa fa-check"></i><b>21.4</b> Empirical weighted-AFROC FOM-statistic</a></li>
<li class="chapter" data-level="21.5" data-path="froc-meanings.html"><a href="froc-meanings.html#two-theorems"><i class="fa fa-check"></i><b>21.5</b> Two Theorems</a>
<ul>
<li class="chapter" data-level="21.5.1" data-path="froc-meanings.html"><a href="froc-meanings.html#theorem-1"><i class="fa fa-check"></i><b>21.5.1</b> Theorem 1</a></li>
<li class="chapter" data-level="21.5.2" data-path="froc-meanings.html"><a href="froc-meanings.html#theorem-2"><i class="fa fa-check"></i><b>21.5.2</b> Theorem 2</a></li>
</ul></li>
<li class="chapter" data-level="21.6" data-path="froc-meanings.html"><a href="froc-meanings.html#understanding-the-afroc-and-wafroc-empirical-plots"><i class="fa fa-check"></i><b>21.6</b> Understanding the AFROC and wAFROC empirical plots</a>
<ul>
<li class="chapter" data-level="21.6.1" data-path="froc-meanings.html"><a href="froc-meanings.html#froc-meanings-AFROC-plot"><i class="fa fa-check"></i><b>21.6.1</b> The AFROC plot</a></li>
<li class="chapter" data-level="21.6.2" data-path="froc-meanings.html"><a href="froc-meanings.html#froc-meanings-wAFROC-plot"><i class="fa fa-check"></i><b>21.6.2</b> The weighted-AFROC (wAFROC) plot</a></li>
</ul></li>
<li class="chapter" data-level="21.7" data-path="froc-meanings.html"><a href="froc-meanings.html#physical-interpretation-of-afroc-based-foms"><i class="fa fa-check"></i><b>21.7</b> Physical interpretation of AFROC-based FOMs</a>
<ul>
<li class="chapter" data-level="21.7.1" data-path="froc-meanings.html"><a href="froc-meanings.html#physical-interpretation-of-area-under-afroc"><i class="fa fa-check"></i><b>21.7.1</b> Physical interpretation of area under AFROC</a></li>
<li class="chapter" data-level="21.7.2" data-path="froc-meanings.html"><a href="froc-meanings.html#physical-interpretation-of-area-under-wafroc"><i class="fa fa-check"></i><b>21.7.2</b> Physical interpretation of area under wAFROC</a></li>
</ul></li>
<li class="chapter" data-level="21.8" data-path="froc-meanings.html"><a href="froc-meanings.html#froc-meanings-Discussion"><i class="fa fa-check"></i><b>21.8</b> Discussion</a></li>
<li class="chapter" data-level="21.9" data-path="froc-meanings.html"><a href="froc-meanings.html#froc-meanings-references"><i class="fa fa-check"></i><b>21.9</b> References</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>REFERENCES</a></li>
<li class="part"><span><b>APPENDICES</b></span></li>
<li class="appendix"><span><b>Appendix</b></span></li>
<li class="chapter" data-level="A" data-path="rocdataformat.html"><a href="rocdataformat.html"><i class="fa fa-check"></i><b>A</b> ROC DATA FORMAT</a>
<ul>
<li class="chapter" data-level="A.1" data-path="rocdataformat.html"><a href="rocdataformat.html#rocdataformatIntro"><i class="fa fa-check"></i><b>A.1</b> Introduction</a></li>
<li class="chapter" data-level="A.2" data-path="rocdataformat.html"><a href="rocdataformat.html#note-to-existing-users"><i class="fa fa-check"></i><b>A.2</b> Note to existing users</a></li>
<li class="chapter" data-level="A.3" data-path="rocdataformat.html"><a href="rocdataformat.html#rocExceldataformat"><i class="fa fa-check"></i><b>A.3</b> The Excel data format</a></li>
<li class="chapter" data-level="A.4" data-path="rocdataformat.html"><a href="rocdataformat.html#illustrative-toy-file"><i class="fa fa-check"></i><b>A.4</b> Illustrative toy file</a></li>
<li class="chapter" data-level="A.5" data-path="rocdataformat.html"><a href="rocdataformat.html#rocExcelTruthdataformat"><i class="fa fa-check"></i><b>A.5</b> The <code>Truth</code> worksheet</a></li>
<li class="chapter" data-level="A.6" data-path="rocdataformat.html"><a href="rocdataformat.html#the-structure-of-an-roc-dataset"><i class="fa fa-check"></i><b>A.6</b> The structure of an ROC dataset</a></li>
<li class="chapter" data-level="A.7" data-path="rocdataformat.html"><a href="rocdataformat.html#rocExcelFPdataformat"><i class="fa fa-check"></i><b>A.7</b> The false positive (FP) ratings</a></li>
<li class="chapter" data-level="A.8" data-path="rocdataformat.html"><a href="rocdataformat.html#rocExcelTPdataformat"><i class="fa fa-check"></i><b>A.8</b> The true positive (TP) ratings</a></li>
<li class="chapter" data-level="A.9" data-path="rocdataformat.html"><a href="rocdataformat.html#correspondence-between-nl-member-of-dataset-and-the-fp-worksheet"><i class="fa fa-check"></i><b>A.9</b> Correspondence between <code>NL</code> member of dataset and the <code>FP</code> worksheet</a></li>
<li class="chapter" data-level="A.10" data-path="rocdataformat.html"><a href="rocdataformat.html#correspondence-between-ll-member-of-dataset-and-the-tp-worksheet"><i class="fa fa-check"></i><b>A.10</b> Correspondence between <code>LL</code> member of dataset and the <code>TP</code> worksheet</a></li>
<li class="chapter" data-level="A.11" data-path="rocdataformat.html"><a href="rocdataformat.html#correspondence-using-the-which-function"><i class="fa fa-check"></i><b>A.11</b> Correspondence using the <code>which</code> function</a></li>
<li class="chapter" data-level="A.12" data-path="rocdataformat.html"><a href="rocdataformat.html#rocdataformat-Summary"><i class="fa fa-check"></i><b>A.12</b> Summary</a></li>
<li class="chapter" data-level="A.13" data-path="rocdataformat.html"><a href="rocdataformat.html#rocdataformat-Discussion"><i class="fa fa-check"></i><b>A.13</b> Discussion</a></li>
<li class="chapter" data-level="A.14" data-path="rocdataformat.html"><a href="rocdataformat.html#rocdataformat-references"><i class="fa fa-check"></i><b>A.14</b> References</a></li>
</ul></li>
<li class="chapter" data-level="B" data-path="frocdataformat.html"><a href="frocdataformat.html"><i class="fa fa-check"></i><b>B</b> FROC data format</a>
<ul>
<li class="chapter" data-level="B.1" data-path="frocdataformat.html"><a href="frocdataformat.html#purpose"><i class="fa fa-check"></i><b>B.1</b> Purpose</a></li>
<li class="chapter" data-level="B.2" data-path="frocdataformat.html"><a href="frocdataformat.html#frocdataformatIntro"><i class="fa fa-check"></i><b>B.2</b> Introduction</a></li>
<li class="chapter" data-level="B.3" data-path="frocdataformat.html"><a href="frocdataformat.html#frocExceldataformat"><i class="fa fa-check"></i><b>B.3</b> The Excel data format</a></li>
<li class="chapter" data-level="B.4" data-path="frocdataformat.html"><a href="frocdataformat.html#frocExcelTruthdataformat"><i class="fa fa-check"></i><b>B.4</b> The <code>Truth</code> worksheet</a></li>
<li class="chapter" data-level="B.5" data-path="frocdataformat.html"><a href="frocdataformat.html#the-structure-of-an-froc-dataset"><i class="fa fa-check"></i><b>B.5</b> The structure of an FROC dataset</a></li>
<li class="chapter" data-level="B.6" data-path="frocdataformat.html"><a href="frocdataformat.html#the-false-positive-fp-ratings"><i class="fa fa-check"></i><b>B.6</b> The false positive (FP) ratings</a></li>
<li class="chapter" data-level="B.7" data-path="frocdataformat.html"><a href="frocdataformat.html#the-true-positive-tp-ratings"><i class="fa fa-check"></i><b>B.7</b> The true positive (TP) ratings</a></li>
<li class="chapter" data-level="B.8" data-path="frocdataformat.html"><a href="frocdataformat.html#on-the-distribution-of-numbers-of-lesions-in-abnormal-cases"><i class="fa fa-check"></i><b>B.8</b> On the distribution of numbers of lesions in abnormal cases</a>
<ul>
<li class="chapter" data-level="B.8.1" data-path="frocdataformat.html"><a href="frocdataformat.html#definition-of-lesdistr-array"><i class="fa fa-check"></i><b>B.8.1</b> Definition of <code>lesDistr</code> array</a></li>
</ul></li>
<li class="chapter" data-level="B.9" data-path="frocdataformat.html"><a href="frocdataformat.html#definition-of-leswghtdistr-array"><i class="fa fa-check"></i><b>B.9</b> Definition of <code>lesWghtDistr</code> array</a></li>
<li class="chapter" data-level="B.10" data-path="frocdataformat.html"><a href="frocdataformat.html#frocdataformat-Summary"><i class="fa fa-check"></i><b>B.10</b> Summary</a></li>
<li class="chapter" data-level="B.11" data-path="frocdataformat.html"><a href="frocdataformat.html#frocdataformat-Discussion"><i class="fa fa-check"></i><b>B.11</b> Discussion</a></li>
<li class="chapter" data-level="B.12" data-path="frocdataformat.html"><a href="frocdataformat.html#frocdataformat-references"><i class="fa fa-check"></i><b>B.12</b> References</a></li>
</ul></li>
<li class="chapter" data-level="C" data-path="classification-tasks.html"><a href="classification-tasks.html"><i class="fa fa-check"></i><b>C</b> Localization - classification tasks</a>
<ul>
<li class="chapter" data-level="C.1" data-path="classification-tasks.html"><a href="classification-tasks.html#classification-tasks-intro"><i class="fa fa-check"></i><b>C.1</b> Introduction</a></li>
<li class="chapter" data-level="C.2" data-path="classification-tasks.html"><a href="classification-tasks.html#classification-tasks-abbreviations"><i class="fa fa-check"></i><b>C.2</b> Abbreviations</a></li>
<li class="chapter" data-level="C.3" data-path="classification-tasks.html"><a href="classification-tasks.html#classification-tasks-basic-idea"><i class="fa fa-check"></i><b>C.3</b> History and basic idea</a></li>
<li class="chapter" data-level="C.4" data-path="classification-tasks.html"><a href="classification-tasks.html#classification-tasks-example1"><i class="fa fa-check"></i><b>C.4</b> First example, File1.xlsx</a>
<ul>
<li class="chapter" data-level="C.4.1" data-path="classification-tasks.html"><a href="classification-tasks.html#classification-tasks-example1-truth"><i class="fa fa-check"></i><b>C.4.1</b> <code>Truth</code> sheet</a></li>
<li class="chapter" data-level="C.4.2" data-path="classification-tasks.html"><a href="classification-tasks.html#classification-tasks-example1-tp"><i class="fa fa-check"></i><b>C.4.2</b> <code>TP</code> sheet</a></li>
<li class="chapter" data-level="C.4.3" data-path="classification-tasks.html"><a href="classification-tasks.html#classification-tasks-example1-fp"><i class="fa fa-check"></i><b>C.4.3</b> <code>FP</code> sheet</a></li>
<li class="chapter" data-level="C.4.4" data-path="classification-tasks.html"><a href="classification-tasks.html#the-two-ratings-arrays"><i class="fa fa-check"></i><b>C.4.4</b> The two ratings arrays</a></li>
</ul></li>
<li class="chapter" data-level="C.5" data-path="classification-tasks.html"><a href="classification-tasks.html#classification-tasks-example2"><i class="fa fa-check"></i><b>C.5</b> Second example, File2.xlsx</a></li>
<li class="chapter" data-level="C.6" data-path="classification-tasks.html"><a href="classification-tasks.html#classification-tasks-example3"><i class="fa fa-check"></i><b>C.6</b> Third example, File3.xlsx</a></li>
<li class="chapter" data-level="C.7" data-path="classification-tasks.html"><a href="classification-tasks.html#classification-tasks-example4"><i class="fa fa-check"></i><b>C.7</b> Fourth example, File4.xlsx</a></li>
<li class="chapter" data-level="C.8" data-path="classification-tasks.html"><a href="classification-tasks.html#classification-tasks-example5"><i class="fa fa-check"></i><b>C.8</b> Fifth example, File5.xlsx</a></li>
<li class="chapter" data-level="C.9" data-path="classification-tasks.html"><a href="classification-tasks.html#classification-tasks-precautions"><i class="fa fa-check"></i><b>C.9</b> Precautions</a></li>
<li class="chapter" data-level="C.10" data-path="classification-tasks.html"><a href="classification-tasks.html#classification-tasks-discussion"><i class="fa fa-check"></i><b>C.10</b> Discussion</a></li>
<li class="chapter" data-level="C.11" data-path="classification-tasks.html"><a href="classification-tasks.html#classification-tasks--references"><i class="fa fa-check"></i><b>C.11</b> References</a></li>
</ul></li>
<li class="chapter" data-level="D" data-path="SplitPlotChapter.html"><a href="SplitPlotChapter.html"><i class="fa fa-check"></i><b>D</b> Split Plot Study Design</a>
<ul>
<li class="chapter" data-level="D.1" data-path="SplitPlotChapter.html"><a href="SplitPlotChapter.html#mean-square-rt"><i class="fa fa-check"></i><b>D.1</b> Mean Square R(T)</a></li>
<li class="chapter" data-level="D.2" data-path="SplitPlotChapter.html"><a href="SplitPlotChapter.html#SplitPlotChapter-references"><i class="fa fa-check"></i><b>D.2</b> References</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">The RJafroc Book</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="froc-empirical-examples" class="section level1" number="19">
<h1><span class="header-section-number">Chapter 19</span> Empirical plot examples</h1>
<div id="froc-empirical-intro" class="section level2" number="19.1">
<h2><span class="header-section-number">19.1</span> Introduction TBA</h2>
<p>So far, the description has been limited to abstract definitions of various operating characteristics possible with FROC data. Now it is time to put numbers into the formulae and see actual plots. The starting point is the FROC plot.</p>
</div>
<div id="the-chance-level-froc-and-afroc-1" class="section level2" number="19.2">
<h2><span class="header-section-number">19.2</span> The chance level FROC and AFROC</h2>
<p>The chance level FROC was addressed in the previous chapter; it is a “flat-liner,” hugging the x-axis, except for a slight upturn at large NLF.</p>
<div class="figure"><span id="fig:froc-afroc-chance-level"></span>
<img src="13-froc-empirical-examples_files/figure-html/froc-afroc-chance-level-1.png" alt="The left figure is the near guessing observer's FROC and the right figure is the corresponding AFROC for for $\mu=0.01$." width="672" />
<p class="caption">
FIGURE 18.1: The left figure is the near guessing observer’s FROC and the right figure is the corresponding AFROC for for <span class="math inline">\(\mu=0.01\)</span>.
</p>
</div>
<p>Fig. <a href="froc-empirical.html#fig:froc-afroc-chance-level">18.1</a> shows “near guessing” FROC and AFROC plots for <span class="math inline">\(\mu = 0.1\)</span>. These plots were generated by the code with <span class="math inline">\(\mu\)</span> = 0.1, <span class="math inline">\(\lambda\)</span> = 1, <span class="math inline">\(\nu\)</span> = 0.1, <span class="math inline">\(\zeta_1\)</span> = -1, <span class="math inline">\(K_1\)</span> = 50, <span class="math inline">\(K_2\)</span> = 70. One does not expect to observe curves like these with radiologists as they rarely guess in the clinic – there is too much at stake.</p>
<p>The AFROC of a guessing observer is not the line connecting (0,0) to (1,1) <span class="citation">(<a href="SplitPlotChapter.html#ref-RN2518" role="doc-biblioref">Lockwood and Piper 2015</a>)</span>. A guessing observer will also generate a “flat-liner,” but this time the plot ends at FPF = 1, and the straight line extension will be a vertical line connecting this point to (1,1). In the limit <span class="math inline">\(\mu \rightarrow 0+\)</span>, AFROC-AUC tends to zero.</p>
<p><em>To summarize, AFROC AUC of a guessing observer is zero.</em> On the other hand, suppose an expert radiologist views screening images and the lesions on diseased cases are very difficult, even for the expert, and the radiologist does not find any of them. Being an expert the radiologist successfully screens out non-diseased cases and sees nothing suspicious in any of them – this is a measure of the expertise of the radiologist, not mistaking variants of normal anatomy for false lesions on non-diseased cases. Accordingly, the expert radiologist does not report anything, and the operating point is “stuck” at the origin. Even in this unusual situation, one would be justified in connecting the origin to (1,1) and claiming area under AFROC is 0.5. The extension gives the radiologist credit for not marking any non-diseased case; of course, the radiologist does not get any credit for marking any of the lesions. An even better radiologist, who finds and marks some of the lesions, will score higher, and AFROC-AUC will exceed 0.5. See TBA §17.7.4 for a software demonstration of this unusual situation.</p>
</div>
<div id="raw-frocafrocroc-plots-1" class="section level2" number="19.3">
<h2><span class="header-section-number">19.3</span> Raw FROC/AFROC/ROC plots</h2>
<p><em>Raw plots</em> correspond to the actual simulator generated continuous ratings, prior to any binning operation. The opposite of raw plots would be <em>binned plots</em>. The FROC plots shown below were generated using the data simulator introduced in Chapter <a href="froc-paradigm.html#froc-paradigm">17</a>. The examples are similar to the population FROC curves shown in that chapter but the emphasis here is on understanding the FROC data structure. To this end smaller numbers of cases, not 20,000 as in the previous chapter, are used. Examples are given using continuous ratings, termed “raw data,” and binned data, for a smaller dataset and for a larger dataset. With a smaller dataset, the logic of constructing the plot is more transparent but the operating points are more susceptible to sampling variability. The examples illustrate key points distinguishing the free-response paradigm from ROC.</p>
<div id="raw-plots-code1" class="section level3" number="19.3.1">
<h3><span class="header-section-number">19.3.1</span> Code for raw plots</h3>
<div class="sourceCode" id="cb116"><pre class="sourceCode numberSource r numberLines"><code class="sourceCode r"><span id="cb116-1"><a href="froc-empirical-examples.html#cb116-1"></a>seed <span class="ot">&lt;-</span> <span class="dv">1</span>;<span class="fu">set.seed</span>(seed)</span>
<span id="cb116-2"><a href="froc-empirical-examples.html#cb116-2"></a>mu <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb116-3"><a href="froc-empirical-examples.html#cb116-3"></a>lambda <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb116-4"><a href="froc-empirical-examples.html#cb116-4"></a>nu <span class="ot">&lt;-</span> <span class="dv">1</span> </span>
<span id="cb116-5"><a href="froc-empirical-examples.html#cb116-5"></a>zeta1 <span class="ot">&lt;-</span> <span class="sc">-</span><span class="dv">1</span></span>
<span id="cb116-6"><a href="froc-empirical-examples.html#cb116-6"></a>K1 <span class="ot">&lt;-</span> <span class="dv">5</span></span>
<span id="cb116-7"><a href="froc-empirical-examples.html#cb116-7"></a>K2 <span class="ot">&lt;-</span> <span class="dv">7</span> </span>
<span id="cb116-8"><a href="froc-empirical-examples.html#cb116-8"></a>Lmax <span class="ot">&lt;-</span> <span class="dv">2</span></span>
<span id="cb116-9"><a href="froc-empirical-examples.html#cb116-9"></a>Lk2 <span class="ot">&lt;-</span> <span class="fu">floor</span>(<span class="fu">runif</span>(K2, <span class="dv">1</span>, Lmax <span class="sc">+</span> <span class="dv">1</span>))</span>
<span id="cb116-10"><a href="froc-empirical-examples.html#cb116-10"></a></span>
<span id="cb116-11"><a href="froc-empirical-examples.html#cb116-11"></a>frocDataRaw <span class="ot">&lt;-</span> <span class="fu">SimulateFrocDataset</span>(</span>
<span id="cb116-12"><a href="froc-empirical-examples.html#cb116-12"></a>  <span class="at">mu =</span> mu, </span>
<span id="cb116-13"><a href="froc-empirical-examples.html#cb116-13"></a>  <span class="at">lambda =</span> lambda, </span>
<span id="cb116-14"><a href="froc-empirical-examples.html#cb116-14"></a>  <span class="at">nu =</span> nu, </span>
<span id="cb116-15"><a href="froc-empirical-examples.html#cb116-15"></a>  <span class="at">I =</span> <span class="dv">1</span>,</span>
<span id="cb116-16"><a href="froc-empirical-examples.html#cb116-16"></a>  <span class="at">J =</span> <span class="dv">1</span>,</span>
<span id="cb116-17"><a href="froc-empirical-examples.html#cb116-17"></a>  <span class="at">K1 =</span> K1, </span>
<span id="cb116-18"><a href="froc-empirical-examples.html#cb116-18"></a>  <span class="at">K2 =</span> K2, </span>
<span id="cb116-19"><a href="froc-empirical-examples.html#cb116-19"></a>  <span class="at">perCase =</span> Lk2, </span>
<span id="cb116-20"><a href="froc-empirical-examples.html#cb116-20"></a>  <span class="at">zeta1 =</span> zeta1</span>
<span id="cb116-21"><a href="froc-empirical-examples.html#cb116-21"></a>)</span>
<span id="cb116-22"><a href="froc-empirical-examples.html#cb116-22"></a></span>
<span id="cb116-23"><a href="froc-empirical-examples.html#cb116-23"></a>p1 <span class="ot">&lt;-</span> <span class="fu">PlotEmpiricalOperatingCharacteristics</span>(</span>
<span id="cb116-24"><a href="froc-empirical-examples.html#cb116-24"></a>  <span class="at">dataset =</span> frocDataRaw, </span>
<span id="cb116-25"><a href="froc-empirical-examples.html#cb116-25"></a>  <span class="at">trts=</span> <span class="dv">1</span>, <span class="at">rdrs =</span> <span class="dv">1</span>, <span class="at">opChType =</span> <span class="st">&quot;FROC&quot;</span>, </span>
<span id="cb116-26"><a href="froc-empirical-examples.html#cb116-26"></a>  <span class="at">legend.position =</span> <span class="st">&quot;NULL&quot;</span>)<span class="sc">$</span>Plot</span>
<span id="cb116-27"><a href="froc-empirical-examples.html#cb116-27"></a></span>
<span id="cb116-28"><a href="froc-empirical-examples.html#cb116-28"></a>p2 <span class="ot">&lt;-</span> <span class="fu">PlotEmpiricalOperatingCharacteristics</span>(</span>
<span id="cb116-29"><a href="froc-empirical-examples.html#cb116-29"></a>  <span class="at">dataset =</span> frocDataRaw, </span>
<span id="cb116-30"><a href="froc-empirical-examples.html#cb116-30"></a>  <span class="at">trts=</span> <span class="dv">1</span>, <span class="at">rdrs =</span> <span class="dv">1</span>, <span class="at">opChType =</span> <span class="st">&quot;AFROC&quot;</span>, </span>
<span id="cb116-31"><a href="froc-empirical-examples.html#cb116-31"></a>  <span class="at">legend.position =</span> <span class="st">&quot;NULL&quot;</span>)<span class="sc">$</span>Plot</span>
<span id="cb116-32"><a href="froc-empirical-examples.html#cb116-32"></a></span>
<span id="cb116-33"><a href="froc-empirical-examples.html#cb116-33"></a>p3 <span class="ot">&lt;-</span> <span class="fu">PlotEmpiricalOperatingCharacteristics</span>(</span>
<span id="cb116-34"><a href="froc-empirical-examples.html#cb116-34"></a>  <span class="at">dataset =</span> frocDataRaw, </span>
<span id="cb116-35"><a href="froc-empirical-examples.html#cb116-35"></a>  <span class="at">trts=</span> <span class="dv">1</span>, <span class="at">rdrs =</span> <span class="dv">1</span>, <span class="at">opChType =</span> <span class="st">&quot;ROC&quot;</span>, </span>
<span id="cb116-36"><a href="froc-empirical-examples.html#cb116-36"></a>  <span class="at">legend.position =</span> <span class="st">&quot;NULL&quot;</span>)<span class="sc">$</span>Plot</span>
<span id="cb116-37"><a href="froc-empirical-examples.html#cb116-37"></a></span>
<span id="cb116-38"><a href="froc-empirical-examples.html#cb116-38"></a>frocDataRaw_1_5_7 <span class="ot">&lt;-</span> frocDataRaw <span class="co"># seed 2, K1 = 5, K2 = 7</span></span></code></pre></div>
</div>
<div id="explanation-of-the-code-1" class="section level3" number="19.3.2">
<h3><span class="header-section-number">19.3.2</span> Explanation of the code</h3>
<p>Line 1 sets the seed of the random number generator. Lines 2-5 set the simulator parameters <span class="math inline">\(\mu = 1, \lambda = 1, \nu = 1, \zeta_1 = -1\)</span>. Briefly, <span class="math inline">\(\mu\)</span> determines the separation of two unit variance Gaussians, the left one determines the z-samples of latent NLs, while the right one determines the z-samples of latent LLs. <span class="math inline">\(\lambda\)</span> determines the number of latent NLs while <span class="math inline">\(\nu\)</span> determines the number of latent LLs. A latent NL or LL is marked if its z-sample <span class="math inline">\(\geq \zeta_1\)</span>.</p>
<p>Lines 6-7 set the number of non-diseased cases <span class="math inline">\(K_1 = 5\)</span> and the number of diseased cases <span class="math inline">\(K_2 = 7\)</span>.</p>
<p>Line 8 sets the maximum number of lesions per diseased case to 2. Line 9 randomly samples the actual number of lesions per diseased case. The following code illustrats the process.</p>
<div id="number-of-lesions-per-diseased-case-1" class="section level4" number="19.3.2.1">
<h4><span class="header-section-number">19.3.2.1</span> Number of lesions per diseased case</h4>
<div class="sourceCode" id="cb117"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb117-1"><a href="froc-empirical-examples.html#cb117-1" aria-hidden="true" tabindex="-1"></a>Lk2</span>
<span id="cb117-2"><a href="froc-empirical-examples.html#cb117-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 1 1 2 2 1 2 2</span></span>
<span id="cb117-3"><a href="froc-empirical-examples.html#cb117-3" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(Lk2)</span>
<span id="cb117-4"><a href="froc-empirical-examples.html#cb117-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 11</span></span>
<span id="cb117-5"><a href="froc-empirical-examples.html#cb117-5" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(<span class="fu">floor</span>(<span class="fu">runif</span>(<span class="dv">1000</span>, <span class="dv">1</span>, Lmax <span class="sc">+</span> <span class="dv">1</span>)))</span>
<span id="cb117-6"><a href="froc-empirical-examples.html#cb117-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 2</span></span></code></pre></div>
<p>This shows that the first two diseased cases have one lesion each, the third and fourth have two lesions each, etc. The total number of lesions in the dataset is 11. The last two lines of the code snippet show that, even with a thousand simulations, the number of lesions per diseased case is indeed limited to two.</p>
</div>
<div id="the-structure-of-the-froc-dataset-1" class="section level4" number="19.3.2.2">
<h4><span class="header-section-number">19.3.2.2</span> The structure of the FROC dataset</h4>
<p>Returning to the explanation of the code, lines 11-21 uses the function <code>SimulateFrocDataset</code> to simulate the dataset object <code>frocDataRaw</code>. Its structure is examined next:</p>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="froc-empirical-examples.html#cb118-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(frocDataRaw)</span>
<span id="cb118-2"><a href="froc-empirical-examples.html#cb118-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; List of 3</span></span>
<span id="cb118-3"><a href="froc-empirical-examples.html#cb118-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  $ ratings     :List of 3</span></span>
<span id="cb118-4"><a href="froc-empirical-examples.html#cb118-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   ..$ NL   : num [1, 1, 1:12, 1:4] 0.764 -0.799 -Inf -Inf -Inf ...</span></span>
<span id="cb118-5"><a href="froc-empirical-examples.html#cb118-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   ..$ LL   : num [1, 1, 1:7, 1:2] -Inf 0.943 0.944 0.309 0.522 ...</span></span>
<span id="cb118-6"><a href="froc-empirical-examples.html#cb118-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   ..$ LL_IL: logi NA</span></span>
<span id="cb118-7"><a href="froc-empirical-examples.html#cb118-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  $ lesions     :List of 3</span></span>
<span id="cb118-8"><a href="froc-empirical-examples.html#cb118-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   ..$ perCase: num [1:7] 1 1 2 2 1 2 2</span></span>
<span id="cb118-9"><a href="froc-empirical-examples.html#cb118-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   ..$ IDs    : num [1:7, 1:2] 1 1 1 1 1 ...</span></span>
<span id="cb118-10"><a href="froc-empirical-examples.html#cb118-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   ..$ weights: num [1:7, 1:2] 1 1 0.5 0.5 1 ...</span></span>
<span id="cb118-11"><a href="froc-empirical-examples.html#cb118-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  $ descriptions:List of 7</span></span>
<span id="cb118-12"><a href="froc-empirical-examples.html#cb118-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   ..$ fileName     : chr &quot;NA&quot;</span></span>
<span id="cb118-13"><a href="froc-empirical-examples.html#cb118-13" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   ..$ type         : chr &quot;FROC&quot;</span></span>
<span id="cb118-14"><a href="froc-empirical-examples.html#cb118-14" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   ..$ name         : logi NA</span></span>
<span id="cb118-15"><a href="froc-empirical-examples.html#cb118-15" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   ..$ truthTableStr: logi NA</span></span>
<span id="cb118-16"><a href="froc-empirical-examples.html#cb118-16" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   ..$ design       : chr &quot;FCTRL&quot;</span></span>
<span id="cb118-17"><a href="froc-empirical-examples.html#cb118-17" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   ..$ modalityID   : chr &quot;1&quot;</span></span>
<span id="cb118-18"><a href="froc-empirical-examples.html#cb118-18" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   ..$ readerID     : chr &quot;1&quot;</span></span></code></pre></div>
<p>It is seen to consist of three <code>list</code> members: <code>ratings</code>, <code>lesions</code> and <code>descriptions</code>. Let us examine the <code>ratings</code> member.</p>
</div>
<div id="the-structure-of-the-ratings-member-1" class="section level4" number="19.3.2.3">
<h4><span class="header-section-number">19.3.2.3</span> The structure of the ratings member</h4>
<p>The <code>ratings</code> member is itself a list of 3, consisting of <code>NL</code> the non-lesion localization ratings, <code>LL</code> the lesion localization ratings and <code>LL_IL</code> the incorrect localization ratings. The last member is needed for LROC datasets and can be ignored for now. Let us examine the contents of the <code>NL</code> member.</p>
</div>
<div id="the-structure-of-the-nl-member-1" class="section level4" number="19.3.2.4">
<h4><span class="header-section-number">19.3.2.4</span> The structure of the NL member</h4>
<div class="sourceCode" id="cb119"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb119-1"><a href="froc-empirical-examples.html#cb119-1" aria-hidden="true" tabindex="-1"></a>frocDataRaw_1_5_7<span class="sc">$</span>ratings<span class="sc">$</span>NL[<span class="dv">1</span>,<span class="dv">1</span>,,]</span>
<span id="cb119-2"><a href="froc-empirical-examples.html#cb119-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;             [,1]       [,2]       [,3] [,4]</span></span>
<span id="cb119-3"><a href="froc-empirical-examples.html#cb119-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  [1,]  0.7635935       -Inf       -Inf -Inf</span></span>
<span id="cb119-4"><a href="froc-empirical-examples.html#cb119-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  [2,] -0.7990092       -Inf       -Inf -Inf</span></span>
<span id="cb119-5"><a href="froc-empirical-examples.html#cb119-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  [3,]       -Inf       -Inf       -Inf -Inf</span></span>
<span id="cb119-6"><a href="froc-empirical-examples.html#cb119-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  [4,]       -Inf       -Inf       -Inf -Inf</span></span>
<span id="cb119-7"><a href="froc-empirical-examples.html#cb119-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  [5,]       -Inf       -Inf       -Inf -Inf</span></span>
<span id="cb119-8"><a href="froc-empirical-examples.html#cb119-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  [6,]       -Inf       -Inf       -Inf -Inf</span></span>
<span id="cb119-9"><a href="froc-empirical-examples.html#cb119-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  [7,] -0.2894616       -Inf       -Inf -Inf</span></span>
<span id="cb119-10"><a href="froc-empirical-examples.html#cb119-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  [8,] -0.2992151 -0.4115108       -Inf -Inf</span></span>
<span id="cb119-11"><a href="froc-empirical-examples.html#cb119-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  [9,]  0.2522234       -Inf       -Inf -Inf</span></span>
<span id="cb119-12"><a href="froc-empirical-examples.html#cb119-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [10,] -0.8919211       -Inf       -Inf -Inf</span></span>
<span id="cb119-13"><a href="froc-empirical-examples.html#cb119-13" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [11,]  0.4356833  0.3773956 -0.2242679 -Inf</span></span>
<span id="cb119-14"><a href="froc-empirical-examples.html#cb119-14" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [12,]  0.1333364       -Inf       -Inf -Inf</span></span></code></pre></div>
<ul>
<li><p>It is seen to be an array with dimensions <code>[1,1,1:12,1:4]</code>.</p></li>
<li><p>The first dimension corresponds to the number of modalities, one in this example, the second dimension corresponds to the number of readers, also one in this example. The third dimension is the total number of cases, <span class="math inline">\(K_1+K_2 = 12\)</span> in this example, because NLs are possible on <em>both</em> non-diseased and diseased cases.</p></li>
<li><p>The fourth dimension is 4, as the simulator generated, over 12 cases, a maximum of 4 latent NLs per case. This is demonstrated in the code output below, generated by temporarily setting <span class="math inline">\(\zeta_1 = -\infty\)</span>, which results in all latent marks being marked. Specifically, case 11, the sixth diseased case, generated 4 NLs, but one of them, at position 4, had rating less than <span class="math inline">\(\zeta_1 = -1\)</span>, and was consequently not marked, i.e., assigned a rating of <span class="math inline">\(-\infty\)</span>.</p></li>
</ul>
<pre><code>#&gt;             [,1]       [,2]       [,3]      [,4]
#&gt;  [1,]  0.7635935       -Inf       -Inf      -Inf
#&gt;  [2,] -0.7990092       -Inf       -Inf      -Inf
#&gt;  [3,]       -Inf       -Inf       -Inf      -Inf
#&gt;  [4,]       -Inf       -Inf       -Inf      -Inf
#&gt;  [5,]       -Inf       -Inf       -Inf      -Inf
#&gt;  [6,] -1.1476570       -Inf       -Inf      -Inf
#&gt;  [7,] -0.2894616       -Inf       -Inf      -Inf
#&gt;  [8,] -0.2992151 -0.4115108       -Inf      -Inf
#&gt;  [9,]  0.2522234       -Inf       -Inf      -Inf
#&gt; [10,] -0.8919211       -Inf       -Inf      -Inf
#&gt; [11,]  0.4356833  0.3773956 -0.2242679 -1.237538
#&gt; [12,]  0.1333364       -Inf       -Inf      -Inf</code></pre>
<ul>
<li><p>Note that all listed ratings are greater than <span class="math inline">\(\zeta_1 = -1\)</span>.</p></li>
<li><p>Case 1, the first non-diseased case, has a single NL mark rated 0.7635935 and the remaining 3 locations are filled with <span class="math inline">\(-\infty\)</span>s.</p></li>
<li><p>Case 6, the first diseased case, has zero NL marks and all 4 locations for it are filled with <span class="math inline">\(-\infty\)</span>s.</p></li>
<li><p>Case 11, the sixth diseased case, has three NL marks rated 0.4356833, 0.3773956, -0.2242679 and the remaining location for it is <span class="math inline">\(-\infty\)</span>. As noted above, this case generated a fourth rating that fell below <span class="math inline">\(\zeta_1 = -1\)</span>.</p></li>
</ul>
</div>
<div id="the-structure-of-the-ll-member-1" class="section level4" number="19.3.2.5">
<h4><span class="header-section-number">19.3.2.5</span> The structure of the LL member</h4>
<div class="sourceCode" id="cb121"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb121-1"><a href="froc-empirical-examples.html#cb121-1" aria-hidden="true" tabindex="-1"></a>frocDataRaw<span class="sc">$</span>ratings<span class="sc">$</span>LL[<span class="dv">1</span>,<span class="dv">1</span>,,]</span>
<span id="cb121-2"><a href="froc-empirical-examples.html#cb121-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;           [,1]      [,2]</span></span>
<span id="cb121-3"><a href="froc-empirical-examples.html#cb121-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1,]      -Inf      -Inf</span></span>
<span id="cb121-4"><a href="froc-empirical-examples.html#cb121-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [2,] 0.9428932      -Inf</span></span>
<span id="cb121-5"><a href="froc-empirical-examples.html#cb121-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [3,] 0.9438713      -Inf</span></span>
<span id="cb121-6"><a href="froc-empirical-examples.html#cb121-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [4,] 0.3090462      -Inf</span></span>
<span id="cb121-7"><a href="froc-empirical-examples.html#cb121-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [5,] 0.5218499      -Inf</span></span>
<span id="cb121-8"><a href="froc-empirical-examples.html#cb121-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [6,] 0.7642934      -Inf</span></span>
<span id="cb121-9"><a href="froc-empirical-examples.html#cb121-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [7,] 1.3876716 0.8972123</span></span></code></pre></div>
<ul>
<li><p>It is seen to be an array with dimensions <code>[1,1,1:7,1:2]</code>.</p></li>
<li><p>The first dimension corresponds to the number of modalities, one in this example, the second dimension corresponds to the number of readers, also one in this example. The third dimension is the total number of diseased cases, <span class="math inline">\(K_2 = 7\)</span> in this example, because LLs are only possible on diseased cases.</p></li>
<li><p>The fourth dimension is 2, as the maximum number of lesions per diseased case is 2.</p></li>
<li><p>Note that all listed ratings are greater than <span class="math inline">\(\zeta_1 = -1\)</span>.</p></li>
<li><p>Case 1, the first diseased case, has zero LL marks and both locations are filled with <span class="math inline">\(-\infty\)</span>s.</p></li>
<li><p>Case 2, the second diseased case, has one LL mark rated 0.9428932 and the remaining location is <span class="math inline">\(-\infty\)</span>.</p></li>
<li><p>Case 7, the seventh diseased case, has two LL marks rated 1.3876716, 0.8972123 and zero locations with <span class="math inline">\(-\infty\)</span>.</p></li>
</ul>
</div>
</div>
<div id="explanation-of-the-code-continued-1" class="section level3" number="19.3.3">
<h3><span class="header-section-number">19.3.3</span> Explanation of the code, continued</h3>
<p>Returning to the explanation of the code in Section <a href="froc-empirical.html#raw-plots-code1">18.12.1</a>:</p>
<ul>
<li><p>Lines 23 - 25 use the <code>PlotEmpiricalOperatingCharacteristics</code> function to calculate the FROC plot object, which is saved to <code>p1</code>. Note the argument <code>opChType = "FROC"</code>, for the desired FROC plot.</p></li>
<li><p>Lines 28 - 31 use the <code>PlotEmpiricalOperatingCharacteristics</code> function to calculate the AFROC plot object, which is saved to <code>p2</code>. Note the argument <code>opChType = "AFROC"</code>.</p></li>
<li><p>Finally, lines 33 - 35 use the <code>PlotEmpiricalOperatingCharacteristics</code> function to calculate the ROC plot object, which is saved to <code>p3</code>. Note the argument <code>opChType = "ROC"</code>.</p></li>
</ul>
<p>In summary, the code generates FROC, AFROC and ROC plots shown in the top row of Fig. <a href="froc-empirical.html#fig:froc-afroc-roc-raw-seed1">18.2</a>. The discreteness, i.e., the relatively big jumps between data points, is due to the small numbers of cases. Increasing the numbers of cases to <span class="math inline">\(K_1 = 50\)</span> and <span class="math inline">\(K_2 = 70\)</span> yields the lower row of plots in Fig. <a href="froc-empirical.html#fig:froc-afroc-roc-raw-seed1">18.2</a>. The fact that the upper row left plot does not seem to match the lower row left plot, especially near NLF = 0.25, is due to sampling variability with few cases.</p>
<div class="figure"><span id="fig:froc-afroc-roc-raw-seed1"></span>
<img src="13-froc-empirical-examples_files/figure-html/froc-afroc-roc-raw-seed1-1.png" alt="Raw FROC, AFROC and ROC plots with seed = 1: the top row is for $K_1 = 5$ and $K_2 = 7$ cases while the bottom row is for $K_1 = 50$ and $K_2 = 70$ cases, details below" width="672" />
<p class="caption">
FIGURE 18.2: Raw FROC, AFROC and ROC plots with seed = 1: the top row is for <span class="math inline">\(K_1 = 5\)</span> and <span class="math inline">\(K_2 = 7\)</span> cases while the bottom row is for <span class="math inline">\(K_1 = 50\)</span> and <span class="math inline">\(K_2 = 70\)</span> cases, details below
</p>
</div>
<p>Fig. <a href="froc-empirical.html#fig:froc-afroc-roc-raw-seed1">18.2</a> Raw FROC, AFROC and ROC plots with <code>seed</code> = 1: the top row is for <span class="math inline">\(K_1 = 5\)</span> and <span class="math inline">\(K_2 = 7\)</span> cases while the bottom row is for <span class="math inline">\(K_1 = 50\)</span> and <span class="math inline">\(K_2 = 70\)</span> cases. Model parameters are <span class="math inline">\(\mu\)</span> = 1, <span class="math inline">\(\lambda\)</span> = 1, <span class="math inline">\(\nu\)</span> = 1 and <span class="math inline">\(\zeta_1\)</span> = -1. The discreteness (jumps) in the upper row is due to the small number of cases. The decreased discreteness in the lower row is due to the larger numbers of cases. If the number of cases is increased further, the plots will approach continuous plots, like those shown in Chapter <a href="froc-paradigm.html#froc-paradigm">17</a>. Note that the AFROC and ROC plots are contained within the unit square, unlike the semi-constrained FROC plot.</p>
<div id="effect-of-seed-on-raw-plots-1" class="section level4" number="19.3.3.1">
<h4><span class="header-section-number">19.3.3.1</span> Effect of seed on raw plots</h4>
<p>Shown next are similar plots but this time <code>seed</code> = 2.</p>
<div class="figure"><span id="fig:froc-afroc-roc-raw-seed2"></span>
<img src="13-froc-empirical-examples_files/figure-html/froc-afroc-roc-raw-seed2-1.png" alt="Raw FROC, AFROC and ROC plots with seed = 2: the top row is for $K_1 = 5$ and $K_2 = 7$ cases while the bottom row is for $K_1 = 50$ and $K_2 = 70$ cases, details below" width="672" />
<p class="caption">
FIGURE 18.3: Raw FROC, AFROC and ROC plots with seed = 2: the top row is for <span class="math inline">\(K_1 = 5\)</span> and <span class="math inline">\(K_2 = 7\)</span> cases while the bottom row is for <span class="math inline">\(K_1 = 50\)</span> and <span class="math inline">\(K_2 = 70\)</span> cases, details below
</p>
</div>
<p>Fig. <a href="froc-empirical.html#fig:froc-afroc-roc-raw-seed2">18.3</a> Raw FROC, AFROC and ROC plots with <code>seed</code> = 2: the top row is for <span class="math inline">\(K_1 = 5\)</span> and <span class="math inline">\(K_2 = 7\)</span> cases while the bottom row is for <span class="math inline">\(K_1 = 50\)</span> and <span class="math inline">\(K_2 = 70\)</span> cases. Model parameters are <span class="math inline">\(\mu\)</span> = 1, <span class="math inline">\(\lambda\)</span> = 1, <span class="math inline">\(\nu\)</span> = 1 and <span class="math inline">\(\zeta_1\)</span> = -1. Note the large variability in the upper row plots as compared to those in Fig. <a href="froc-empirical.html#fig:froc-afroc-roc-raw-seed1">18.2</a>. The effect of case-sampling variability is most apparent for small datasets.</p>
</div>
</div>
<div id="key-differences-from-the-roc-paradigm-1" class="section level3" number="19.3.4">
<h3><span class="header-section-number">19.3.4</span> Key differences from the ROC paradigm:</h3>
<ul>
<li><p>In a ROC study, each case generates exactly one rating.</p></li>
<li><p>In a FROC study, each case can generate zero or more (0, 1, 2, …) mark-rating pairs.</p></li>
<li><p>The number of marks per case is a random variable as is the rating of each mark.</p></li>
<li><p>Each mark corresponds to a distinct location on the image and associated with it is a rating, i.e., confidence level in presence of disease at the region indicated by the mark.</p></li>
<li><p>In the ROC paradigm, each non-diseased case generates one FP and each diseased case generates one TP.</p></li>
<li><p>In a FROC study, each non-diseased case can generate zero or more NLs and each diseased case can generate zero or more NLs and zero or more LLs.</p></li>
<li><p>The number of lesions in the case limits the number of LLs.</p></li>
</ul>
</div>
</div>
<div id="binned-frocafrocroc-plots-1" class="section level2" number="19.4">
<h2><span class="header-section-number">19.4</span> Binned FROC/AFROC/ROC plots</h2>
<p>In the preceding example, continuous ratings data was available and data binning was not employed. Shown next is the code for generating the plots when the data is binned.</p>
<div id="binned-plots-code1" class="section level3" number="19.4.1">
<h3><span class="header-section-number">19.4.1</span> Code for binned plots</h3>
<div class="sourceCode" id="cb122"><pre class="sourceCode numberSource r numberLines"><code class="sourceCode r"><span id="cb122-1"><a href="froc-empirical-examples.html#cb122-1"></a>seed <span class="ot">&lt;-</span> <span class="dv">1</span>;<span class="fu">set.seed</span>(seed)</span>
<span id="cb122-2"><a href="froc-empirical-examples.html#cb122-2"></a>zeta1 <span class="ot">&lt;-</span> <span class="sc">-</span><span class="dv">1</span></span>
<span id="cb122-3"><a href="froc-empirical-examples.html#cb122-3"></a>K1 <span class="ot">&lt;-</span> <span class="dv">5</span></span>
<span id="cb122-4"><a href="froc-empirical-examples.html#cb122-4"></a>K2 <span class="ot">&lt;-</span> <span class="dv">7</span> </span>
<span id="cb122-5"><a href="froc-empirical-examples.html#cb122-5"></a>Lmax <span class="ot">&lt;-</span> <span class="dv">2</span></span>
<span id="cb122-6"><a href="froc-empirical-examples.html#cb122-6"></a>Lk2 <span class="ot">&lt;-</span> <span class="fu">floor</span>(<span class="fu">runif</span>(K2, <span class="dv">1</span>, Lmax <span class="sc">+</span> <span class="dv">1</span>))</span>
<span id="cb122-7"><a href="froc-empirical-examples.html#cb122-7"></a></span>
<span id="cb122-8"><a href="froc-empirical-examples.html#cb122-8"></a>frocDataRaw <span class="ot">&lt;-</span> <span class="fu">SimulateFrocDataset</span>(</span>
<span id="cb122-9"><a href="froc-empirical-examples.html#cb122-9"></a>  <span class="at">mu =</span> mu, </span>
<span id="cb122-10"><a href="froc-empirical-examples.html#cb122-10"></a>  <span class="at">lambda =</span> lambda, </span>
<span id="cb122-11"><a href="froc-empirical-examples.html#cb122-11"></a>  <span class="at">nu =</span> nu, </span>
<span id="cb122-12"><a href="froc-empirical-examples.html#cb122-12"></a>  <span class="at">I =</span> <span class="dv">1</span>,</span>
<span id="cb122-13"><a href="froc-empirical-examples.html#cb122-13"></a>  <span class="at">J =</span> <span class="dv">1</span>,</span>
<span id="cb122-14"><a href="froc-empirical-examples.html#cb122-14"></a>  <span class="at">K1 =</span> K1, </span>
<span id="cb122-15"><a href="froc-empirical-examples.html#cb122-15"></a>  <span class="at">K2 =</span> K2, </span>
<span id="cb122-16"><a href="froc-empirical-examples.html#cb122-16"></a>  <span class="at">perCase =</span> Lk2, </span>
<span id="cb122-17"><a href="froc-empirical-examples.html#cb122-17"></a>  <span class="at">zeta1 =</span> zeta1</span>
<span id="cb122-18"><a href="froc-empirical-examples.html#cb122-18"></a>)</span>
<span id="cb122-19"><a href="froc-empirical-examples.html#cb122-19"></a></span>
<span id="cb122-20"><a href="froc-empirical-examples.html#cb122-20"></a>frocDataBinned <span class="ot">&lt;-</span> <span class="fu">DfBinDataset</span>(</span>
<span id="cb122-21"><a href="froc-empirical-examples.html#cb122-21"></a>  frocDataRaw, </span>
<span id="cb122-22"><a href="froc-empirical-examples.html#cb122-22"></a>  <span class="at">desiredNumBins =</span> <span class="dv">5</span>,</span>
<span id="cb122-23"><a href="froc-empirical-examples.html#cb122-23"></a>  <span class="at">opChType =</span> <span class="st">&quot;FROC&quot;</span>)</span>
<span id="cb122-24"><a href="froc-empirical-examples.html#cb122-24"></a></span>
<span id="cb122-25"><a href="froc-empirical-examples.html#cb122-25"></a>p1 <span class="ot">&lt;-</span> <span class="fu">PlotEmpiricalOperatingCharacteristics</span>(</span>
<span id="cb122-26"><a href="froc-empirical-examples.html#cb122-26"></a>  <span class="at">dataset =</span> frocDataBinned, </span>
<span id="cb122-27"><a href="froc-empirical-examples.html#cb122-27"></a>  <span class="at">trts=</span> <span class="dv">1</span>, <span class="at">rdrs =</span> <span class="dv">1</span>, <span class="at">opChType =</span> <span class="st">&quot;FROC&quot;</span>, </span>
<span id="cb122-28"><a href="froc-empirical-examples.html#cb122-28"></a>  <span class="at">legend.position =</span> <span class="st">&quot;NULL&quot;</span>)<span class="sc">$</span>Plot</span>
<span id="cb122-29"><a href="froc-empirical-examples.html#cb122-29"></a></span>
<span id="cb122-30"><a href="froc-empirical-examples.html#cb122-30"></a>p2 <span class="ot">&lt;-</span> <span class="fu">PlotEmpiricalOperatingCharacteristics</span>(</span>
<span id="cb122-31"><a href="froc-empirical-examples.html#cb122-31"></a>  <span class="at">dataset =</span> frocDataBinned, </span>
<span id="cb122-32"><a href="froc-empirical-examples.html#cb122-32"></a>  <span class="at">trts=</span> <span class="dv">1</span>, <span class="at">rdrs =</span> <span class="dv">1</span>, <span class="at">opChType =</span> <span class="st">&quot;AFROC&quot;</span>, </span>
<span id="cb122-33"><a href="froc-empirical-examples.html#cb122-33"></a>  <span class="at">legend.position =</span> <span class="st">&quot;NULL&quot;</span>)<span class="sc">$</span>Plot</span>
<span id="cb122-34"><a href="froc-empirical-examples.html#cb122-34"></a></span>
<span id="cb122-35"><a href="froc-empirical-examples.html#cb122-35"></a>p3 <span class="ot">&lt;-</span> <span class="fu">PlotEmpiricalOperatingCharacteristics</span>(</span>
<span id="cb122-36"><a href="froc-empirical-examples.html#cb122-36"></a>  <span class="at">dataset =</span> frocDataBinned, </span>
<span id="cb122-37"><a href="froc-empirical-examples.html#cb122-37"></a>  <span class="at">trts=</span> <span class="dv">1</span>, <span class="at">rdrs =</span> <span class="dv">1</span>, <span class="at">opChType =</span> <span class="st">&quot;ROC&quot;</span>, </span>
<span id="cb122-38"><a href="froc-empirical-examples.html#cb122-38"></a>  <span class="at">legend.position =</span> <span class="st">&quot;NULL&quot;</span>)<span class="sc">$</span>Plot</span></code></pre></div>
<p>This is similar to the code for the raw plots except that at lines 20-23 we have used the function <code>DfBinDataset</code> to bin the raw data <code>frocDataRaw</code> and the binned data is saved to <code>frocDataBinned</code>, which is used in the subsequent plotting routines. Note the arguments <code>desiredNumBins</code> and <code>opChType</code>. The binning function needs to know the desired number of bins (set to 5 in this example) and the operating characteristic that the binning is aimed at (here set to “FROC”).</p>
<div class="figure"><span id="fig:froc-afroc-roc-binned-seed1"></span>
<img src="13-froc-empirical-examples_files/figure-html/froc-afroc-roc-binned-seed1-1.png" alt="Binned FROC, AFROC and ROC plots with seed = 1: the top row is for $K_1 = 5$ and $K_2 = 7$ cases while the bottom row is for $K_1 = 50$ and $K_2 = 70$ cases, details below" width="672" />
<p class="caption">
FIGURE 18.4: Binned FROC, AFROC and ROC plots with seed = 1: the top row is for <span class="math inline">\(K_1 = 5\)</span> and <span class="math inline">\(K_2 = 7\)</span> cases while the bottom row is for <span class="math inline">\(K_1 = 50\)</span> and <span class="math inline">\(K_2 = 70\)</span> cases, details below
</p>
</div>
<div id="effect-of-seed-on-binned-plots-1" class="section level4" number="19.4.1.1">
<h4><span class="header-section-number">19.4.1.1</span> Effect of seed on binned plots</h4>
<p>Shown next are corresponding plots with <code>seed</code> = 2.</p>
<div class="figure"><span id="fig:froc-afroc-roc-binned-seed2"></span>
<img src="13-froc-empirical-examples_files/figure-html/froc-afroc-roc-binned-seed2-1.png" alt="Binned FROC, AFROC and ROC plots with seed = 2: the top row is for $K_1 = 5$ and $K_2 = 7$ cases while the bottom row is for $K_1 = 50$ and $K_2 = 70$ cases, details below" width="672" />
<p class="caption">
FIGURE 18.5: Binned FROC, AFROC and ROC plots with seed = 2: the top row is for <span class="math inline">\(K_1 = 5\)</span> and <span class="math inline">\(K_2 = 7\)</span> cases while the bottom row is for <span class="math inline">\(K_1 = 50\)</span> and <span class="math inline">\(K_2 = 70\)</span> cases, details below
</p>
</div>
</div>
</div>
<div id="structure-of-the-binned-data-1" class="section level3" number="19.4.2">
<h3><span class="header-section-number">19.4.2</span> Structure of the binned data</h3>
<div class="sourceCode" id="cb123"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb123-1"><a href="froc-empirical-examples.html#cb123-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(frocDataBinnedSeed1<span class="sc">$</span>ratings<span class="sc">$</span>NL)</span>
<span id="cb123-2"><a href="froc-empirical-examples.html#cb123-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  num [1, 1, 1:120, 1:4] -Inf 3 -Inf -Inf 1 ...</span></span>
<span id="cb123-3"><a href="froc-empirical-examples.html#cb123-3" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(frocDataBinnedSeed1<span class="sc">$</span>ratings<span class="sc">$</span>LL)</span>
<span id="cb123-4"><a href="froc-empirical-examples.html#cb123-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  num [1, 1, 1:70, 1:2] -Inf 4 4 3 1 ...</span></span>
<span id="cb123-5"><a href="froc-empirical-examples.html#cb123-5" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(frocDataBinnedSeed1<span class="sc">$</span>ratings<span class="sc">$</span>NL)</span>
<span id="cb123-6"><a href="froc-empirical-examples.html#cb123-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb123-7"><a href="froc-empirical-examples.html#cb123-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; -Inf    1    2    3    4 </span></span>
<span id="cb123-8"><a href="froc-empirical-examples.html#cb123-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  378   50   15   12   25</span></span>
<span id="cb123-9"><a href="froc-empirical-examples.html#cb123-9" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">as.numeric</span>(<span class="fu">table</span>(frocDataBinnedSeed1<span class="sc">$</span>ratings<span class="sc">$</span>NL)))</span>
<span id="cb123-10"><a href="froc-empirical-examples.html#cb123-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 480</span></span>
<span id="cb123-11"><a href="froc-empirical-examples.html#cb123-11" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(frocDataBinnedSeed1<span class="sc">$</span>ratings<span class="sc">$</span>LL)</span>
<span id="cb123-12"><a href="froc-empirical-examples.html#cb123-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb123-13"><a href="froc-empirical-examples.html#cb123-13" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; -Inf    1    2    3    4    5 </span></span>
<span id="cb123-14"><a href="froc-empirical-examples.html#cb123-14" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   78   10    5    8   35    4</span></span>
<span id="cb123-15"><a href="froc-empirical-examples.html#cb123-15" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">as.numeric</span>(<span class="fu">table</span>(frocDataBinnedSeed1<span class="sc">$</span>ratings<span class="sc">$</span>LL)))</span>
<span id="cb123-16"><a href="froc-empirical-examples.html#cb123-16" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 140</span></span>
<span id="cb123-17"><a href="froc-empirical-examples.html#cb123-17" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(Lk2Seed1)</span>
<span id="cb123-18"><a href="froc-empirical-examples.html#cb123-18" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 104</span></span>
<span id="cb123-19"><a href="froc-empirical-examples.html#cb123-19" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(Lk2Seed1) <span class="sc">-</span> <span class="fu">sum</span>(<span class="fu">as.vector</span>(<span class="fu">table</span>(frocDataBinnedSeed1<span class="sc">$</span>ratings<span class="sc">$</span>LL))[<span class="dv">2</span><span class="sc">:</span><span class="dv">6</span>])</span>
<span id="cb123-20"><a href="froc-empirical-examples.html#cb123-20" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 42</span></span></code></pre></div>
<p>The <code>table()</code> function converts an array into a counts table. In the first usage, there are 120 x 4 = 480 elements in the array. From the output of <code>table(frocDataBinnedSeed1$ratings$NL)</code> one sees that there are 378 entries in the NL array that equal <span class="math inline">\(-\infty\)</span>, 50 that equal 1, etc. These sum to 480. Because the fourth dimension of the NL array is determined by cases with the most NLs, therefore, on cases with fewer NLs, this dimension is “padded” with <span class="math inline">\(-\infty\)</span>s. One does not know how many of the 378 <span class="math inline">\(-\infty\)</span>s are latent NLs. The actual number of latent NLs could be considerably smaller, and the number of marked NLs even smaller, as this is determined by <span class="math inline">\(\zeta_1\)</span>. The last three statements are important to understand and will be further explained below.</p>
<p>The LL array contains 70 x 2 = 140 values. From the output of <code>table(frocDataBinnedSeed1$ratings$lL)</code> one sees that there are 78 entries in the LL array that equal <span class="math inline">\(-\infty\)</span>, 10 entries that equal 1, etc. These sum to 140. Since the total number of lesions is 104, the number of unmarked lesions is known. Specifically, summing the LL counts in bins 1 through 5 (corresponding to indices 2-6, since index 1 applies to the <span class="math inline">\(-\infty\)</span>s) and subtracting from the total number of lesions one gets: 104 – (10+5+8+35+4) = 104 – 62 = 42, see last line of above code output. Therefore, the number of unmarked lesions is 42. The listed value 78, is an overestimate because it includes the <span class="math inline">\(-\infty\)</span> counts from the fourth dimension <span class="math inline">\(-\infty\)</span> “padding” of the <code>LL</code> array. This happens because some other diseased case had lesions in those location-holders.</p>
</div>
</div>
<div id="misconceptions-about-location-level-true-negatives-1" class="section level2" number="19.5">
<h2><span class="header-section-number">19.5</span> Misconceptions about location-level “true-negatives”</h2>
<p>The quotes are intended to draw attention to a misconception that results when one inappropriately applies ROC terminology to the FROC paradigm. For the 5 / 7 dataset, seed = 1, and reporting threshold set to -1, the first non-diseased case has one NL rated 0.7635935. The remaining three entries for this case are filled with <span class="math inline">\(-\infty\)</span>.</p>
<p>What really happened is only known internal to the simulator. To the data analyst the following possibilities are indistinguishable:</p>
<ul>
<li>Four latent NLs, one of whose ratings exceeded <span class="math inline">\(\zeta_1\)</span>, i.e., three location-level “true negatives” occurred on this case.</li>
<li>Three latent NLs, one of whose ratings exceeded <span class="math inline">\(\zeta_1\)</span>, i.e., two location-level “true negatives” occurred on this case.</li>
<li>Two latent NLs, one of whose ratings exceeded <span class="math inline">\(\zeta_1\)</span>, i.e., one location-level “true negative” occurred on this case.</li>
<li>One latent NL, whose rating exceeded <span class="math inline">\(\zeta_1\)</span>, i.e., 0 location-level “true negatives” occurred on this case.</li>
</ul>
<p>The second non-diseased case has one NL mark rated -0.7990092 and similar ambiguities occur regarding the number of latent NLs. The third, fourth and fifth non-diseased cases have no marks. All four locations-holders on each of these cases are filled with <span class="math inline">\(-\infty\)</span>, which indicates un-assigned values corresponding to either absence of any latent NL or presence of one or more latent NLs that did not exceed <span class="math inline">\(\zeta_1\)</span> and therefore did not get marked.</p>
<p>To summarize: absence of an actual NL mark, indicated by a <span class="math inline">\(-\infty\)</span> rating, could be due to either (i) non-occurrence of the corresponding latent NL or (ii) occurrence of the latent NL but its rating did not exceed <span class="math inline">\(\zeta_1\)</span>. One cannot distinguish between the two possibilities, as in either scenario, the corresponding rating is assigned the <span class="math inline">\(-\infty\)</span> value and either scenario would explain the absence of a mark.</p>
<p>For those who insist on using ROC terminology to describe FROC data the second possibility would be termed a location level True Negative (“TN”). Their “logic” is as follows: there was the possibility of a NL mark, which they term a “FP,” but the observer did not make it. Since the complement of a FP event is a TN event, this was a TN event. However, as just shown, one cannot tell if it was a “TN” event or there was no latent event in the first place. Here is the conclusion: there is no place in the FROC lexicon for a location level “TN.”</p>
<p>If <span class="math inline">\(\zeta_1\)</span> = <span class="math inline">\(-\infty\)</span> then all latent marks are actually marked and the ambiguities mentioned above disappear. As noted previously, when this change is made one confirms that there were actually four latent NLs on the sixth diseased case (the eleventh sequential case), but the one rated -1.237538 fell below <span class="math inline">\(\zeta_1 = -1\)</span> and was consequently not marked.</p>
<p>So one might wonder, why not ask the radiologists to report everything they see, no matter now low the confidence level? Unfortunately, that would be contrary to their clinical task, where there is a price to pay for excessive NLs. It would also be contrary to a principle of good experimental design: one should keep interference with actual clinical practice, designed to make the data easier to analyze, to a minimum.</p>
</div>
<div id="comments-and-recommendations-1" class="section level2" number="19.6">
<h2><span class="header-section-number">19.6</span> Comments and recommendations</h2>
<div id="why-not-use-nls-on-diseased-cases-1" class="section level3" number="19.6.1">
<h3><span class="header-section-number">19.6.1</span> Why not use NLs on diseased cases?</h3>
<p>The original definition of the AFROC <span class="citation">(<a href="SplitPlotChapter.html#ref-chakraborty1989maximum" role="doc-biblioref">Dev P. Chakraborty 1989</a>; <a href="SplitPlotChapter.html#ref-RN206" role="doc-biblioref">Dev P. Chakraborty and Winter 1990</a>)</span>, but missing the “1” nowadays appended to the acronym, was introduced in 1989. It used the maximum rated NL on every case to define the FPF-axis. The paper <span class="citation">(<a href="SplitPlotChapter.html#ref-RN1496" role="doc-biblioref">Phillip C. Bunch et al. 1977</a>)</span> suggested the same procedure. At that time, it seemed a good idea to include all available information and not discard any highest rated NLs. Usage of the AFROC1 as the basis of analysis is not recommended: the only exception is when the case-set contains only diseased cases although it is not clear to the author why anyone would wish to conduct an observer performance study with diseased cases only, since it sheds no light on the basic imaging task of discriminating non-diseased from diseased cases.</p>
<p>The reason for excluding highest rated NLs on diseased cases is that they have a fundamentally different role in the clinic from those on non-diseased cases. A recall due to a highest rated NL on a diseased case where the lesion was not seen is actually not that bad. It would be better if the recall were for the right reason, i.e., the lesion was seen, but with a recall for the wrong reason at least the doctors get a second chance to find the lesion. On the other hand, a recall resulting from a highest rated NL on a non-diseased case is unequivocally bad. The patient is unnecessarily subjected to further imaging and perhaps invasive procedures like needle-biopsy in order to rule out cancer that she does not have. All this costs money, not to mention the physical and emotional trauma inflicted on the patient.</p>
<p>Another reason, more subtle, is that including highest rated NLs makes the AFROC1 curve disease-prevalence dependent (this issue was mentioned earlier in connection with the EFROC). Two investigators sampling from the same population, but one using a low-prevalence dataset while the other uses an enriched high-prevalence dataset will obtain different AFROC1 curves for the same observer. This is because observers are generally less likely to mark NLs on diseased cases. This could be satisfaction of search effect26 where it is known that diseased cases are less likely to generate NL marks than non-diseased ones; it is as if finding a lesion “satisfies” the radiologist’s need to find something in the patient’s image that is explanatory of the patient’s symptoms. Also, from the clinical perspective, finding a lesion is enough to trigger more extensive imaging, so it is not necessary to find every other reportable suspicious region in the image, because the radiologist knows that a more extensive workup is “in the works” for this patient. Suffice to say the author has datasets showing strong dependence of number of NLs per case on disease state. More commonly, the number of NLs per case (the abscissa of the upper most operating point on the FROC) is larger if calculated over non-diseased cases than over diseased cases. So the observed FROC and the AFROC1 will be disease prevalence dependent. If disease prevalence is very low, the curves will approach one limit, extending to larger <span class="math inline">\(\text{NLF}_{\text{max}}\)</span> and <span class="math inline">\(\text{FPF}_{\text{max}}\)</span>, and if disease prevalence is high, the curve will approach a different limit, extending to lower <span class="math inline">\(\text{NLF}_{\text{max}}\)</span> and <span class="math inline">\(\text{FPF}_{\text{max}}\)</span>. The logic is also an argument against using the FROC curve, but there are several other issues with the FROC, which are much more serious.</p>
</div>
<div id="recommendations-1" class="section level3" number="19.6.2">
<h3><span class="header-section-number">19.6.2</span> Recommendations</h3>
<p>Table @tef(tab:recommendations-froc-empirical) summarizes the different operating characteristic possible with FROC data and the recommendations.</p>
<table>
<caption>
<span id="tab:recommendations-froc-empirical">TABLE 18.2: </span>Summary of operating characteristics possible with FROC data and recommendations. In most cases the AUC under the wAFROC is the desirable operating characteristic.
</caption>
<thead>
<tr>
<th style="text-align:left;">
Operating characteristic
</th>
<th style="text-align:left;">
Abscissa
</th>
<th style="text-align:left;">
Ordinate
</th>
<th style="text-align:left;">
Comments
</th>
<th style="text-align:left;">
Recommendation
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
ROC
</td>
<td style="text-align:left;">
FPF
</td>
<td style="text-align:left;">
TPF
</td>
<td style="text-align:left;">
Highest rating used to infer FPF and TPF
</td>
<td style="text-align:left;">
Yes, if overall sensitivity and specificity are desired
</td>
</tr>
<tr>
<td style="text-align:left;">
FROC
</td>
<td style="text-align:left;">
NLF
</td>
<td style="text-align:left;">
LLF
</td>
<td style="text-align:left;">
Defined by marks; unmarked cases do not contribute
</td>
<td style="text-align:left;">
No
</td>
</tr>
<tr>
<td style="text-align:left;">
AFROC
</td>
<td style="text-align:left;">
FPF
</td>
<td style="text-align:left;">
LLF
</td>
<td style="text-align:left;">
Highest rating used to infer FPF
</td>
<td style="text-align:left;">
Yes, if number of lesions per case less than 4 and weighting not relevant
</td>
</tr>
<tr>
<td style="text-align:left;">
AFROC1
</td>
<td style="text-align:left;">
FPF1
</td>
<td style="text-align:left;">
LLF
</td>
<td style="text-align:left;">
Highest NL ratings over every case contribute to FPF1
</td>
<td style="text-align:left;">
Yes, only when there are zero non-diseased cases and lesion weighting not relevant
</td>
</tr>
<tr>
<td style="text-align:left;">
wAFROC
</td>
<td style="text-align:left;">
FPF
</td>
<td style="text-align:left;">
wLLF
</td>
<td style="text-align:left;">
Weights, which sum to unity, affect ordinate only
</td>
<td style="text-align:left;">
Yes
</td>
</tr>
<tr>
<td style="text-align:left;">
wAFROC1
</td>
<td style="text-align:left;">
FPF1
</td>
<td style="text-align:left;">
wLLF
</td>
<td style="text-align:left;">
Weights affect ordinate only; maximum NL rating over every case contributes to FPF1
</td>
<td style="text-align:left;">
Yes, only when there are zero non-diseased cases
</td>
</tr>
</tbody>
</table>
<p>The recommendations are based on the author’s experience with simulation testing and many clinical datasets. They involve a compromise between statistical power (the ability to discriminate between modalities that are actually different) and reliability of the analysis (i.e., it yields the right p-value).</p>
<ul>
<li><p>AFROC1 vs. AFROC: Unlike the AFROC1 figures-of-merit, the AFROC figures-of-merit do not use non-lesion localization data on diseased cases, so there is loss of statistical power with using the AFROC FOM. However, AFROC analyses are more likely to be reliable. The AFROC1 figures-of-merit involve two types of comparisons: (i) those between LL-ratings and NL-ratings on non-diseased cases and (ii) those between LL-ratings and NL-ratings on diseased cases. The comparisons have different clinical implications, and mixing them does not appear to be desirable. The problem is avoided if one does not use the second type of comparison. This requires further study, but the issue does not arise if the dataset contains only diseased cases (e.g., nodule-free cases are rare in in lung cancer screening using low-dose computerized tomography) when the AFROC1 figures-of-merit should be used.</p></li>
<li><p>Weighted vs. non-weighted: Weighting (i.e., using wAFROC or wAFROC1 FOM) assures that all diseased cases get equal importance, regardless of the number of lesions on them, a desirable statistical characteristic, so weighted analysis is recommended. Based on the author’s experience, there is little difference between the two analyses when the number of lesions varies from 1-3. There is some loss of statistical power in using weighted over non-weighted figures-of-merit, but the benefits, vs. ROC analysis, are largely retained. Unless there are clinical reasons for doing otherwise, equal weighting is recommended.</p></li>
<li><p>The (highest rating inferred) ROC curve is sometimes desirable to get case-level sensitivity and specificity, as these quantities have well understood meanings to clinicians. For example the highest non-trivial point in Fig. 13.5 (F), defined by counting all highest rated marks, yields a relatively stable estimate of sensitivity and specificity, as described in a recent publication27.</p></li>
</ul>
<p>A paper has questioned the validity of the highest rating assumption28. Two other methods of inferring ROC data from FROC data have been suggested5, and are implemented in <code>RJafroc</code>: the average rating and the stochastically dominant rating. The author has applied both methods of inferring ROC data, in addition to the highest rating method, to the data used in Ref. 28. The results are insensitive to the choice of inferring method: so if the highest rating method is not valid, neither are any of the other proposed methods . A paper supporting the validity of the highest rating assumption has since appeared29. The highest rating assumption has a long history. See for example Swensson’s LROC paper30 and other papers published by Swensson &amp; Judy. It is intuitive. If an observer sees a highly suspicious region and a less suspicious region, why would the observer want to dilute the severity of the condition by averaging the ratings? The highest rating captures the rating of the most significant clinical finding on the case, which is usually the reason for further clinical follow-up.</p>
<p>The AFROC and wAFROC are contained within the unit square and provide valid area measures for comparing two treatments. Except in special cases this is not possible with the FROC.</p>
</div>
</div>
<div id="froc-empirical-Discussion" class="section level2" number="19.7">
<h2><span class="header-section-number">19.7</span> Discussion</h2>
<p>This chapter started with the difference between latent and actual marks and the notation to describe FROC data. The notation is exploited in deriving formulae for FROC, AFROC, and inferred ROC operating characteristics obtainable from FROC data. Coded examples are given of FROC, AFROC and ROC curves using a FROC data simulator. These allow examination of the FROC data structure at a deeper level than is possible with formalism alone.</p>
<p>Since there are serious misunderstandings and confusion regarding the FROC paradigm, several key points are re-emphasized:</p>
<ol style="list-style-type: decimal">
<li>An important distinction is made between observable and unobservable events. Observable events, such as unmarked lesions, can safely be assigned the <span class="math inline">\(-\infty\)</span> rating. Negative infinity ratings cannot be assigned to unobservable events.</li>
<li>A location level “true negative” is an unobservable event and usage of this term has no place in the FROC lexicon. This is a serious misunderstanding among some experts in ROC methodology.</li>
<li>The FROC curve does not reach unit ordinate unless the lesions are easy to find.</li>
<li>The limiting end-point abscissa of the FROC, i.e., what the observer would have reached had the observer marked every latent NL, is unconstrained to the range (0,1).</li>
<li>The inclusion of NLs on diseased cases introduces an undesirable dependence of the FROC curve on disease prevalence. A valid operating characteristic, an example of which is the ROC, should be independent of disease prevalence.</li>
<li>The notion that maximum NLF is determined by the ratio of the image area to the lesion area is incorrect. This simplistic model is not supported by eye-movement data acquired on radiologists performing clinical tasks.</li>
<li>In contrast to the FROC, the limiting end-point of the AFROC is constrained, i.e., both coordinates are in the range (0,1).</li>
<li>For the observer, who does not generate any marks, the operating point is (0,0) and the AFROC is the inaccessible line connecting (0,0) to (1,1), contributing empirical AUC = 0.5. This observer has unit specificity but zero sensitivity, which is better than chance level performance (AUC = 0). The corresponding ROC observer displays chance level performance and gets no credit for perfect performance on non-diseased cases.</li>
<li>The weighted-AFROC curve is the preferred way to summarize performance in the FROC task. Usage of the FROC to derive measures of performance is strongly discouraged.</li>
<li>The highest NL rating carries more information about the other NLs on the case than the rating of a randomly selected NL. The implication is that the AFROC does not sacrifice much power relative to FROC curve based measures.</li>
<li>The highest rating method of inferring data is adequate for most purposes; alternatives such as average and stochastically dominant rating do not appear to have substantive advantages.</li>
<li>The highest rating inferred ROC curve is a useful way to summarize case-level sensitivity and specificity from FROC data.</li>
</ol>
<p>It is ironic that the optimal way of summarizing FROC data, namely the AFROC, has been known for a long time, specifically 1977 in the Bunch et al papers3,31,32, although they imply that it is not the preferred way. It has also been known since 1989 in a paper by the author4, which states unambiguously that the area under the AFROC is an appropriate figure of merit for the FROC paradigm. Unfortunately, this recommendation has been largely ignored and CAD research, which would have benefited most from it, has proceeded, over more than two decades, almost entirely based on the FROC curve. Currently there is much controversy about CAD’s effectiveness, especially for masses in breast cancer screening. The author believes that CAD’s current poor performance is in part due to choice of the incorrect operating characteristic used to evaluate and optimize it.</p>
<p>If the author appears to have “picked on others mistakes,” and on CAD, it is with the objective of learning. The author has made his own share of mistakes15, which are unavoidable in science, and has contributed to some of the confusion, an example of which is the temporary recommendation of the AFROC1 noted above: progress in science rarely proceeds in a straight line.</p>
<p>A legitimate concern at this point could be that most of the recommendations are based on the FROC data simulator. The author could have shown examples from actual datasets, and he has many, but chose not to do so. One does not know the truth with clinical datasets and varying parameters in a systematic manner is not possible. Details of the simulator are deferred to Chapter 16, as well as predictions of the simulator, Chapter 17.</p>
<p>Having defined various operation characteristics associated with FROC data, and how to compute the coordinates of operating points, it is time to turn to formulae for figures of merit that can be derived from these plots, without recourse to planimetry (i.e., without actually “counting squares”), and their physical meanings, the subject of the next chapter.</p>
</div>
<div id="froc-empirical-miscellaneous" class="section level2" number="19.8">
<h2><span class="header-section-number">19.8</span> Miscellaneous</h2>
<div id="froc-empirical-case-vs-view" class="section level3" number="19.8.1">
<h3><span class="header-section-number">19.8.1</span> TBA Cased based vs. view-based scoring</h3>
<p>So far, the implicit assumption has been that each case or patient is represented by one image. When a case has multiple images or views, the above definitions are referred to as <em>case-based scoring</em>. A <em>view-based scoring</em> of the data is also possible, in which the denominator in Eqn. <a href="froc-empirical.html#eq:froc-empirical-NLF1">(18.3)</a> is the total number of views. Furthermore, in view-based scoring multiple lesions on different views of the same case are counted as different lesions, even thought they may correspond to the same physical lesion <span class="citation">(<a href="SplitPlotChapter.html#ref-RN1652" role="doc-biblioref">Yoon et al. 2007</a>)</span>. The total number of lesion localizations is divided by the total number of lesions visible to the truth panel in all views, which is the counterpart of Eqn. <a href="froc-empirical.html#eq:froc-empirical-LLFr">(18.7)</a>. When each case has a single image, the two definitions are equivalent. With four views per patient in screening mammography, case-based NLF is four times larger than view-based NLF. Since a superior system tends to have smaller NLF values, the tendency among researchers is to report view-based FROC curves, because it makes their systems “look better”<a href="#fn11" class="footnote-ref" id="fnref11"><sup>11</sup></a>.</p>
</div>
</div>
<div id="froc-empirical-references" class="section level2" number="19.9">
<h2><span class="header-section-number">19.9</span> References</h2>

</div>
</div>
<div class="footnotes">
<hr />
<ol start="11">
<li id="fn11"><p>this is an actual private comment from a prominent CAD researcher<a href="froc-empirical-examples.html#fnref11" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="froc-empirical.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="froc-paradigm-froc-vs-afroc.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["RJafrocBook.pdf", "RJafrocBook.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
